apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: my-keycloak-operator
  labels:
    app: sso
spec:
  instances: 1
  externalAccess:
    enabled: True
    host: keycloak.tiborpilz.dev
    tlsTermination: reencrypt
