apiVersion: ENC[AES256_GCM,data:i60=,iv:lbeNmyP08Aym0X9kP3+BY+Iad7s0k2ebBk64tNzIWGg=,tag:MbugcokmftTNLk3RPN22nA==,type:str]
kind: ENC[AES256_GCM,data:D5LYmQ7L,iv:03pbPAh4RI0A4aVVB2ekmWp5yt4Ln9hkW+Qqcv/aWFs=,tag:sdakZDFuskXDLr8ZH0+vjQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:bbMO/TOVbFg5RPrfDefLWMLPcVk=,iv:+xiLS1Zr/jnBSYmqCMIi1N7xP4z/oV7HvSrwN5XsUGM=,tag:o62GAoXKeYVhkLV8ZeZvuw==,type:str]
    namespace: ENC[AES256_GCM,data:6XFMI+hOrMgotK4=,iv:wuDtwJyPlHzKczlf6akk915CY6r0CA4M8XpRCcrDdqw=,tag:u+l14GX2uf4kIG9XlJxTBg==,type:str]
type: ENC[AES256_GCM,data:f23lKGKB,iv:qnJBszaQs5stU7b4jDZQgp2e/6rQLquESgyNrVJMqL4=,tag:sZIkcfEBz8iTgtHaVGnXmA==,type:str]
data:
    client-id: ENC[AES256_GCM,data:zbn9CFT2B5Y=,iv:2/7LOCveGs1SlreMi++a0mEpKLcl0NgNM/60UoMx710=,tag:UaHMtoeM62ro4poVzOYHDw==,type:str]
    client-secret: ENC[AES256_GCM,data:3x6H7HnmGGxLsB98bZ/d9GpBDQuem8xkbmrsCiJA5jHg6wDOUFU01HUfl0ERn8jToFQzPBmXXEf12GcpPXZyyNl+bvIerT4ptu4ezYi22/0w+RAY2i2LJg==,iv:XydshwSwOBlUdCsIfIJL/w0COdRccjkCW5cuaerQhQI=,tag:cnj9h2jiWci1IxDCm3vuDA==,type:str]
    cookie-secret: ENC[AES256_GCM,data:QV0C8zAFGdKnXjbH0SGrCRrLe6iN+6tPF3Gj+7luG8cRuzOaCAhdtv8UASRxuvxoz0EjoauVdPXrutlN,iv:Mcw+JJAV75ma9AAto4xneGqchOqwd3amRkW1IYSavD0=,tag:DQOEJ7YSEagLelfwljZTDA==,type:str]
sops:
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMDFCSFVLTHNUT1BMSEVa
            MGlJbTQycE83Nkc5ZVJsR2dZRDFXRXVZYnpFCnB3OGpoZjVQR25JMjVtdHBnYkVE
            SjBNSGI3Q3NCaWswanNGN0VCNTB3d0kKLS0tIEM1eUhIRkpIVjRmUnlySUk0MmtZ
            U3M0eGl0VDNTd0Eya3VaeUs0R0tMTHcKKgF1iuK5HTwh5cH6wLR0OVvwvwZm47co
            gv/pHRzbAx8SWv8ywEIuox3/hYIQP20l1KJqjdjyRIrzM/oOK8t8gw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiYjhJaUU1WTl6Q3dnNEEx
            alF1Y1F6THMvQ0ZFR0RiVWN0dDdldGtkU3hBCjA3ZzBtQ0dPSWRKY29VcjRFNm5s
            ZnNXb0pMUTc0NjVTQXFHaTlPaTAvcDQKLS0tIDdES1NTczNHUHl3dDRWVjExZDBZ
            MlBuMHo3alFFZHlhV1lDQmZURkg3S0EK6b1qZe8k5qaxEdte0gX1w5QJ7Oo0YxIT
            W5lVNLqkwsObDi92HhT3wbQ5I5lGiK1adnpMoP9dA9KlvA+8uCdh9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T12:59:27Z"
    mac: ENC[AES256_GCM,data:6smpw/FJML+cJVwFgH3nh1jt6zYpfJaL5xtTQP1hNvBx4OMbytYurEzAFaheqhsGt4t+3Z/SD3eQsBqGd9HhGN6S0od9qk4DVTRb8h0AnlbE6NWcoadNC0UdwsRiNsKPxWhenaV77jyncQ+k46pjrkPgZTucGtzxuXlrolBoqCk=,iv:Rt9iNeupN3EpP0wZwMw8zTQWAmuWdZX2j+rqTlDfthw=,tag:PSPktXQWsQ63AODRK054MA==,type:str]
    pgp:
        - created_at: "2026-07-12T20:03:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0IKwDTH3WibAQ/8CL72f9XuxemTVM4jMfaES9x7E5vyFeO8klQ9r73oaPta
            U+4+i7eNh7ARHrnDgp2aTv7QG/OzJJp2+F2hCuNqeTOIOO94DVCP6LZ3M+JTV/N4
            GT5Al6JrwrskylCtxMWkUlQmgVqMDQxdPg0/G4GhB6kKbEJ1jr5qwUj0i0eMaLPd
            p8jUta93wq17dr016CjwdDZUtB1vLdMhxjNA966wZZj62gaYUJbLxkM+c7W9ze43
            2Sfyzjl5fkkw6HOnFcPLFHF0n8VWkK9EUBSTGcwMsckwnEn8tNGdpaSn2JHKe7Ca
            XY9Gi8MnkA+GP2UKND2S9GJ8OWhdcu0fqL8nn/xGurp++lr0DfhJWRKFIsXbSYGV
            tQl/IDoPqTpSTsI+Y5+3wA/Yr9xuidWMfWdOpChjuABPJaTMK+/XS2Ezuv6lNc4C
            tm7jezsl0oil8kzVggsC526vKXyICXDPmnm884lL3XvJoZL6gBLR7HQevrAckwjS
            9yW+Ft7D95AJhlPyxcN5xyWcMkl5dnmdYRRTZyYIxhYBe/jwVG6cTjremLzB8K1D
            P/ehx+LVK/0mn/HmeWIaIg+A7H5BIJy3x3gEvseo9zjVcHv5o1AMtb7TAgs2Fq0+
            M43RvFY/FUcNQE9Vlbz8fy11QTGIHqw2uekbGX+Bsbl/AhPSW2lLe/JxBqZfsHHS
            XgEPuD2z5EBoLjHdrzlsvPq6KINyDbklwJsC1y/r1pYS5nv4RW/jTJp0fS/xxupp
            s8yzcYT+MEXS92/grQUA9uMfbhq2b+TvODPRkOCInHLguJrOZ+atY/98uWrSiBs=
            =ZqE6
            -----END PGP MESSAGE-----
          fp: 03746612698994281D322B09923BC5E9B4E9509B
    unencrypted_suffix: _unencrypted
    version: 3.12.2
