apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: hubble-secrets
    namespace: hubble-auth
spec:
    secretTemplates:
        - name: oauth2-proxy-secrets
          annotations:
            reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
            reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: authentik
            reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
            reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: authentik
          data:
            client-id: ENC[AES256_GCM,data:Q8/HH+PyjRY=,iv:NJ/wakRDK1eJrYKen4MVXG4NZ9YsmtDM1+VMcns3Saw=,tag:dyKh3UYbsoa0K/jmlMAVrQ==,type:str]
            client-secret: ENC[AES256_GCM,data:ec/DrO5VVxC3w67ewXXVT/00vzrCZObVLdMqRnlAoHmlM0aDjxLF44WhDPolfl9qbDDVZwM/m19UBU+RgDgdB7QjgZU+3CB7QZr7vA58pE8VC82JCJ8SMw==,iv:5X0Gro+UGvvwRI0GrTWTX0UzBtIz4zU+1k9rWH7eZQk=,tag:rPRKTTYZP6QQvLiWmopDBA==,type:str]
            cookie-secret: ENC[AES256_GCM,data:3Rns1zeG9/iI2aAA9Yzulz4ZlqeU8oSbpDNiabgi7H6p1yhaOrY/jko4S3MH9/IED5kY/p06GbGSLZT9,iv:N+GOc0E8bIp7JC7LJQSIfwlTuAqVo5iXAAchlgb7nHU=,tag:urejlyW+rRD74QRZ+kX6Kw==,type:str]
sops:
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMG0xcCs1SkFPNGNLR1Ru
            bE9sSGV3b1RBeGV4SjdPR29XQ25VZkxMSUdZCklkVzBUOWdiVkcyeEIwYUtuTEM3
            SlVyb3VKanNQOFJIcFZOdkp5Z0R6WjAKLS0tIE5UVCtJWEpuZityVWlMR3dsaFc5
            aEJyVFVVVzdKR002dUprRjZPb3VqTzQKBsj1Qw8zBkEGAxKpQN/SIXP/y88PQo3w
            XGJE8QuUPcbzTubhGWKZLI0rF4pFBQak/uaHniYhnavf9NXdzNvkyw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbzMrWlVGTzZSa2RwdkRw
            MGE5YTB5K1FlOGdWbmpMVm5jMnpacTNDc0E4CmRUbXpqanAwSjY1SzR0M2h6N3JO
            MW45NC9lYy9uaTRPMVZxak5WN2hUVk0KLS0tIFVJWnZHcUNxa0ZnMFJnWTB1ekdh
            bjF1MnRyMUN0Mmd2cStpTmE1T25ZaEUK9E/5d/MLYCCS0Z4/HIYm34D2NF/PW117
            1E5ad/O8hkbQdeEnkC7DUJpmo5oU+JbGntOH0NMULzfYLSeYivJXew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-21T16:59:52Z"
    mac: ENC[AES256_GCM,data:1Dt3frsng13VpWq/Jn3l2BFxgmdjWP7OcKMlYBd3MKhmAUNcILF+nhAxWx959PuOT2rSaMsNYz24GwGzeDUbpKeA6cycOm0UPGWPjcPanTD5+W9HYo02PY7oB/P9zNr47xUUpdsnsjioyeCVTM9pgHLfrcmLvnr7vsso0f85YrA=,iv:PWjp2W/KEPxf/hAXz0EI/w1raPSSaYHpJotraAO7s2g=,tag:qn2IJ1YDf6w1fdnKgEJWwg==,type:str]
    pgp:
        - created_at: "2026-08-21T16:59:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0IKwDTH3WibAQ//c+N7egbc74SIvbqdlUsseArpZbxt1oebFGQF6JCLhcVB
            EX5VW6oxgMadcXQ8PZ+f09hfEUpgX/kv545YfEVAG+WgE1GjksBwWBBwBMeJwMy6
            qgjXy7qvNBnI3+luyQExgGeWmvCNW3WULsCGYr3ch4tbCLHsu9UWLJl1TsR7OSuR
            iKXeXNfts5lfWFssVJxEfAe20/2+SCnOhjUSc8XiuXaSgwXYlGIAIK2piQd5IIlC
            N0IZmRkeAbpFJxmPIlqeM+FgHfX6Yhf4jvyG8xYexZ2dupqI+pTAOXHYghdHE8hJ
            r5/F4N2hSmi4hous/AWf6S5oKO/X1uYOJm6NWyCE0Yv3v9zdd8odRUR5KUQQdrv0
            3qXzz8YSjYcu6zkvYmun8QzCgvgGuCsGGakMgMNVWCKxkgxKp14kI5G/ohSckZag
            Z3BgFmakvheg5OSXqZ87dkpjLDkuMnINfKBlWOWn0VfN6gT/cEqB5cJ/hqB89Ddw
            kqVnGsJNwqvEepKvVJ70esq5ZNeFi4NbPYuvyAxRuN8alAp+5qRVOR+s4uU8cdbP
            PNOaRktwTEuRSmVYlEb0qK9dS06zA3rKUY381J//Gjx9NNmTGVOqUR7mHx1jYMXp
            vIbUoDx9KqJhJjMmVSQcXdrZLlC9wlBg4s9DJfJ5ZJ330t/iSy3qreZIKiSMBfjS
            XgHD6oOtsFbDe1ni2xQ/yKuvCTyDcE7EUTWd5UP4xA0apB4dTQ87UefE6uXmXmUh
            dJj6rm2WjtHEWKpDnRkg0rWfvPW09iFDzvUGGVbL7pk4JvMY+k2bgC6yw+N8opI=
            =ly9o
            -----END PGP MESSAGE-----
          fp: 03746612698994281D322B09923BC5E9B4E9509B
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
