apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: alertmanager-secrets
    namespace: observability
spec:
    secretTemplates:
        - name: alertmanager-oauth2-proxy-secrets
          annotations:
            reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
            reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: authentik
            reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
            reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: authentik
          stringData:
            client-id: ENC[AES256_GCM,data:aNrDUa6tXS+FdOY+,iv:q3LLts5XLZwT3N0hZDkbDexoZkUcyMr8LYGQzNBY84c=,tag:fgLcy2zY8johE2036G3Vtw==,type:str]
            client-secret: ENC[AES256_GCM,data:+q/BhoQTccn0RJ5mDLCtpAe+viaazZlRvu5gf8tZBn+/6tkLyRtmJA==,iv:bKFWyrueTj/hSgo4on/hngKUDggkLXjFA5lwcgrFMZw=,tag:5k4ByU97dqsV/4KQuTMq5w==,type:str]
            cookie-secret: ENC[AES256_GCM,data:Blacb4hdqdFHiOauZdn+arzxs1Wgbej50Ew+Gc4/aKBBkvH9SXXFRC/svzc=,iv:z9kokLPy6KBcZRs/O1W7ZEd6EsNt8hGl5Fx8NKDMFW8=,tag:keXjGrOpOrMJss0GJEzdwQ==,type:str]
sops:
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQm1tV3piNEQ4QnVLZGww
            VXRJa1JrWldwb281NlZxQS9pS3UwS0JkU0c4CktWUXAwbXkvZk9wOGtxSUVVRG00
            V2NiNWJ3cU5IWDh2bjR3ZXUzbmFrVzQKLS0tIGdIcU8yV3YrS2NTTDR2NmlvRWc3
            OGpwdnNkbjdlemJRT0dJczROdENDRFUKncQvlw1Mndgq67Z4cVFh3fYTaWLz9nSQ
            CQGAJ/+mH7JfVtKc4l/K2j68olSJs1zyTvbmvp5VXao+ISfypwqvPg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEYU1HTjhOK0R2dG1HUDBP
            czBFTkdQLzJkUUpZZDhPRVpJTm01a09XUEdFCmdLTUJmVjREcXZBRGdhR283ekZK
            RkdJNjBqcDdPS1dUUUxCL29nWkI5dzgKLS0tIDZNd2NHS2VpQkk0RTNQbG8xYmhL
            bGlmSGZkZkVWbFE1N05zRlhkMnlxVGMKbRHxAZYj7ffVLDlY3Z+zXxzqs6bEX1Dw
            n0VGtxLRoGHauhjZKOq0jUIDzNjstGSwjf6xSYh2W1UqVH+qSMIBfQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gzf883y8p0wfy5yjn5l3l2axnqxdgtw2zdcp8jqsrk65m7gf6y6qzgkf63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVRkk5Sm9USVVpQWMzUDRo
            anFDQXlVZkdpMXM3dGhXd1Iwa2ZleU0rTXgwCnpYU2hIaTBUUk51OHlleEswWTBW
            STNpS1pjUTh2SkNZS2VLVVk5cUZLRTQKLS0tIG1WaXZlWlhqd0JQejA2dzBub0cz
            MDJzSytUNGl6emJzenZmTlpKd1lNY1EKLzRzNu3+RMmpJ8/WEyfQkbDH2wuduWm4
            +6ABf3Gg9w9NvRO4Hm5evZ+ilVupfLqNim4kGmkg7y0VQjgTgGyvAQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1j460k9yf4l3smlegue9yx4lwm70cr02308ea5wnpsuqagm25tgrsmfmpj2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4UE9sQkhXSHdoZll1SEdL
            OFpKOFVsZWNRYWgwaUZTLzVpeTNVWGh0NXdjCmV1UHkvcFp3R0JBaFJCZzRxNU5T
            NWtZYUJ6WndkQmNsTUVadEh1eWRvY28KLS0tIGRGcWEzbkI5dXJ3MGJiY2JRZ2xH
            Tm9QYUVQa1pRNm5heFB4Z0RzMWg4clEKAf+mvzH4oaHCdxEZtPjbyHvH6afSd8CX
            nfrhJ7whIlL3hfpsHSdq6oMFcflgQ9pmtfgJehaB/dklduqFerbK0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-30T12:25:54Z"
    mac: ENC[AES256_GCM,data:cl5p6PS+0nmEQkYlz/fX9Lf4T2q0esVmP4N/vNzXuzS7mt1x9usshhxgysVs4gox4/Ra7EVb3gb44nXimClrJfqlngRO/2yBGNInjw/TAqdHHBIbBCGZTrwxxFQIdzAHMLFwzleNCJcnA4zBKJIR/4EN2J6x6a0M+VnfQsgFI+8=,iv:BQ/fnmFo7ZaXihrXK14uYy81xsjiZ+mJ3sUBiKl5uWk=,tag:RecMPmRSvpo7V7Y6gsnX6w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
