apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.6.3
    helm:
      releaseName: loki
      valuesObject:
        deploymentMode: SingleBinary
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          storage:
            type: filesystem
          schemaConfig:
            configs:
              - from: "2024-04-01"
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: index_
                  period: 24h
          limits_config:
            retention_period: 168h
            allow_structured_metadata: true
            volume_enabled: true
          compactor:
            retention_enabled: true
            delete_request_store: filesystem
          server:
            grpc_server_max_recv_msg_size: 8388608
            grpc_server_max_send_msg_size: 8388608
        singleBinary:
          replicas: 1
          persistence:
            enabled: true
            storageClass: ceph-block
            size: 20Gi
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 512Mi
        gateway:
          enabled: true
          replicas: 1
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 64Mi
        read:
          replicas: 0
        write:
          replicas: 0
        backend:
          replicas: 0
        chunksCache:
          enabled: false
        resultsCache:
          enabled: false
        minio:
          enabled: false
        lokiCanary:
          enabled: false
        test:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=false
