apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secrets.enc.yaml
  - argo-app-kube-prometheus-stack.yaml
  - argo-app-loki.yaml
  - argo-app-alloy.yaml
  - alloy-rbac.yaml
  - argo-app-jaeger.yaml
  - argo-app-jaeger-oauth2-proxy.yaml
  - argo-app-otel-collector.yaml
  - httproute-grafana.yaml
  - httproute-jaeger.yaml
