apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: observability-secrets
    namespace: observability
spec:
    secretTemplates:
        - name: grafana-secrets
          annotations:
            reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
            reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: authentik
            reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
            reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: authentik
          stringData:
            GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:mudFlxY=,iv:GtbP9J0gx4JkEPdzckz1DXq6I6jiDbUDG14subgRACE=,tag:WEj1SAyBMRMzLfXnYB5CUg==,type:str]
            GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:ekN2/zHG6EKaVjniM8lUq24gthNl5+m/5rWMJk3IYH6JOvgoCE1HkA==,iv:3BZ3V7KLc9DyAEg4euVX3iJMcC8xaN++7JWyJUS2gas=,tag:sv5qdY6vMVvhS2UVA0W+kw==,type:str]
            GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:ujx/FEyKtQ==,iv:8MwXKSlZo93UWRjyYIOlf1K+4sT5geKZXHNK+inFsqQ=,tag:pbJGzsV09qSw2A9Bt3Z5ig==,type:str]
            GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:E/mC+rSRjFpl+f27UMlNcNxOGYS3JsLB1XeC+Yr+LxVa3RcIAfiZDQ==,iv:XBIjrDSgf7Qq/QS5M1PYofH0kN6vlPKbJ3fFjSBDhS0=,tag:d0ga9wLFK6h6D4eVVRGuYg==,type:str]
        - name: jaeger-oauth2-proxy-secrets
          annotations:
            reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
            reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: authentik
            reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
            reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: authentik
          stringData:
            client-id: ENC[AES256_GCM,data:yLaBf03r,iv:9+cpHsXoF4btMZT1HDzQzPOWo4Kh8DpuQj1gPt/QXXo=,tag:V55tyhUnjiGtkiiW0pySXQ==,type:str]
            client-secret: ENC[AES256_GCM,data:gl0giusxZFwRdI9d64hWXR8YURaRfKe6xiZvuExdsyMUSjxGdq390g==,iv:RcwwTj4yT7cZO2gEmFmEQ63iVD3x+m31bmDrxx/3QYc=,tag:WjZMtP3Qoo/kXyyVxeLlJQ==,type:str]
            cookie-secret: ENC[AES256_GCM,data:xM78NH1bIWhG5VIbWCkxEPoKOi8lJZTyMVDGA4iP+AU+tERgoGVkAQDk+9c=,iv:cDC6Bbf/lGvyMNMx7TCxPKux4KWgMyQdV7fPUYCeFCw=,tag:Ky7Xj1/BRzrUZqEKQUDJag==,type:str]
sops:
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUzN5NnZLSmRJWU1hZFN0
            QzlHeTN2RXgrcTI2NmRlS1R5RmZqQkpXcDBBCnVzS3dkYk1pSk5GcG1XMVlyanpP
            dEEzRU9zdUNPT2R0Uzhpa0cxOVo4aGMKLS0tIDZCTkdSNTNtbFg3U1o2SFd4dmR1
            TGUxdkdFaDNRamVCTGNDYWFnRzlibU0KSUUFnZtqHlPg0CpGFpAUW+NDmsToTFQ3
            lbp7H3kM9p4zgE/gXljxyAGFUq1N2zV5D1ZzhI+2HZoMuvEAh3OQdQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNaDlzemh0NDUrQVkvUWgx
            NHJDZzZrYTB4b2lYaVhreDdqblZVeTI5NTA0Cm9icWV4QXoxYWdEWXVvSE16cTFV
            azB2bk1LUGJiemhVeE0veDlkTWJaMkkKLS0tIExMQVpyZFFMZVB4NDlYVUh6UVN3
            b0syRlNvTkg2NlZtN2lOd3FEREJ0MVUKEgJk7jwCBEDW13poRmO72rDSNsvOYS5A
            J4urIiBpcJ++QOk5jrHqU90p4Puzr3hHX0SVQFGolgTahq5lsWg5Yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-12T19:46:13Z"
    mac: ENC[AES256_GCM,data:HYhvWJ4akN7AcLtnQuMi6Wl9k+sgWppiIs8DmTzR7/war+ap+4GX32R/BkKCVED9dbnfJY5FXYOBtlfzmqYa2tTckbb9XIFrm5GOQQoIF/hIpMT+I6Gj7unTsyWjPmfaeWKg8eFO1va1uD3dw5Quh4v/az43xWaDbeiWC5f0egI=,iv:bsJ6HZ6ROCdt3fUo5UIYfWP5cZEVgOBM3VYDrGI4mko=,tag:sje/R9Aj1QCnlkTbUV/w0A==,type:str]
    pgp:
        - created_at: "2026-07-12T20:03:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0IKwDTH3WibARAAheyI+38gMisWywSmpeagHDa6VCn7a+Nwp8+yrjOLyrHZ
            wByRLVHJUZreAkqp1R/4B2m0sCnMe9KvF3XF0VTaK3Zk4dN158hXgN3RUkkw4mH1
            rm+MrY9GAbpv1P86ROQvMKVnZHS94cKtjTamtaZIZv1B/o+O0ZUIHwJeQ8y2ojJ/
            lLoYg+6EuofZ07xLXBPhHaaRLXiy5s8iz3Nie3DQaD02rFMQeKgGcfvGD+ReRUZF
            PlAoyB8WVXe8JlLzz2x5cnehG/zE/iqLfqrh/0cUSDDm4TahYewhb+pJeO5OZVW/
            cyG6B3NpnZ22i2Mi0Z4bZjQTYxbh1bOHcta7DjLkrcY++bTMFxCnSIXqW1jDwzYN
            BjUSb/fU1RUXiKV1geO73nwZZeUooI3IkDFhVmSVNj3SMEEAO0vqA/xfzPMkBzMM
            wVA5qTl2rCYuniHmBV8YrF0GDmubI/+GvpWvNERZLnmD7WLavtd3drr+ME4B1eeq
            XoFU/1TjUuloAGlFD5axHB2Jbr6XdC0ePSk+4uVZq2t8aUgsDytkwjQuePBSCxlD
            r3lkXWNK5xibQNqt2fE7o5TAniQaMSpF0XpOWmUXoonW2kTGsu/oESce/W5bHZzC
            I8i4Ignv3LqHrQFdTx+EiR+0RdPJS7rm9ykRWxykc9hBDdMLd431z19kxop+nl/S
            XgH2kxCfk5dReNPKtVOWMEGUn+WO1nBH+UuAIKidIjfmdaJk1D4WGTsEZ+6WZgjq
            T2xGDj70k6/nhQCBpYpDZEMb4b8KqTrmxvII95gbbKuVC6oNSGXMUBU5ba8+9VQ=
            =EOe2
            -----END PGP MESSAGE-----
          fp: 03746612698994281D322B09923BC5E9B4E9509B
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
