apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: observability-secrets
    namespace: observability
spec:
    secretTemplates:
        - name: grafana-secrets
          annotations:
            reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
            reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: authentik
            reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
            reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: authentik
          stringData:
            GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:mudFlxY=,iv:GtbP9J0gx4JkEPdzckz1DXq6I6jiDbUDG14subgRACE=,tag:WEj1SAyBMRMzLfXnYB5CUg==,type:str]
            GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:ekN2/zHG6EKaVjniM8lUq24gthNl5+m/5rWMJk3IYH6JOvgoCE1HkA==,iv:3BZ3V7KLc9DyAEg4euVX3iJMcC8xaN++7JWyJUS2gas=,tag:sv5qdY6vMVvhS2UVA0W+kw==,type:str]
            GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:ujx/FEyKtQ==,iv:8MwXKSlZo93UWRjyYIOlf1K+4sT5geKZXHNK+inFsqQ=,tag:pbJGzsV09qSw2A9Bt3Z5ig==,type:str]
            GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:E/mC+rSRjFpl+f27UMlNcNxOGYS3JsLB1XeC+Yr+LxVa3RcIAfiZDQ==,iv:XBIjrDSgf7Qq/QS5M1PYofH0kN6vlPKbJ3fFjSBDhS0=,tag:d0ga9wLFK6h6D4eVVRGuYg==,type:str]
        - name: jaeger-oauth2-proxy-secrets
          annotations:
            reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
            reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: authentik
            reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
            reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: authentik
          stringData:
            client-id: ENC[AES256_GCM,data:yLaBf03r,iv:9+cpHsXoF4btMZT1HDzQzPOWo4Kh8DpuQj1gPt/QXXo=,tag:V55tyhUnjiGtkiiW0pySXQ==,type:str]
            client-secret: ENC[AES256_GCM,data:gl0giusxZFwRdI9d64hWXR8YURaRfKe6xiZvuExdsyMUSjxGdq390g==,iv:RcwwTj4yT7cZO2gEmFmEQ63iVD3x+m31bmDrxx/3QYc=,tag:WjZMtP3Qoo/kXyyVxeLlJQ==,type:str]
            cookie-secret: ENC[AES256_GCM,data:xM78NH1bIWhG5VIbWCkxEPoKOi8lJZTyMVDGA4iP+AU+tERgoGVkAQDk+9c=,iv:cDC6Bbf/lGvyMNMx7TCxPKux4KWgMyQdV7fPUYCeFCw=,tag:Ky7Xj1/BRzrUZqEKQUDJag==,type:str]
sops:
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dmF4L3FrZU52aWpQM1Fv
            cmo5TyszWGVjbTNQSHhEb0szQ0lhUjFKbFNzCjl6RHo0dmk2OE9sdnBoZ3hmdFRy
            d3ZiVTR0YkgvYm1mVStnTW9RbXhEcVkKLS0tIGs2b1lVUE92RkN0V0hYYm5YMXc4
            Z3FWaER5b0NHUk56dGlmZGJuR0I4RXcKKX9sIY0PAmh0N3eDG23xVmW4j0w1DEJ1
            +ppec3BYxPHH8mDga81igwnewzyr7I/BRpkRzucziL1zAmPBNchUBQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gzf883y8p0wfy5yjn5l3l2axnqxdgtw2zdcp8jqsrk65m7gf6y6qzgkf63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsK3VXVVVCRXJMYmhFVWdX
            ZTNaOG9VYWhqSjRySURsK2Q5VnN5RzZXajFjCjBPWWVvSS9jUUlOSDRGd3RELzgv
            REg1eE04NTc2Z1dRWDVQTzFTc0tjaXMKLS0tIDMyR1hna3Q0cWpoTG56cEF0QWd1
            NXlxREt1QlliM2x3dy9oemFoSktEQ0EKfCzSpN84NhG+UHdFetbyRP687mnw0MHk
            D60nzYmmxjDBj/JQGuNS/onG+m2AcCOLJXyPeRjDhlyBuobZk5WNVw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUzFvTEVNb24wNDJ1ZnBN
            ajNRZXRxV0tmN2Z1Y2NJWHEwelFGUHE3MUVZClU5b2ZObTEvR0V4QWFIL2NKamcx
            TlcvUU1pa1ZrNnZFYUI5L0FRVCttWWcKLS0tIGRSMUFBSkdEc2xOaWlmeVRaMFlY
            THN2aGY3SkhUQlQ3R0E1Tnd4Lzh1ZmMKoGolPljyps0O2vbHRZqGg1rgh19laijW
            RaiW4pqNYE1DPu2mtW953SqmE6frmtgx6vzG1rTM7oftTfzEymQB1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-12T19:46:13Z"
    mac: ENC[AES256_GCM,data:HYhvWJ4akN7AcLtnQuMi6Wl9k+sgWppiIs8DmTzR7/war+ap+4GX32R/BkKCVED9dbnfJY5FXYOBtlfzmqYa2tTckbb9XIFrm5GOQQoIF/hIpMT+I6Gj7unTsyWjPmfaeWKg8eFO1va1uD3dw5Quh4v/az43xWaDbeiWC5f0egI=,iv:bsJ6HZ6ROCdt3fUo5UIYfWP5cZEVgOBM3VYDrGI4mko=,tag:sje/R9Aj1QCnlkTbUV/w0A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
