apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
    namespace: observability
type: Opaque
stringData:
    GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:ZZQHlLY=,iv:jqKYH6XB71gqeVoRtp3yY7Dfy//MR7t6lrQm1OqT69E=,tag:b6btvxubVvZVJb+vX9gwTw==,type:str]
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:HQb+YPpI4PO68Q2ug8ACHpDrs+NDOdyJIVh/XACMq2DF0Qnk1RxTmA==,iv:pw32nu1qMbaW3PtbiGplppVtSiSeivM6MTkzO+5Cax8=,tag:hL6wzYvKARbTsV32VFFB5Q==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:Rz3Tp9gu4A==,iv:C+LspnZXZfGY3XdmnZBw1MMbY/6Ur+wjPxJJTrkv/ZU=,tag:90CbA6wJQZsVD5gfh/YUeQ==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:iNE4HFTAyyTy/WwqhRoF6+SulnOESsOqhyGvWrNXppcE21RW8+OrAg==,iv:PMQMRvx/5NBtQv5bzKXFXi6koXWjo057KOkmdj/uVKI=,tag:NG+HeEvFVSaBFwmbrDbBXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVHc4b01TTVRBME5RZThS
            dE9oZ200M3hha0kwbldzRnB1cmRXMU1md2tvCjhHSUVyK0trT2hTZWliUU1YaWRP
            MVBhMkNBUkdHNkRoQk5UQ3BoRE5XcjAKLS0tIHpmK1Q2NTBLYVVhT0x3WmhEbHQ1
            YittOXVTWU42elNVVmRLd1FOdm44NUEKSicv1sKpI69JWyK1jk+cQcw107I76Agf
            r4h6V41VSw8NIhrNh4iiJfsxFvrBqGRRmghqbzhUjXPswRh5l3NzbA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gzf883y8p0wfy5yjn5l3l2axnqxdgtw2zdcp8jqsrk65m7gf6y6qzgkf63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSEVKQkw2WFRjUEZZS2hr
            d0FtYmtRYWNKRnh5Nlp0UXduVFF0dHY3QnhJCmJKdmlILzhzRTBtMGdzZFBadXUv
            ajlkQkV0U0lndmdFMEdSd0JMbVRMcjQKLS0tIFBkeGdVT2toZ1RxSWZPK0taVThG
            bERad1BPQTVjU01Wb01zekxhY2FXdWsKwUoQAtGg9XtKw6zdFr3b/b8KcmJBTtx/
            Qo0EJFDhYD45OB63amwi60fhbi8gsSmscfBUsCap5jrE1jgGkskwWQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUEJsK3BnOE5IbmZzcnJz
            aUxSLzdVc0puN1U1Uk56WDlaSkpqT3A2N0VnCkErM2VPQXpjbTlSQTZ2SnJMNGV3
            TlMxSjNETjArVFE0RjJkc25TU0VORW8KLS0tIHlCWFRzeGM5M1RXNGlpTmhLZWhN
            VUpweGVnL0VCa3dkcFRPUTN4NVdtOUEKYdDCeU4+apWAWZTEuQ0d4gq7gPSqosSt
            7T1bNKc235ZNB21yUeamBV/r/G0re07c/IFzFIKfe5SG7qeCGw+FJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-03T22:48:04Z"
    mac: ENC[AES256_GCM,data:hBkJIRAeuJBcm/x7W5fzPNy/xCAxTlnzRr2M4hnfvPdhUGhC4MJ65TrD50bwU7ymg//bf/X809M8p19/N69B7ih6UOIwCJXAE9hfwsMjUwHTtPeHZ3eBMVpxdzboh+NR10+c/ET3519AGPD/7KgNFPGlrsN7Obhp4dYcpSzb6/s=,iv:Fn/anFDKg+dRwsyh4RyESCozFF1RvTSBLMLnrF4UYyo=,tag:mX716pvtL2gU5v/vAMCSoQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
---
apiVersion: v1
kind: Secret
metadata:
    name: jaeger-oauth2-proxy-secrets
    namespace: observability
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:vxIUtf3B,iv:wwLu767Q2Ij9Kj8MpPLea+i1kc53ukQLOmzMKXNM2Ag=,tag:Z5ipN8s8RIIUOuM+S3tTtw==,type:str]
    client-secret: ENC[AES256_GCM,data:ijLplvbOlIw3Tzb1LKxHps4LT0omVKI1VcxPONMaqIuL34GgWdK0bQ==,iv:SRpv+XYtUXydDMKB9HxBqj+5bQlWKqmeQ7YJBxsKisQ=,tag:lLdq9epKDq/sO+lUBJiCJQ==,type:str]
    cookie-secret: ENC[AES256_GCM,data:Q5+ZWOSvdoY4Ejvsqt9eTpLm/kkfyNNULGApvYeWb08bTF0Oc4SDwCArcYQ=,iv:A1ubNXgsN2LWUo/hGFnenlDtKd4/H479Cb3U0GKjL/s=,tag:yfrHRBL9QabNNJBV+9HIzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVHc4b01TTVRBME5RZThS
            dE9oZ200M3hha0kwbldzRnB1cmRXMU1md2tvCjhHSUVyK0trT2hTZWliUU1YaWRP
            MVBhMkNBUkdHNkRoQk5UQ3BoRE5XcjAKLS0tIHpmK1Q2NTBLYVVhT0x3WmhEbHQ1
            YittOXVTWU42elNVVmRLd1FOdm44NUEKSicv1sKpI69JWyK1jk+cQcw107I76Agf
            r4h6V41VSw8NIhrNh4iiJfsxFvrBqGRRmghqbzhUjXPswRh5l3NzbA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gzf883y8p0wfy5yjn5l3l2axnqxdgtw2zdcp8jqsrk65m7gf6y6qzgkf63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSEVKQkw2WFRjUEZZS2hr
            d0FtYmtRYWNKRnh5Nlp0UXduVFF0dHY3QnhJCmJKdmlILzhzRTBtMGdzZFBadXUv
            ajlkQkV0U0lndmdFMEdSd0JMbVRMcjQKLS0tIFBkeGdVT2toZ1RxSWZPK0taVThG
            bERad1BPQTVjU01Wb01zekxhY2FXdWsKwUoQAtGg9XtKw6zdFr3b/b8KcmJBTtx/
            Qo0EJFDhYD45OB63amwi60fhbi8gsSmscfBUsCap5jrE1jgGkskwWQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUEJsK3BnOE5IbmZzcnJz
            aUxSLzdVc0puN1U1Uk56WDlaSkpqT3A2N0VnCkErM2VPQXpjbTlSQTZ2SnJMNGV3
            TlMxSjNETjArVFE0RjJkc25TU0VORW8KLS0tIHlCWFRzeGM5M1RXNGlpTmhLZWhN
            VUpweGVnL0VCa3dkcFRPUTN4NVdtOUEKYdDCeU4+apWAWZTEuQ0d4gq7gPSqosSt
            7T1bNKc235ZNB21yUeamBV/r/G0re07c/IFzFIKfe5SG7qeCGw+FJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-03T22:48:04Z"
    mac: ENC[AES256_GCM,data:hBkJIRAeuJBcm/x7W5fzPNy/xCAxTlnzRr2M4hnfvPdhUGhC4MJ65TrD50bwU7ymg//bf/X809M8p19/N69B7ih6UOIwCJXAE9hfwsMjUwHTtPeHZ3eBMVpxdzboh+NR10+c/ET3519AGPD/7KgNFPGlrsN7Obhp4dYcpSzb6/s=,iv:Fn/anFDKg+dRwsyh4RyESCozFF1RvTSBLMLnrF4UYyo=,tag:mX716pvtL2gU5v/vAMCSoQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
