apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: kubernetes
  namespace: keycloak
  labels:
    realm: master
spec:
  realmSelector:
    matchLabels:
      realm: master
  client:
    clientId: kubernetes
    protocol: openid-connect
    standardFlowEnabled: true
    redirectUris:
      - http://localhost:8000
      - http://localhost:18000
    protocolMappers:
      - name: groups
        protocol: openid-connect
        protocolMapper: oidc-usermodel-client-role-mapper
        consentRequired: false
        config:
          "full.path": "true"
          "id.token.claim": "true"
          "access.token.claim": "true"
          "userinfo.token.claim": "true"
          "claim.name": groups
          "multivalued": "true"
          "usermodel.clientRoleMapping.clientId": kubernetes
          "usermodel.clientRoleMapping.rolePrefix": "kubernetes:"
