apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secrets.enc.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - argo-app-oauth2-proxy.yaml

images:
  - name: ghcr.io/ozencb/excalidraw-persist
    newTag: 0.18.0-persist.7
