apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - argo-app-oauth2-proxy.yaml

images:
  - name: ghcr.io/ozencb/excalidraw-persist
    newTag: 0.18.0-persist.7

generators:
  - kustomization-ksops-generator.yaml

patches:
  - patch: |-
      apiVersion: v1
      kind: Secret
      metadata:
        name: excalidraw-oauth2-proxy-secrets
        namespace: excalidraw
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "authentik"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "authentik"
