apiVersion: v1
kind: Secret
metadata:
    name: excalidraw-oauth2-proxy-secrets
    namespace: excalidraw
stringData:
    client-id: ENC[AES256_GCM,data:9tf3t74KHI2CiQ==,iv:sZLniXD4PdBbSqgvE+PTMXyjocQ78tRPRMENErC6ZfE=,tag:V52Lc/oGpD6V74UAQPcnhw==,type:str]
    client-secret: ENC[AES256_GCM,data:4VoumpcHXQWGC8Za1KsZWRueylc273/oXrt+/ZsrJGAolk9W3vWSdaOk8A8efltXvj3UWJ4qeMp5HbMpmukeEA==,iv:TTIPH0hSXIYKiWrz03JPTYz++uOCi0wUG91geiXNYgo=,tag:psw5TQm1xJ/qiRE8bULzmg==,type:str]
    cookie-secret: ENC[AES256_GCM,data:8egC+wKOWM/f3321tzJNhLnUGDHTEaPguqWCMBsiUlmgwKm2uQVYQWeRsow=,iv:VBwGDyMSBonVzh85OwFBS27wOVo+C5k7X7NNuA4zHms=,tag:V8eLYmjCijboTlmQUurXFw==,type:str]
sops:
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybEd5MlQ4SHBhYW41MC8y
            U0Z3anc0V1d3Z2M2VHVaclFjTkhBZHI3NVc0CnREQ3Z0SXdsQ3EwZ1QrY3paV0dW
            Z2wzYkhjOG9YM1R4SFgvLzFUMCtFbDgKLS0tIGt0cUJiMW5ONVBIM3hVdFZ3THZt
            a1RMKzVTUlViMGtCcFRRbjVmcjJhaUEKxeGWBGKFMZVrRZQT7S5lHSiMtGhfgJze
            nsRHNvEdHkaIK6swNwgRVvCdWhO2iI2loknOSWED61ZjnFDGGBub0A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHY25HbVdEYmNYb2ZpRXow
            cEhuWS8yeks0S3ZGanZUcUxvZ01jUk44Nmk4CmNUL3V2QXVRVWQyZjRHdkQyVG5M
            V0tWVDA5bnBBbmNiSEt1aFFDZVF4SE0KLS0tIG0xOGhTQVZTb0I1bXdKS0VnSHoy
            akJ1dzVqNWdxQnBTYVRZaEJGejhkWEkKNudyaiiTHMEFeGh2rvtbm7DOyKRrfXdx
            ONq1UNfzFfHHuboppt6+u1jHj/ge8fqNUhiBbHeZahKvM1Lwxah41g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-24T07:00:05Z"
    mac: ENC[AES256_GCM,data:S5Dqpn92IpOmhMD69D6lId3+MKzRPl+OX18908BRtnQd02SqmVfpprHtjfZ3oaO5tuvDxLcsYeu4C2I2aK+AEs+TKgbbau6Aw6PkCz1j2CGSdL5RdexBNgPGZhGxFhqrk1GuoK44tFuOpbMDiGI0n5o1RLMetb5viigB+hDRT4k=,iv:ABFYwhr5w4OmmejJOKKlBd5Fh0oDOX8/QPtPFnFs4xU=,tag:dm5k64ZbwaeH6K0J0SRhaA==,type:str]
    pgp:
        - created_at: "2026-07-24T07:00:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0IKwDTH3WibAQ//Y4L1KMStllqXcj3vOlcfEiE72hWG4Q7njIsUzFI8rtaj
            yi/sr0CA5Le/zykLKRZEQlRIJALJlJZqZ3trlbvohqQyfbvbtUz8Z9w5pwlkkUqp
            scbsaBL2wrW23s8RJyTXSvzbTI4z3hU9tKZ6P0Qog5J68ceySi734rn2S23npQk8
            oijLtku1Rpgd29b7K8H3VPnQAb18TmJtlby4nRKTc71tQ5yMcqf9rWBJ9JZpFFdH
            hRG7R/3psgPyOSo8xh75RYJIIUeTxY1HsgcVXRkojp22Nc3zkk3LO3+nUCjTe5uu
            JajQT0KoaYltQ81QWEtRKYwRPgUfNYskekYaCGgiynx4rzj9MDch7yMl2U8Opjhi
            w5egkckzTciW/i8U2LQUf+/K8vGj4PA758ugwtLQ3h3b/ekZiK9+U8FXFxg5363M
            tk57mKybABaMTHXD01XyZjf4XNKU2QRZbDM5eb2qMveZbL9UI58adeWxHTBth32I
            hrQ/aSmqPR9pHYZ8IL3ZvMGZTNj8/HjOQPQjPH1B5yoteRX16ZoQBEKgldsYZiK9
            qt8B9vjwCNIp7Nw8XQ4hCh+++hxWz1j9XTahHOOoeLxgbty7dGLHCH5TVpx29e2Q
            XNb0KDvRZvx/kWDc20CU0FnXjTEbScqZuWOPGIV22hmdUWX3rHiRPLFQT6DElYHS
            XAGBfnk9q/CF8vX681xVIxtjjj3NDThq0GHTTv6FvPuDkKZhZBJLtM4iaDyctoYe
            PTPSWdzJ/h/KaU/o3FnGkiUqqS6cR+0j5juRJyXk7xUedELJtI/Cj1VtCg7k
            =pqQ3
            -----END PGP MESSAGE-----
          fp: 03746612698994281D322B09923BC5E9B4E9509B
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
