apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: excalidraw-secrets
    namespace: excalidraw
spec:
    secretTemplates:
        - name: excalidraw-oauth2-proxy-secrets
          annotations:
            reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
            reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: authentik
            reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
            reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: authentik
          stringData:
            client-id: ENC[AES256_GCM,data:e1L+zFpCwW3+cQ==,iv:X0S9X7/BuogTZJQ5izMVkBkMCByX9N+9BzDa04FrMnY=,tag:PAHelA1IsMvwEIEuTrOcpw==,type:str]
            client-secret: ENC[AES256_GCM,data:+l89qUruHCI6ZbcICpZ5LoZOTAZWauikOO47Fba/WvAIoH3XmF4Y1+wZ2sh62QpCHH9I4drThUwyZ/bgIwe4hQ==,iv:in/UavBIxunPNP2gGzUMGX/yhF5WlIOHyzZOxVfuT2A=,tag:Elw0P3YBrw4rjdx2eQEVAQ==,type:str]
            cookie-secret: ENC[AES256_GCM,data:8NA4vNbco05+zmrustNW+k1a9+M+96VcfXjk5wHWaBAzGW9M8vSgUO2hgCA=,iv:VEZIEFZPII0AIGRpTmnpzHPYzBCC6svFgVFolY5OUMQ=,tag:KiJWBx/7i3FD9Ob22u2ipw==,type:str]
sops:
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMY01YdjRFRkxnZEgxRDFO
            eExLLyt5QmRXdTdnaHpaUjUrcFU3SWhhaUNvCldxL2VSQ3lyaUJmcFMrQm9PTkY5
            cVlvdHRXMi9RNzVvc05wV3ptb3poUGcKLS0tIFlXZnFPTlhFRmIyQXRxeWl6RHI4
            MFBHbXBvZlEwNGNpVHdhTk1UNThKK3cKwA456rzmfw4dwBRCwSewXZ5yz/0tWUf1
            qriTp3delHww4FEh54L22S3AMX6hARu9RqxFyH4MQFV18VHKsSWm6w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMFA5Tjhyb0pvUEZ0U040
            MzJXT1h1SlJWSUE0Y3NwLzIxQ2tNdENjdDJFCjExN2ZRV21RYlZ4cHY1aWFKSDZ5
            MkhQKzgycklDcmVGYW5uNlpPSjBXM1EKLS0tIHRTeVZpZmprcXo1UDJxYjZwVU5R
            QmNBSVhZTUxQOTdjUE9OY0FVMWI5ZlUK1CNaFgAZe3bpqeZSXcrhEF+Z8lbXBGz+
            0JNwSDSktZKT+YMNyoVBPlqPxoDklP961vsIb8mUUnl+T7TmPRGhhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-21T16:59:52Z"
    mac: ENC[AES256_GCM,data:4P85mNCULaoew8wnBTmNCijtSnt6dcJ4HLA/AUy71imHk1fNNiww6lhJXrVKJ5bp/f4VDuPe27iRQe/c1gEZKhqrAf4MNGxHVVxtM1pfLoxeXEy7Uvc/HHqDjCxISjzW+gZdZwoSRjKibjobDB/yV8xoLTLAvAsEZJC/HwtGkvU=,iv:u/twKM+xcu+K3eEsjTOLEOaAJ1rOJ87q6t4dhDae3cs=,tag:fCuUd9UBNm6OUlUGdBlnaw==,type:str]
    pgp:
        - created_at: "2026-08-21T16:59:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0IKwDTH3WibAQ//RQN68E96witk10KXa9cD0JEAUce0NEUTvVez4htqJL5B
            ZCfGx88B+WhX+53sqHWI8p4I8BQWEPj7sRYeIpQAgB7u5pjMogHwTmrZWaSihKQr
            3XWs12IB/4LYPPywSxiz0R7JsmRrf3zh2lyH9cXNip3RL2mxUNOKp4wVmxFszNKY
            RrzW0dryP04C+xnx27DjzSmpHaNpKXX8xZLTxuDXDpsP3MdUJEsFBtCRDfnIUmk9
            2b1wIx5UoLMMQiaQ7CUh+qpOmpytMmGjJPm1ZVVSsh1O4eLpXUi6ZPEJmtkeE624
            M2oYXSY5YGyyLVUgPc9pvEtQcPjw+Lm6pYpzLu+L/ceY3slWXLnBNEYhuThCbbGa
            tG8EfQ19UhcOf/SNDbXnPmB+QIDu0svCZ4ly3ijw1ONRjoYldz7iQWOyqpIotf4L
            L8ogDEpl5azYWn1TL12RWLrkVjePck7x+g4uUHEC7AGC/FGlAOBtwFUIwTJURU/C
            zIE59NNz1Mhsrh7+9muh3oI8usHEGYChmTctooOljl2aH5ow6mgAjKhfDv0h0pZ6
            soAxitihz2VNLbHpsPSzbuSnpTW+TSb+P/ya2FeZEddz7ZLVKo81AZgYx2bTkq0y
            CwtssgbFNzlbntejM1yv4ZBmB5eTf+DgvR+kM12ypMOiMv6yzDBxaoclt2AV3mrS
            XgGDqBhhY5QqkOtq9oN+f4RsRlZqVg8IEJF6EbVBDOJRNduNibWqqER7J1cpBUcw
            thFY+S5bwfwD8JZrYM8DjQKxUldTW2VpCpyX6LL2vp8+MP4wwvAN+lUcpl+Cc+8=
            =jpu5
            -----END PGP MESSAGE-----
          fp: 03746612698994281D322B09923BC5E9B4E9509B
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
