apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - httproute-handles.yaml
  - dnsendpoint.yaml

generators:
  - kustomization-ksops-generator.yaml
