apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: radicle

resources:
  - namespace.yaml
  - ../../base

patches:
  - path: patch-pvc.yaml
  - path: patch-node-config.yaml
  - path: patch-explorer-config.yaml
  - target:
      kind: HTTPRoute
      name: radicle
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: radicle.tibor.sh
