---
kind: pipeline
type: docker
name: default

steps:
- name: jsonnet
  image: sparkprime/jsonnet
  environment:
    CLOUDFLARE_API_TOKEN:
      from_secret: CLOUDFLARE_API_TOKEN
    PM_PASSWORD:
      from_secret: PM_PASSWORD
  commands:
    - jsonnet -m . main.jsonnet -V TERRAFORM_TOKEN -V CLOUDFLARE_API_TOKEN
    - cat main.tf.json

- name: terraform
  image: jmccann/drone-terraform:5
  actions:
    - validate
