apiVersion: "keycloak.org/v1alpha1"
kind: "KeycloakClient"
metadata:
  labels:
    client: "oauth-proxy"
    app: "keycloak"
  name: "oauth-proxy"
  namespace: "keycloak"
spec:
  client:
    clientId: "oauth-proxy"
    defaultClientScopes:
      - profil
      - email
    directAccessGrantsEnabled: true
    enabled: true
    name: "Oauth Proxy"
    protocol: "openid-connect"
    redirectUris:
      - "https://oauth.tiborpilz.dev/oauth2/callback"
    standardFlowEnabled: true
  realmSelector:
    matchLabels:
      realm: "master"
