apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pds-data
  namespace: pds
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hcloud-volumes
  resources:
    requests:
      storage: 20Gi
