apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pds-data
  namespace: pds
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 10Gi
