apiVersion: v1
kind: Secret
metadata:
    name: pds-env
    namespace: pds
type: Opaque
stringData:
    PDS_JWT_SECRET: ENC[AES256_GCM,data:vDHSkGkbbbrT8hBHjlEvFqNtcaVPybIgEfGlGHal8qQ=,iv:bUbzqtwX6/b5NSs8Dh9mWHURW1Z7GQ3P2HFJyfvvR7I=,tag:z7BZp6V9fIyiFXjcy89azQ==,type:str]
    PDS_ADMIN_PASSWORD: ENC[AES256_GCM,data:Ebl1r8+EsPlwW3ZMda8LVLdjo/TJQj/gp5C9uBDfipA=,iv:FKh44OUg72vyUw/4PkzweZM71ZWEj263In7AVVwji8o=,tag:/Up1wX/rwDCXhcHVMIZvAQ==,type:str]
    PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX: ENC[AES256_GCM,data:xfs20z62feP2hZv/JAe54cLfU99Lzu4diuB9QnF8fufIt+sTAgHpOyCfqmjlKn4C9YP0pVziHvf9fGaKSL69sg==,iv:GRbPhLSyAKnK/kVfkMt4AffKhnACQ3Ma4nLQNSfeuEw=,tag:txLBVln/u+IcyvTbw1i7oA==,type:str]
sops:
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbCtSTm1rd2VZZ0owQkdu
            MHpLZE1QL29vNll2WTFTTHBpV3FlSUp3cmxZClZrTVFYWXRqWHFUU1hxMkVDS05X
            L1dvL3d6dndETGRjVmpySWZXMHp5eVEKLS0tIGtvWDRrbkJWTGVjcHA5WHdYczVO
            aDV3dndKd3ZJcEZKYXFtKzkyYVZ1Q28KgQCoSeTbw8Ds5IFKtTtTKvCZcyOTxGf7
            oWWhwYnQu2hOKC7RSzKL520DiXaoTs69CnE5ZmURfuv6KAfERsGEUA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gzf883y8p0wfy5yjn5l3l2axnqxdgtw2zdcp8jqsrk65m7gf6y6qzgkf63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWnVtYXMrZnR1OG1OOUNS
            VEhLWlNGV2QzeTVyck1jaHROMGtZSUZPN1Y4CnVKaWNQNThzREptdTM5NUNXTDlW
            ZWdqMk5IMjRCRGY0d2RJTUY0eTRrSmsKLS0tIGZsYWV6SFpCUVM0eEt1bURSVk9m
            YnJXUGNlbGhRNXdqUlk1aENaV1cvSHMKVXNAKXd/xJyMi2IDkbQpteH8zyp+h7Uf
            wOu3IvycSrybeBmmFofZw3tU+99WbK9Iq98DMJf0wx3NBMTuXe6pFA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZG90MXRuajdkRzBwajhn
            S2hjZC9TV2tXdmJHcGdESlZodktjczFxZWtJCnMzYXhyZjdvWnMyYlJhQ0FBSGdl
            YjJvSG5uVDNKbWx3OE03SDBWYkY5WjQKLS0tIHdxVXpRa3BFb3p2elREbjBuRHJV
            ZURQNWExZ1NsK1AyNklDRjNaTlArNEkKAOGUnH7195Oyemg7ZVnszdzUpHHOfgWv
            S5NFOZZlfMtf3c7iCVnGvivMbcFUSTLjzrOlUzr7jZG9G/045oDxsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-24T15:44:21Z"
    mac: ENC[AES256_GCM,data:/vtJW7MjMuEkObqbHkmpGi1JGhXVUCdTdZ9aLr5RT3CIpDsmTtgjyx3qrNAP5mph1XZAxc86CHLVQ5gCmur4ZLN3sTiphEtTyK5pZ7U7rIDZkzU+pvqRVQkpKdvro7oRizIXGU2LCYBRRbDDKvkYAQEvgD/nPqMYPnQFUYTYrM8=,iv:WOZ2QfHXS3e2LP9OGMQkEuN7NijgT7WEFoPEnilHTxw=,tag:wDR8hl2WgPR+5Nl5obSR3Q==,type:str]
    pgp:
        - created_at: "2026-06-24T15:44:21Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0IKwDTH3WibAQ/+O9jtkUCJJVrbwEUFDei8mp14qSB/HmePb4B3BIMoXCdx
            rM6TdKLRuTA1X7nkFnvlek+lm3RXtITkf0IJLrDpn164pFjGTOivs28W17WU429c
            PW33fYY8TLNGIbp1kaU5OEcTsmBt/ELZxicPg/hbNOvLBi5BGcqEZCXULCqAiUuU
            04qtBQ5AvTMxmONgy/pwnkoCW+ofPDxouLYHIaaUhuRG5lOBkc02DMyjBaBTRqCM
            zd+7JT8ZnCIEwMjSByE34jMXluNUipL1/0rdNcrJ6re8KHeGYI8CMUWWKCsGvFTd
            yDkY064pGqmcLzmNCMUoGhh0C7bFCw2dZ6aLfyyTN2K+rQCEQLPB0d+ICZzWmO+p
            7X6fujJZexXQkafLKfyyELbZU+pUin97AJiy5yzvwub0DHKwVRM1p9mZz57kXVQ9
            k7N9UPd/o0yEygMJcICotZUpUe3R6weyP/DEdbmZm4ZXugkD5wkZ5GRuuDJUYBQl
            8N1EqbJCNQjODhnIcRDqF0rLA6zQCt7ccpRK61u20UfWP/7KMT2i+uVnEcg2qGU6
            KXjcCmTDf/ouj2+n3MzfftR04a1i5J+GXcfn+wF2gRo58gSMHSLiGLfua1VublU5
            q3Nq9Bt3yWPt+jpcXFRKeg0//AhhCQGIsVt8Gt2Fq+KdKG+New6ctTUnKKsqeE/S
            XgEdCLayUQu2gCcsbal2+Y86XkdzGgYs4pJceERR3cLoCqUjt5xshg3n4GTDJVhJ
            p0ATR+bSI61CiIF0WuOpxXrQWyqH0N7k3EEU1mMhfviAnpgMRhgPud/md2coryI=
            =iG63
            -----END PGP MESSAGE-----
          fp: 03746612698994281D322B09923BC5E9B4E9509B
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
