apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: pds-secrets
    namespace: pds
spec:
    secretTemplates:
        - name: pds-env
          stringData:
            PDS_JWT_SECRET: ENC[AES256_GCM,data:7SIDUy87GKq6vuHlatGosYmi+v4VRuK1USgGWxdy+C8=,iv:Wf2cbDvaJa0ieOZmOA71FzCrlAxBMWBK1rbUG5aHQZc=,tag:yaLhQfJCrf5xTvq2kt6C9A==,type:str]
            PDS_ADMIN_PASSWORD: ENC[AES256_GCM,data:9ZiOCW5nW4ZxHxYY6ZGOXC8XcLaMUC/Tzb2f2pStut8=,iv:oYa1rqJnhJGNtFMTsqt5tdsR55J8/TxyR32Wh4RvTrQ=,tag:IzchgX5+O/l5EzmLx4rUjw==,type:str]
            PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX: ENC[AES256_GCM,data:uD8yNULH4m9chP1eDXaDySTh/DSafsO3fOJG22LLPFrqvcD59PVLVtGh71/dmxig5LXD976PtFfy2alVya5oIA==,iv:cA3pHp4+vB2j66Y+ccywpsmvFDUAW86HopKXsXG8J14=,tag:wIFm4h2mXiQRNDFWwMLmeA==,type:str]
sops:
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwN2pXWE1FSlowVHVJYlZT
            aTREVk51cm5WcUJETlptaExVelNaWnU1ejA4CmlTTzZRa0crOUdLWHZVbVRIYjFR
            cWtRczhKZ3JXS2w5andUbUkrMXFOOTAKLS0tICsvaXhaVC9WeVpobDY5a2pteG83
            dU5YaHcvQUsyc3gwbjBmbEgySmR6NTgKL+JtWn4Jrf68AUbjla++vxlythvdk/in
            +aw/KDYTTgGqPpUQ6H5xWOG2qV6ZM2Un09ALyOvk50lWAzU1E/VRog==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzajl0bUpqZnZac2xXMWZL
            dnYvcTQ5RmxVVVpQWnFETHRLbElXTmsxa3dVCk83ZTVwMUY1WnlxK1czYWpMWERi
            T1FZQWx0R0ZsZ0hlbVRldTBhWjdlSE0KLS0tIFIrZHdiMEFOUmxpVXh2RGp4N2lL
            RzkwQ3JPeU5UY0owVVVtWFBvME4xQm8KPrSxYuJQkxg7Xh7c5QuP7dpOIc4OvMPl
            oBdXC2023DL641S9ZixWbr99CUdirp0wzBYSpY1y2kgmUzPFWU0DTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-21T16:59:52Z"
    mac: ENC[AES256_GCM,data:TL5KsFzZSj/jL8foBylb2D4HXyIK65fWqbo6I0DzUjCe/7Vf7NKvKxbqtZ4wTxqFgzNS6A0IsCMuuJPJbQO9n9XKC6o5320M9mMPYiFvUGTKTOtlVExHuuRxotmkSwAnqLEgNQRVmAHDCj0KG9SKfCb2b0Jz/88uwr3VWWPuXKs=,iv:6npPrJiIYkUe7+RiMJ5W0AdqQTNdW/SgZyjZiFhsUHk=,tag:z0X3Pj77CCUXdAEzHNJWQg==,type:str]
    pgp:
        - created_at: "2026-08-21T16:59:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0IKwDTH3WibAQ/+KuIQJjFd/Bb65tuVJYb70cjFQU4Qm80wP3DIpQQxcjaV
            NqBqQbXqA9lkPIE7u8Foi7M3uOd4/t/mnNoak28DWvkOQThWiRzd3MGfbU9oFIaX
            fx/ilEt67FvWQhR5hVHAqfeAVrkYuofBhX/4tpeSxaBTX3rJozetwGnOm2S109+G
            s2V1srlVLNGysB9lTz2yxW9nO7EX/8e0PlZQesqg/zl9EqdEALAbW+WO+Z/pNSY+
            yrj6M8dUm9UuWY+2CBw05ptVykZ9dS4vhla4ydaxRdT/s/gqrKijYmvamQNSnYt3
            wlcQk3NPal+bKm0vhoXC8mEa351CZ4ZppnnmbkABsIveAHoEkbfhltKRm5fs5+gp
            VI3qafMUFxLjZVrY00HwSlNIUSL1gmDMZUBPu2n/geO1Moi4kzEsbWKquoDnKubV
            +ShYU8bBzx1B21ISoUwJwGlvEzZpuAurwtFUQUfYop+AgH7wtaY7/jyAI+obkkCB
            KTA42smMjFkIXFvDirTEUYZYe8n42vFuJozJ2z8QEQizqu+5D7u4UvK4RKZv5oZ5
            8P8uR2o1XVSsowoy7koFNn9MJ/Cg3OcnQWlercjJux3kA0pkX05Dwgca0tmCercr
            XFa3DjryQZDCZtZGU9gcMYTe8WEvl4hCbP5pAQH1MysUY78HQZk1P12hoeVPwAHS
            XAEfFOXQyS9GfeBwr/i/Um/2S/pziH8rSNhhvnt/IdVId3kwb4gw2X3yIS5j8d2O
            t62y7T3deW2Lpk0kqHc7ooxf7fWXmJTjBAXUknBUF27zICquwqSw7noznzi1
            =mD8T
            -----END PGP MESSAGE-----
          fp: 03746612698994281D322B09923BC5E9B4E9509B
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
