apiVersion: v1
kind: Secret
metadata:
    name: pds-env
    namespace: pds
type: Opaque
stringData:
    PDS_JWT_SECRET: ENC[AES256_GCM,data:vDHSkGkbbbrT8hBHjlEvFqNtcaVPybIgEfGlGHal8qQ=,iv:bUbzqtwX6/b5NSs8Dh9mWHURW1Z7GQ3P2HFJyfvvR7I=,tag:z7BZp6V9fIyiFXjcy89azQ==,type:str]
    PDS_ADMIN_PASSWORD: ENC[AES256_GCM,data:Ebl1r8+EsPlwW3ZMda8LVLdjo/TJQj/gp5C9uBDfipA=,iv:FKh44OUg72vyUw/4PkzweZM71ZWEj263In7AVVwji8o=,tag:/Up1wX/rwDCXhcHVMIZvAQ==,type:str]
    PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX: ENC[AES256_GCM,data:xfs20z62feP2hZv/JAe54cLfU99Lzu4diuB9QnF8fufIt+sTAgHpOyCfqmjlKn4C9YP0pVziHvf9fGaKSL69sg==,iv:GRbPhLSyAKnK/kVfkMt4AffKhnACQ3Ma4nLQNSfeuEw=,tag:txLBVln/u+IcyvTbw1i7oA==,type:str]
sops:
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhNGpJMWNiSHFOSW1mSnV0
            M0JjVFQvaVVwd3RuK2R4SGp5aXE1bXJJTVdRClB0WjZIaE1wUjhaaXYwbU9FbGVM
            UGdZRnByR1RtS3dKWFdUUEFyNDVvOTAKLS0tIDBqWG5ySnlxNmo0dy9aNTVNckRz
            c2hnR1FjeFlpNEw2aGhNbnRia3I5bmcKQCpkmV60eulMd0t7LLvyVKkLsTcIG3Yv
            wqZ9ofqNkr2E8AMvkPf1yz7WpAnxkj93HVwkk4K1TQKLXFKBL4KYtg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZ3JHL2U2eUNWR2VGK0xG
            dU1KR0M4M0RrOEgrS2twQktqWVFMVVorcGtnCjA3OVNxYkRveEFyT2c1TzFRZ3JL
            TXhGS2p3NWkxMWZQSWdFZ1Rqak1pdlkKLS0tIDJ3SkhwMVdRQUZ4TE1lc3Qxamty
            NjdGK2JTa2xSTzhMb3FlS0o3RWtjN1kKOby1eJMZReTviivoMaTtnEvrFhBgbAeh
            vBalSNBLIv9JJqtvlE/7T4E1rBZpkjT1xYDEd5tge2NWVk33a65vmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-24T15:44:21Z"
    mac: ENC[AES256_GCM,data:/vtJW7MjMuEkObqbHkmpGi1JGhXVUCdTdZ9aLr5RT3CIpDsmTtgjyx3qrNAP5mph1XZAxc86CHLVQ5gCmur4ZLN3sTiphEtTyK5pZ7U7rIDZkzU+pvqRVQkpKdvro7oRizIXGU2LCYBRRbDDKvkYAQEvgD/nPqMYPnQFUYTYrM8=,iv:WOZ2QfHXS3e2LP9OGMQkEuN7NijgT7WEFoPEnilHTxw=,tag:wDR8hl2WgPR+5Nl5obSR3Q==,type:str]
    pgp:
        - created_at: "2026-07-12T20:03:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0IKwDTH3WibAQ//cryX7NwDlE9xttvLQbx5iK0amol2Gupyj9B0e59YZXW9
            GmGInq1D0K5DGjLdXt4AoOuhY3SWh5wz5Wj5YvC7pdfuc7pAmMm7j3Qdn0yEMODw
            TKFDG35IbFMOUEHiH9hLtvzSmSlKzK5nNi25nUQ5Fa/F38saEKEBZbARylx+GKTE
            abux+sTTaFEbBKEire78AfyGxwBsobONNw+4WZWsohtgkRs1LV4wogr8b6kRt2K+
            CF5ZLISvzExyxoUto88wnOC8+e3/BCf2IO8OTGdZuv+1xfc/pScfB6ERjylobTO9
            9xkxRfvl3ii7tGLfrYU63Y0/TRHrqsA3RxPMWn5RX3MSXqQNe9rG6pyl+MFBOXVf
            5rB3X9/rJUTTnuoU9rDvYWeWaJRv09j2GunVK79dJbAQYNDx9CdlLYJWcFvVFpZy
            iPgtbomfDpIdVU6C6RKzV81vNwdTCcY6qlUhQbSpR24Eo5NSHWnfpM+MOJ4RfHhF
            mD0DrRi/NNQcAEmVHUyGGgnygwL0cCclqP/xv/V9pFCp1AAoDy8mfWpklBtxb1Aq
            7lSMDfR/HO8YH0lskWFEg9OWmZJFzCNJQKubTFRDIq4yt79VQRetLdYdUNVdfnXP
            YdEFSxmbtAvdJAZ4MrERFD0jWWSl4d3MTLSNCsCBJdfBJgVItuFh396h8Hh/40nS
            XgFI3JV2EkbyduyjJoXOH/330FimEBixoMmWZIrSbAS7o+krQtPprJgZCuec8okg
            gxAXzAK8mInJcqj/tDp4sdkxobcKpZjjVcUcLTeIXzLpird+a5Pb+LmWTdUBktI=
            =c3q+
            -----END PGP MESSAGE-----
          fp: 03746612698994281D322B09923BC5E9B4E9509B
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
