apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: snapshot-controller
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://piraeus.io/helm-charts/
    chart: snapshot-controller
    targetRevision: 5.2.0
    helm:
      valuesObject:
        installCRDs: true

        controller:
          replicaCount: 1

        webhook:
          enabled: false

        volumeSnapshotClasses:
          - name: ceph-block
            driver: rook-ceph.rbd.csi.ceph.com
            deletionPolicy: Delete
            parameters:
              clusterID: rook-ceph
              csi.storage.k8s.io/snapshotter-secret-name: rook-csi-rbd-provisioner
              csi.storage.k8s.io/snapshotter-secret-namespace: rook-ceph
          - name: ceph-filesystem
            driver: rook-ceph.cephfs.csi.ceph.com
            deletionPolicy: Delete
            parameters:
              clusterID: rook-ceph
              csi.storage.k8s.io/snapshotter-secret-name: rook-csi-cephfs-provisioner
              csi.storage.k8s.io/snapshotter-secret-namespace: rook-ceph
  destination:
    server: https://kubernetes.default.svc
    namespace: snapshot-controller
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
