apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scope
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: 
    server: ''
  source:
    path: 'applications/manifests/weave-scope'
    repoURL: 'git@github.com:tiborpilz/infrastructure.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
