apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/tiborpilz/infrastucture.git
    path: applications/forgejo
  destination:
    namespace: forgejo
    server: 'https://kubernetes.default.svc'
