apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: forgejo
    version: 1.0.2
    repo: oci://codeberg.org/forgejo-contrib/forgejo
    includeCRDs: true
    valuesInline:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: letsencrypt-clusterissuer
        hosts:
          - host: git.tbr.gg
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - git.tbr.gg
            secretName: forgejo-tls

      gitea:
        admin:
          username: admin
          password: admin

        metrics:
          enabled: false
          serviceMonitor:
            enabled: false
              # prometheus-release: prometheus
              # TODO: add prometheus and enable this
        oauth: [] # TODO: find a way to create oauth clients during TF apply that can then be used by other apps
