apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: forgejo

configMapGenerator:
  - name: forgejo-config
    literals:
      - domain=tibor.sh

resources:
  - namespace.yaml
  - secrets.yaml
  - database.yaml
  - argo-app.yaml

vars:
  - name: DOMAIN
    objref:
      kind: ConfigMap
      name: forgejo-config
      apiVersion: v1
    fieldref:
      fieldpath: data.domain
  - name: FORGEJO_HOSTNAME
    objref:
      kind: ConfigMap
      name: forgejo-config
      apiVersion: v1
    fieldref:
      fieldpath: data.domain
