apiVersion: ENC[AES256_GCM,data:T7M=,iv:dIRHBfOplzrJ7UbuANG8xm5v5DcCi/jbhBfAtwD3Dtc=,tag:LOJhvb42ZoAs+sMMMjkOVw==,type:str]
kind: ENC[AES256_GCM,data:Vw7itc9U,iv:F8NBsxkeqBecT09aR6H4ZFVB5VAxsqWC3xEcWcvnHx8=,tag:BUsg/aPAQ1UkiSiE6XzMpA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:A6wiZ/5dauoOdl9X5g==,iv:JAeDRLxmT9xE/XwyvZDC/Swzd1clgfB4RpAoc9uabzQ=,tag:iBnP4KeAq2pe19scLit0Dg==,type:str]
    namespace: ENC[AES256_GCM,data:o3kwBglabA==,iv:6ibUtrsjdggruD3TZq7bVOCxGXO6BCqKyZuehVPpIDw=,tag:4zIYEDTTjgoGje0kRYdO7A==,type:str]
type: ENC[AES256_GCM,data:56cuYWy+,iv:QjavvJR284qso0g63XyKhn34DygjjGFLJSsg9MqgesA=,tag:ycjdBlYTPEFyoT4yifU+iA==,type:str]
data:
    #ENC[AES256_GCM,data:H45z23lkwpLNmt+a5BA=,iv:aaoNYYpyV2dtOSjPnotI4HrnmPNHlLap2bd5BxJwcss=,tag:0v04DuLa/IYz+PW9XgaWNQ==,type:comment]
    username: ENC[AES256_GCM,data:b1Wgi2ZPsQX3YHS/fcfKdsXWeeY=,iv:YQiEd9YDznibrTFLMqUyu00BarrJ7G0zUA0moutNuBw=,tag:zK8qrP63oaWr7gL90nu98A==,type:str]
    #ENC[AES256_GCM,data:DrX/U7zB+jlhuPcYbveMfG7C49UigAu6s8sIoTzilgMTkg+T5O5tjN+f7Go5,iv:NNqSgT/XFFFoRt85hYLkX9XqF+7h5/+JWAOj1ICr5g0=,tag:kQnGaDkMeU0UE55TaH9xfg==,type:comment]
    password: ENC[AES256_GCM,data:EAk2iPWdeWOHvzvwvV9KenUx6ijfac08zNJpEUn5VRCxGW/bZ4SLcgNS4IRL5tQFjUF/6hDDeJSEsdk7,iv:SWm/p4eS5D3M4FustvCMihGbqZ68LqkrLD/m5naT0z0=,tag:8CAnYQYMpJCjeIHmQtBW6A==,type:str]
sops:
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBL21NKzRsUzE4bWxSMzZE
            SkZIb05NNGVOWGVVSFhjYU1RWERWRFhPUUJvClR6ZHFVTy9HSFdKWmpIV2pPTkFl
            VjFQRG9yWVcwQnR6blFZQlB0WnFwYWsKLS0tIGRXbUo1REFsWW1nbmpsNUdJM0dk
            b0RaMmd2NlU1L1RiaEd3cTZJSmdvWTgKZQp10QsOuD3gl4uYichBmRGGghxeq7pD
            Rztzcu7tnNnu+ej8H/qeypCMID+bpNMMqaVQ1SlWIDlStpBkcOaDEw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gzf883y8p0wfy5yjn5l3l2axnqxdgtw2zdcp8jqsrk65m7gf6y6qzgkf63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTFQ0NkVadkpnNGxUNzl2
            R1pEYVJReHUvVDlBZW1PWlh0OG0rczFFenhFClR1NXNJME5MMVZyWGlHSS81VmNF
            VG9oL0dYUXNkVzhlK05iR29tYnBuRjgKLS0tIGc5c1hOMVMyc0kxMDRyQUdhRVBv
            ait3TFpLOExQOWsva0RZWUhuMFIrSWcKi/OcTKPFPBlJpvV7LrQXUHelQntecLRB
            8CaFcOIvTQk8BuhpLydj1NuMXtL6XJucP8QIrEr53srqSMz/lYJH5A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKdXlYZDkwMnNBdVc3a2xs
            VHNVWUptQlQwVG5PTVdGNHpleFA1WDZUMFdRCllmcUNDZTFMVmxQTWkzeWdGWDNZ
            MFZNeVlYSkNzQ1drQXNZMHRxL2hIVlkKLS0tIElQY00rQWJvR3ZINVpVRkErNUVP
            NmkxcWRRR3lhQWJTUzJlQkdvZW9jb3MKEqpyGNqVZXqRR95JC5u9LKB0ZK1V28qC
            FSCuZnoXjWkF2wLPo4G62a5Z4qfpR0pxZ8p+SZOKt5azFmHb6jmR7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-13T14:14:39Z"
    mac: ENC[AES256_GCM,data:u/nu6ywySaGln2B6bYgGa7Buj7AQ7vlbRypRC6aRIYre0HEkE845vGVGCcLKcxwpFvJBgmbOMQxkrRwxlQzhnXxRi21PyWwWMb7yJKooetFOh6gjexk9zXl+eZYtY+BDpYJAIu9ZhEhz/nadnGMfixMIIATLzegcFNMBfJ1dwOo=,iv:hULXmx49F4AaiJPhkKcF1cvipcAbbQwvsyOvck6w858=,tag:VW1AL9Y505wRU0AEQIOKFg==,type:str]
    pgp:
        - created_at: "2026-06-13T14:14:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0IKwDTH3WibARAAhAG5HhobcaRW6Qj+KrSy3D+9VcCm8y3Hb71gxzRCQjUQ
            Shh3q++zQMZDKQR+aTy82V/elE/hvsuJjm4zAFpL0zwIcAXaXgRo/vZy8QTm07sA
            Ei8afGwqa3KApD9KTt5FWeZfoFlj8VW6sNUGM9tbgXUKdT25HUAS7U05wPm/rCzU
            LCQOwl8ngvKcHflGCI1nKyHhzppQmbBU0N112IFK8w9BJV1HQt66o0AkmAwZrT5t
            GFecpFzUjD5VofV4By2rsYoMeLp+xZyPcI+1wbDXPUoXd+p4hsm85BK40Y5DTzGz
            /K5msRMF0IeK4WqsSleGqMGaG0ZdcUspjKeQPiCCPV6VV1EZlwIIqRtPeGT8Eomw
            Siguzj3/g0a+8kL17GtPBb6okWEhK142E2vEgneb3FUgpCZWumb3BXei1zTNuOUZ
            IUDemdtI/9sEy+4OemHZVzwUYdk7OblWqmdHZV76rJcFydJuJGRY+Adms9dAYoTZ
            Wa//SukVBDmRLlsEI0Bmk0qNept6NHB5M5BX4phvCCFUeZOs2RQ/9M1bxJowKEEC
            9PTeAAj8Rs7sz5uwluvA7Vu83kebozG3YTDQ9HymIvsQWducWqru5xlsLiAvq5iP
            39mhKInSB0mGvFWRuFu/4gLBtTv9qdz2yTmmptEuYgCi79AfLvHvK1m67Q4FhKXS
            XAGPxrG0sQxKsYCBSKVDgSNvGvx4+L8a97HtflJc2Kn1YpjFcf0Fy2bUSIWEm4wa
            4Dli+onzbjp33G3WiCwInuIOQxyBbngI0z2hrsIY/DyyBK5TbnPZKDWJTmcJ
            =6F6e
            -----END PGP MESSAGE-----
          fp: 03746612698994281D322B09923BC5E9B4E9509B
    unencrypted_suffix: _unencrypted
    version: 3.12.2
---
apiVersion: ENC[AES256_GCM,data:MdE=,iv:g4IqEJ1HYcxprW4zzUwNBhDu5mAA6zrA4PsmBGMK9oQ=,tag:cAdo5PL6WcU5xpwdWrY2lQ==,type:str]
kind: ENC[AES256_GCM,data:xzTp9iXd,iv:RBQSuG9/HDheQLkzh2QTQW8bFXATcqVzBxCybsF1VYg=,tag:Y/QuFaAzKsMuP7x2CdCXag==,type:str]
metadata:
    name: ENC[AES256_GCM,data:t4RLYfoUwa25x3AD,iv:QJotB2zKmqk250k2FLxfE7Q48kxITzCUkKf48JHS1Lo=,tag:4MPTpnyWiYMNHldZvH6WOQ==,type:str]
    namespace: ENC[AES256_GCM,data:Go6DLSfszA==,iv:d6KTSybX0g9b79f7YYP/QA2jwcrjxK5/CQK03nP53Bg=,tag:dr+FS+Tanglfwoxg4594Iw==,type:str]
type: ENC[AES256_GCM,data:MIcaMxAg,iv:Bk4jmeBGuLHvXgRhyzMV6COSpVo6PeirQsG900s1x1I=,tag:TB4qOH6E8ttWyWz/c+VTeg==,type:str]
data:
    #ENC[AES256_GCM,data:pP50Nb8sBQ0=,iv:aIDj3czjJPE9KejvK2/TsosL+78LlX5zY87SjFA9qPU=,tag:wN/L/phappriYHqfYskZDA==,type:comment]
    key: ENC[AES256_GCM,data:eBWrr3mx+2q6zI2/,iv:Bad8Gjxe5i3Lr/T9qbxORdbEW9EhUnr//mG7zOz5e9w=,tag:hzdok8dfJYtYJN380CxE+A==,type:str]
    #ENC[AES256_GCM,data:UZ/Nxxf7BM5KVDpQzBfFEKJaz19YU94k30I2KV4RL1waoxJ5DWbn+ulO3F1m7acA09Pd74tnQGzLUhzQJiCU+Xo=,iv:Q07/dyO8K/3qhcpBZY6BobcMvqDPLJywoDlNREQ7luY=,tag:1vkbR3lp4D+R+8+rcSVOWA==,type:comment]
    secret: ENC[AES256_GCM,data:Az816TB/844awWpM87ZuaQngrYMkP1KalmJLVqwNdEORz2hmcu0OatutgyOhQGU8icc6GuSsugd8SK65XccAYl5ZfHBdMo23fa3+u3Ftfdyt7Gn4ncnfjA==,iv:njytGZnTt8iltBVnow3lBezc5QzEyBgna1gzGcKF6LM=,tag:LQqA+H3rdsaBkJbSyJUJaA==,type:str]
sops:
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBL21NKzRsUzE4bWxSMzZE
            SkZIb05NNGVOWGVVSFhjYU1RWERWRFhPUUJvClR6ZHFVTy9HSFdKWmpIV2pPTkFl
            VjFQRG9yWVcwQnR6blFZQlB0WnFwYWsKLS0tIGRXbUo1REFsWW1nbmpsNUdJM0dk
            b0RaMmd2NlU1L1RiaEd3cTZJSmdvWTgKZQp10QsOuD3gl4uYichBmRGGghxeq7pD
            Rztzcu7tnNnu+ej8H/qeypCMID+bpNMMqaVQ1SlWIDlStpBkcOaDEw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gzf883y8p0wfy5yjn5l3l2axnqxdgtw2zdcp8jqsrk65m7gf6y6qzgkf63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTFQ0NkVadkpnNGxUNzl2
            R1pEYVJReHUvVDlBZW1PWlh0OG0rczFFenhFClR1NXNJME5MMVZyWGlHSS81VmNF
            VG9oL0dYUXNkVzhlK05iR29tYnBuRjgKLS0tIGc5c1hOMVMyc0kxMDRyQUdhRVBv
            ait3TFpLOExQOWsva0RZWUhuMFIrSWcKi/OcTKPFPBlJpvV7LrQXUHelQntecLRB
            8CaFcOIvTQk8BuhpLydj1NuMXtL6XJucP8QIrEr53srqSMz/lYJH5A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKdXlYZDkwMnNBdVc3a2xs
            VHNVWUptQlQwVG5PTVdGNHpleFA1WDZUMFdRCllmcUNDZTFMVmxQTWkzeWdGWDNZ
            MFZNeVlYSkNzQ1drQXNZMHRxL2hIVlkKLS0tIElQY00rQWJvR3ZINVpVRkErNUVP
            NmkxcWRRR3lhQWJTUzJlQkdvZW9jb3MKEqpyGNqVZXqRR95JC5u9LKB0ZK1V28qC
            FSCuZnoXjWkF2wLPo4G62a5Z4qfpR0pxZ8p+SZOKt5azFmHb6jmR7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-13T14:14:39Z"
    mac: ENC[AES256_GCM,data:u/nu6ywySaGln2B6bYgGa7Buj7AQ7vlbRypRC6aRIYre0HEkE845vGVGCcLKcxwpFvJBgmbOMQxkrRwxlQzhnXxRi21PyWwWMb7yJKooetFOh6gjexk9zXl+eZYtY+BDpYJAIu9ZhEhz/nadnGMfixMIIATLzegcFNMBfJ1dwOo=,iv:hULXmx49F4AaiJPhkKcF1cvipcAbbQwvsyOvck6w858=,tag:VW1AL9Y505wRU0AEQIOKFg==,type:str]
    pgp:
        - created_at: "2026-06-13T14:14:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0IKwDTH3WibARAAhAG5HhobcaRW6Qj+KrSy3D+9VcCm8y3Hb71gxzRCQjUQ
            Shh3q++zQMZDKQR+aTy82V/elE/hvsuJjm4zAFpL0zwIcAXaXgRo/vZy8QTm07sA
            Ei8afGwqa3KApD9KTt5FWeZfoFlj8VW6sNUGM9tbgXUKdT25HUAS7U05wPm/rCzU
            LCQOwl8ngvKcHflGCI1nKyHhzppQmbBU0N112IFK8w9BJV1HQt66o0AkmAwZrT5t
            GFecpFzUjD5VofV4By2rsYoMeLp+xZyPcI+1wbDXPUoXd+p4hsm85BK40Y5DTzGz
            /K5msRMF0IeK4WqsSleGqMGaG0ZdcUspjKeQPiCCPV6VV1EZlwIIqRtPeGT8Eomw
            Siguzj3/g0a+8kL17GtPBb6okWEhK142E2vEgneb3FUgpCZWumb3BXei1zTNuOUZ
            IUDemdtI/9sEy+4OemHZVzwUYdk7OblWqmdHZV76rJcFydJuJGRY+Adms9dAYoTZ
            Wa//SukVBDmRLlsEI0Bmk0qNept6NHB5M5BX4phvCCFUeZOs2RQ/9M1bxJowKEEC
            9PTeAAj8Rs7sz5uwluvA7Vu83kebozG3YTDQ9HymIvsQWducWqru5xlsLiAvq5iP
            39mhKInSB0mGvFWRuFu/4gLBtTv9qdz2yTmmptEuYgCi79AfLvHvK1m67Q4FhKXS
            XAGPxrG0sQxKsYCBSKVDgSNvGvx4+L8a97HtflJc2Kn1YpjFcf0Fy2bUSIWEm4wa
            4Dli+onzbjp33G3WiCwInuIOQxyBbngI0z2hrsIY/DyyBK5TbnPZKDWJTmcJ
            =6F6e
            -----END PGP MESSAGE-----
          fp: 03746612698994281D322B09923BC5E9B4E9509B
    unencrypted_suffix: _unencrypted
    version: 3.12.2
