apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: forgejo-secrets
    namespace: forgejo
spec:
    secretTemplates:
        - name: forgejo-admin
          stringData:
            username: ENC[AES256_GCM,data:Eky7FRJUTkGtHoZLcQ==,iv:yqW6pwLiMSr7D4LOs6rdtHYNXCkvjOtm2eVhC4Pmy9g=,tag:tJLhDNS1OdFrhiukJTi5ZQ==,type:str]
            password: ENC[AES256_GCM,data:nMLd+8A9gh/Zug6imDm3J8ukeYNgNaI/Hmk0jyyzRmmmKP1jr4r/MsEvhJQ=,iv:TYeIqsvZz7yjsy/pczDYWRdGYD8KSQ0gFNJ8PtLMAUU=,tag:d1wn7aEDeuNRywmm6aMsdA==,type:str]
        - name: forgejo-oidc
          stringData:
            key: ENC[AES256_GCM,data:kPOJHxNYRg==,iv:u5B4QqcotIPSved7NdCJWRzYU6mz199gKK0JV4EZad0=,tag:9RtDroK7AYsj3b5savVaEQ==,type:str]
            secret: ENC[AES256_GCM,data:KWTUl0ah2x8kzgCqJZ1lmXrEfcJuDtzrO61I1IFg6Azsb7a8266p5uQCjUQAptYLFb6QK/IcddPY1v+eSJr8Gg==,iv:vsAq9C4muTXZgDR2Y7OKy2tzCgj2eZfM7ZmrVJc7rIs=,tag:E3FoI6OkAlvPdSbDMRkUiw==,type:str]
sops:
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlTk9oR29GMUdjM05zK0li
            UW0wWFZwdGRka041OGJtQVZYaWc0azhJMFNJCnpYR0pMakNsVUwzdVZXY2JYMDlI
            ZzdoOE9EcTlETjRBcnU4MDlpTGNOTjAKLS0tIHVWRllFOWhSRVVGUVVPTWJKS1dQ
            UGY0c1ZRazg3dXZVT2hoWVRWRUxLQncKwOXvMmTekS1oEewHXT0QS3pSYdWJE5QA
            8KjdE+t5WzVMSMMh7KRAxMfd9ZFGnkcHjHdmzFDIPtH6kCtsuz1fzw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gzf883y8p0wfy5yjn5l3l2axnqxdgtw2zdcp8jqsrk65m7gf6y6qzgkf63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUEEvRWVaVnhGcFlST3Nm
            WkIvcmZvS1JFOWtFb3BtM005T2Rsc2lKMVNrCndqc3Jwdi8xWUNiZXIzSk5lUjE4
            QjJjZGRxQm5vN3VwbkZrZXBzdEdjVjgKLS0tIGxHaFFoSWI0bGpwckZiZHA4Ykhz
            dGl4Q3pBZklHUTNlK1Z3aXNIL2lxOGcKdO+wqz8aO4f/RpqAWsm11uUWEWTLuLQK
            CLyPt22437oXDsI9gtFgJEPuJuiHomd1T4E1eM0oW8GcYDTKoeyfsA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkY29pRHUyMzh6TS9rSHFl
            MEpPQkRMUVpTOGlENmFuVzZEZ0dseWtreXpZCm13MFYrYlBhM1ZvbjJSdDdUNVRC
            eEZMQmtkczdtdGxQOEpZaHdNVWVQRFUKLS0tIEt1VDZ6cVJVY1BvUTk1ZDBBQlVK
            SEI4K0w5RG5KVno2TU15bnZQb01UMG8K3ej6d30NNdusCwmBr5gHjZTdM6lKvYGP
            XgkWd6eHRqgX2FFy5VnJ+FjZdzpxdpRrMQRciUdqNM5zFx7Ksot7Og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-13T19:47:04Z"
    mac: ENC[AES256_GCM,data:HViNr+vVFces3YIJ7OVhQaSy2KO7nw9gdJjcU/iRagTC2dInivty89Y6vh4EQrIYjUwCnlQIE4gUrtwUe0vgN2W2JFTMsV5KMRfaWy9V1YjzbslybN7L3RsRoQlFw8dt/X0nphrgOm02X6e/fg4NL1CbaDm72BD/rQJQNlca8PA=,iv:nOwUMXMjstOuPkM+gcqVjRZAIOIOSGR5LsNV9ZrIZiM=,tag:K7q2Q8DcL+3tEWGfGfbdTA==,type:str]
    pgp:
        - created_at: "2026-06-13T19:47:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0IKwDTH3WibARAAhWWnPbS6IuQU+y50QfmxXXw7lloweIfxOD39tLH3kHKS
            dD6BX0+8TvQqip68GVIJ94ClRzTqBiqmao5aGBwLrE5Nd3miM/6eDCWWZiui5ec6
            kqkhAo0z7NHt41esAk4hER/V+bw8sbCOVAIM1rp4g+BXRL6q/zfojSkbN2sGIJPf
            iAMf/CccMrFgV3M7z3mBYLXsHosh59D3oirfsqExxXDfXOUaQWGtt2v+JaG3nWIs
            xmLy9PklTsEDNsYt6Ts9L7KF/1jgU/WKvGyts7M0TqzRmCydWORIZro59iYIdHiy
            A9COOtt+fR5kHs1/hITrASZO2H4zyvaizcGZRf0H87DdvQTrDVKyY8wXdVMMVCf1
            0CR8rOm51kLRykk4mD6SJYt7Nc8+GqtvBYUvihglXYoFBSFthDyOAnv0tM23n9rF
            y9mLTx7lH6zU7XlCQYc+v8FDlcvBO2lbBwDDVr1J+azerUXAe/AZRKsM2TVWYuxL
            A5qqAkd+QDbfzkmJHYdk8SDINKGWfTDjwaj6opmAaW/vkSObBMj8r2D5Q2pNqiCq
            INy7fBCC2kuw4IwLU5TLDn6vJ4QhLs5gh7ks1LdK8bXSioFbbu7Le3Zg3iOWjlHY
            STMQDHcLBzwaM7gyQ+cdXrxP8B7nLNfLaLQCyO0OFXlM8JBeiEhV5rgVuQxbglDS
            XgGhBNKKDgd4yl9sRRdexOcb2KkQuqbVs8395PrM1ScQtZHb7xKWiZbSRFDSeBeJ
            sdOQ9mAYCSvawb9sEMYpavDlVqvHiA69jcn8MkobzFUZCiAwRYMqwNBWKVUAVSU=
            =WDYp
            -----END PGP MESSAGE-----
          fp: 03746612698994281D322B09923BC5E9B4E9509B
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
