apiVersion: v1
kind: Service
metadata:
  name: radicle-node
  annotations:
    load-balancer.hetzner.cloud/name: radicle-node
    load-balancer.hetzner.cloud/location: fsn1
    load-balancer.hetzner.cloud/disable-private-ingress: "true"
spec:
  type: LoadBalancer
