apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mealie
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: mealie
    server: ''
  source:
    path: ''
    repoURL: 'https://k8s-at-home.com/charts'
    targetRevision: 3.3.0
    chart: mealie
    helm:
      values: |
        env:
          TZ: 'Europe/Berlin'
        ingress:
          main:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-clusterissuer
            hosts:
            - host: mealie.tiborpilz.dev
              paths:
                - path: "/"
                  pathType: "Prefix"
            tls:
            - hosts:
              - mealie.tiborpilz.dev
              secretName: mealie.tls
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
