apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: woodpecker
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: ghcr.io/woodpecker-ci/helm
    chart: woodpecker
    targetRevision: 3.6.5
    helm:
      releaseName: woodpecker
      valuesObject:
        agent:
          enabled: true
          replicaCount: 1
          extraSecretNamesForEnvFrom:
            - woodpecker-secrets
            - woodpecker-oauth
          env:
            WOODPECKER_SERVER: woodpecker-server:9000
            WOODPECKER_BACKEND: kubernetes
            WOODPECKER_BACKEND_K8S_NAMESPACE: woodpecker
            WOODPECKER_BACKEND_K8S_STORAGE_CLASS: ceph-filesystem
            WOODPECKER_BACKEND_K8S_VOLUME_SIZE: 5G
            WOODPECKER_BACKEND_K8S_STORAGE_RWX: false
            WOODPECKER_CONNECT_RETRY_COUNT: "5"
          persistence:
            enabled: true
            size: 1Gi
            storageClass: ceph-filesystem
          podSecurityContext:
            runAsNonRoot: true
            runAsUser: 1000
            fsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]

        server:
          enabled: true
          createAgentSecret: true
          extraSecretNamesForEnvFrom:
            - woodpecker-secrets
            - woodpecker-oauth
          env:
            WOODPECKER_HOST: https://ci.tibor.sh
            WOODPECKER_ADMIN: tibor,tine
            WOODPECKER_OPEN: false
            WOODPECKER_FORGEJO: true
            WOODPECKER_FORGEJO_URL: https://git.tibor.sh
            WOODPECKER_DATABASE_DRIVER: postgres
            WOODPECKER_DATABASE_DATASOURCE_FILE: /secrets/db/uri
          persistentVolume:
            enabled: false
          extraVolumes:
            - name: db
              secret:
                secretName: woodpecker-db-app
                items:
                  - key: uri
                    path: uri
          extraVolumeMounts:
            - name: db
              mountPath: /secrets/db
              readOnly: true
          service:
            type: ClusterIP
            port: 80
          ingress:
            enabled: false
          podSecurityContext:
            runAsNonRoot: true
            runAsUser: 1000
            fsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
  destination:
    server: https://kubernetes.default.svc
    namespace: woodpecker
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=false
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /status/terminatingReplicas
