apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: woodpecker-secrets
    namespace: woodpecker
spec:
    secretTemplates:
        - name: woodpecker-secrets
          stringData:
            WOODPECKER_AGENT_SECRET: ENC[AES256_GCM,data:iDecVhTuryFBVoqmWscTq0K19mp/e2Virk0aZWLcfdppQQzu6sb/3KO7D71sYawDjPr2e0ZhF7Rp0mJExysyvQ==,iv:MZl0zpH6nGkeQhIES0rhi091+vl3cHFPI9ak4E46Bzc=,tag:sDJWhkvVRO3vpG64lHf2ag==,type:str]
sops:
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dXlJWmZ0UmtMcithYzNW
            K2N5L0VLSG1NbUlKelhWYnhEdld4TWJkaGpjCjlmRzRma29KMHpxU09PTTYrckgv
            Wk5xbHgzalFyZnFSK2tGTjMyRjhYdmMKLS0tIFRCL0ZEZWF3T2dXdG9STVZTR1N1
            ODFkczd4Q21oZUlIdVdhMDVRbER5djAKDPTFCugc/F8hMLVum4fc9np5KuXxhvOF
            65F3MHdfPAEK32FOIlXnNJB+OOvgXFatfQlnDq4xKXJNYS/rTPgErQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZL3dTOS9mRXdnZHhWZHA2
            dndGaFI5UEZzZ2FET2JsNVhxRWtkazdHbHpFCm93dHZiSUcrVTFXMHpqOVdmZk9j
            Uml4RERlU0NibUJBbjRDMy8xd2hWVnMKLS0tIFFyQUl6K0hXZ2FyWS9Qd2tmU3h5
            cE5meGNER0E4MUg0aXA2VzFCVWJWNkEKwH1ARhn7jYG2is4PLn/aa9crU1/bbTz+
            ujsbwWRmHUUW6gmL+JrwwAqHppwfIHu6E3ZUJkt5+DPwgMOT8nGbvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-13T17:01:44Z"
    mac: ENC[AES256_GCM,data:AxmrCliaJAJj8iL0kpj7LT411jaox0nlZe69R8mSneaPm1UM8RHNrhiYsgQU60p/SVzStT2z3J1VF/4tPsRCK2YZFP8Pk8wcqQGI9w2z9r9awtK0hNog3vm7iSVh+M2J1YmpU0iMP0JPIl0ZRNl3ukw5aFxEwvmzEPR+rpWAlr8=,iv:wt/sg9l9kywRDnAfPqmpXlRH1i2mVz5HAeX/YwOFyBE=,tag:Nr+kj9lFIyz6fXqkMSHMuw==,type:str]
    pgp:
        - created_at: "2026-07-12T20:03:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0IKwDTH3WibAQ/+O80GMMeHGW/ysoObFxLD2wZ+U00fkPJJ+MXzfeuDOW6i
            mhsbfdMqCTr7AMRQenxMoFFih52iMfL/ONY1lN9gFBkEaNrR/NTtzfIUJtoybJDb
            WqWiZMZVTN1iNAwaXcMTsPuU5Rajq9s3dXh3+DXKv3cp6CSKzftKjnzv9Lz7WGYm
            iWNUhlyxJYFnrMv/UVhVC3If7oRTtwE6OVnKvuvReZ7W9/tKF5/y6/yXTPjTGYn2
            pzX040v4G0CX7/AU9B5faKRCSl90dNtf7Tavl5ctRf6YkpFG6GA6OLXauQ2Vs/8G
            YUqdBxtaKqATbQ/7HBRND/Z3qTauq2uqRmIMdBM7f8S5s6uBXNQDx4Jsk5Cr1uJv
            /juGzkv7+EiIpEsodxLSYMAeB4FZdC8LXKIoaB4c2phpHi/5Ne64WbwHSs/2T/qq
            ZVEku15rot3eTcGBru+byDzVFuzndRWgxlvJsh1HMPH6bNMv3yYA6F5CRSNDI84W
            DoFy4yUU6hhcI/dOhdUxcnxu9T74gopcc/WIKD+j8z7wKrKtJPWQ0z7jilRbs8hr
            hpFgSiC8xbE4lrV2nqJSY3ZSRFx+j58dzOIBOEwhe9gg92EPF4DakZORy34woO8l
            cvfzByzasmzQf6i7Bz97BtfShNl5FKGAYcau5hjWvDqweFzlNWs8wqpZNPMkkHHS
            XgGgLbSIibkAs+UfqcBUSDblp9X7J0PDvZxNN6vcIvnai8JWw8iHcyiYzD9icxIS
            rj/qf5lRp7TqV2rrdUgom6y/3IK+Oms9V3ZZtXHUuJ3ASAx+qDYK2vNEwsgxQb8=
            =dKK5
            -----END PGP MESSAGE-----
          fp: 03746612698994281D322B09923BC5E9B4E9509B
    encrypted_regex: WOODPECKER_AGENT_SECRET
    version: 3.12.2
