apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: woodpecker-secrets
    namespace: woodpecker
spec:
    secretTemplates:
        - name: woodpecker-secrets
          stringData:
            WOODPECKER_AGENT_SECRET: ENC[AES256_GCM,data:iDecVhTuryFBVoqmWscTq0K19mp/e2Virk0aZWLcfdppQQzu6sb/3KO7D71sYawDjPr2e0ZhF7Rp0mJExysyvQ==,iv:MZl0zpH6nGkeQhIES0rhi091+vl3cHFPI9ak4E46Bzc=,tag:sDJWhkvVRO3vpG64lHf2ag==,type:str]
sops:
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdEcvampzVThDZ2pISTd2
            Q2hHU0Radzg3dHBveXRDT2tScUtERkxsYzFNCkFJV2RDem9EcnQvN1A1TFBrUVpM
            R2lzQ2RBRDlnOXlsWmozVXQrcjQ5ZUEKLS0tIEpJbytvOXArdU93aVNaZHVFMEQ0
            UTgxVU9hRE54S2lEUkluS0VibHpxQk0KXSSl3BxspxKuOCT5fNdtw6xgpQ3QcwNa
            UKExQFNsgcrCzXKt3PmBDXFNn/B/ikEuAkO0vPB/cipL7YaslEPYOA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gzf883y8p0wfy5yjn5l3l2axnqxdgtw2zdcp8jqsrk65m7gf6y6qzgkf63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSjRuZnBVSS9VUm9UME81
            b2VGQWY2VlhUVU9WQld3MndmK2Y2WUw3cGc4CjlMNzVlUHJ6ZFZjaDNMdkFFTHJH
            RWJROVhOd2RHc3poU0Rkc0ExQnNob2sKLS0tIEJUUTIxVUpnK09ZL2NydTdSVnp4
            M2toMFBLM2crelJ3QStJcVEzZ3c5ck0Kds7NG0QA8DafbqM+VhE2Smhvj+aTRvw7
            Q4dBKNP2eUk8Yq0Y78HQrlnJFFGHSst/qe2Cj8H2om4jjkcOo6JEzQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTllXQ0pMWXFvYjZxSWtF
            bmpMTVhhWVpGZHRmbWpRVHR3TmxmYkdOYzM0ClZZQ0hFOUlRWXQva3lBbWIwemlR
            RFE5a3lXSzl2WE1XMEtXVmRHVGJHMVEKLS0tIE5xcFVFckJJNTl1a2pFOHRIQ09O
            WisxQUZSTEt6VStaL1AxSCtoTUd6VjQKWj3mDfmrGQeBM+Oi7fSTnHaW2PxJFynv
            aVA/bv/Bg27xp8w/5gUOdfWTeSNl429ibEp6ZZ15di9MEkGf09afcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-13T17:01:44Z"
    mac: ENC[AES256_GCM,data:AxmrCliaJAJj8iL0kpj7LT411jaox0nlZe69R8mSneaPm1UM8RHNrhiYsgQU60p/SVzStT2z3J1VF/4tPsRCK2YZFP8Pk8wcqQGI9w2z9r9awtK0hNog3vm7iSVh+M2J1YmpU0iMP0JPIl0ZRNl3ukw5aFxEwvmzEPR+rpWAlr8=,iv:wt/sg9l9kywRDnAfPqmpXlRH1i2mVz5HAeX/YwOFyBE=,tag:Nr+kj9lFIyz6fXqkMSHMuw==,type:str]
    pgp:
        - created_at: "2026-06-13T17:01:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0IKwDTH3WibAQ/8CFvNDGjv4k19aosFHlzZ1boc3bR4rKdTkDboqKb4dBAU
            Tdl3PVMLpqW4lcn/khfJlxNimTeF9ZCcQSxmgCd1gpk6QyNJoTDGhowm2CSEhLDI
            JMOx3h1fw1iJL24tFFcOvK/KArFYB55BcI33wvr5qQ1Gr0KrCE9+ej4bvNe2hzqC
            mSRbJxjbGQYQtAx47YPfvN6T3X4okQDTQ0W08yyXTsPaZp7T0vjiqmSHwgH9Ei/H
            /fDVekhjxA8sLUa8zstLgZkj7j59nzxLGYRMcPwbGTlTeo6kxyTt+Xdp1hE4+8JE
            FZkvDuNYBPsyD/E78/np9WFXcXuA+faxmqQKs3Kk9TYCHKuy0jSB6u98h+lMz+N0
            8cOt56Ta0qKZciK8+MmJUeDYkQt6/2WpNBWcojc8VRlGYMhhi1Jj8S9cYMDnJ5ki
            FoSZf9aD91uvgiGhX5kJfHV6zY8GeByx1/iLLV2t9+ma32RaYK8S1YD57JgkkMc5
            AkjB3lzmyzfATqLY6Ll4dsZrNJY1dv8lmewQAin/ARyHQVr9+A/LcH+/Rbw2VVUi
            UCtE1QknuJvlw7Fx20Q/TxneYosyNoXKhgmMtNF4K2seQRyvAV0y3T6eQAPWu3zL
            yJhoKh52GPZ3dbS+qqbw1JBU1F4ep7FzT/1ETLAHkRstc3EWbYb9DK1iylIkCDHS
            XgH6UKXq70RTAAEcZwd1H0OATZutA2yBzJEaWIMC8WSUWtl/9AuAk57ewAwf2noP
            CxGMw+VW0e/54m6Aww0tQXMb+V/x1aV3/lS1WWZnjgjsJMe1lUWXaHBS0ZICJ7o=
            =ml1o
            -----END PGP MESSAGE-----
          fp: 03746612698994281D322B09923BC5E9B4E9509B
    encrypted_regex: WOODPECKER_AGENT_SECRET
    version: 3.12.2
