apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Platform infrastructure applications
  sourceRepos:
    - https://charts.jetstack.io
    - https://charts.hetzner.cloud
    - https://helm.cilium.io
    - https://argoproj.github.io/argo-helm
    - https://cloudnative-pg.github.io/charts
    - https://charts.longhorn.io
    - https://prometheus-community.github.io/helm-charts
    - https://charts.goauthentik.io
    - https://code.forgejo.org/forgejo-helm
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
