resources:
  # - scope/application.yaml
  - portainer/application.yaml
  - harbor/application.yaml
  - hajimari/application.yaml
  # - forgejo/application.yaml

patches:
  - target:
      kind: Application
    patch: |
      - op: add
        path: /spec/syncPolicy
        value:
          automated:
            prune: true
            selfHeal: true
            allowEmpty: true
          syncOptions:
            - CreateNamespace=true
            - Validate=false
            - PrunePropagationPolicy=Foreground
            - PruneLast=true
