resources:
  - scope/application.yaml

patches:
  - target:
      kind: Application
    patch: |
      - op: add
        path: /spec/source/repoURL
        value: https://gitlab.com/tiborpilz/infrastructure.git
