apiVersion: v1
kind: Secret
metadata:
    name: signoz-oauth2-proxy-secrets
    namespace: signoz
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:9RhYIW+D,iv:LQQeia//k3zDzBZmJ/cmGv5st+3uzVxpPCE2GEDnPIw=,tag:ABHGfut+yDDVSMzE1+cvXQ==,type:str]
    client-secret: ENC[AES256_GCM,data:Dr3z5Sz6rwIPer5eKm4ZQ8xcKO48emWKoRnwLoy6z5mdiiWmySo0f9bjAb4uCOdEeZ+waTQonLS3O9SAe5HGHA==,iv:dwaDXXyp2eUrymR1I6vrMmSbM+IQQ2EnpBwVKMBoIMY=,tag:jApHuHy4pBjzGk5CLR929A==,type:str]
    cookie-secret: ENC[AES256_GCM,data:vTzTCcasD4rFaThdrUkMvXCI7GACmMTKLojfkdlzyg4=,iv:GRn/BUGKNrjbhSpdzTsMENuNmBy3eMesJTVueocSkkc=,tag:XKcW4+tdgbra+d7nsoz0IQ==,type:str]
sops:
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5a29sTUxRR3dsTkpjU3FL
            cklES3dvUUpIZ0xVZDArbHRTaGJRNmRBWER3Ck50ZDMwbTkyWElEamxmTEtjalVL
            VUJLazhlMGhsSWxvaTlhMVVrdW5qd0EKLS0tIEVVcVpGblJiTGlLbUZCQmdodnMw
            Umo1ZE5WS3lTZE94MDBQMzdIQmo3aGMKtvlYf1vvEfb5QdPvWVry3iD2ZNa91nQU
            WKi4y3i76E7tKwFBF7shNfFJH9NprHQqE7L5f5ss1oDnd+B31x54TA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gzf883y8p0wfy5yjn5l3l2axnqxdgtw2zdcp8jqsrk65m7gf6y6qzgkf63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Q0RMVWVCVGE2QUZHUXZj
            TzNYbEw4NEF0NE83MklqckhqRjgwRXVOQVFvCm0wMGdwVzI0bmoxVzEvT080cXhy
            QjRaL0J4c1NxeC9wM1p3Z3RndDhKdjAKLS0tIDJSWE9KSXRQMkNUOUhsVE9EeCsy
            OHNKbnpVVWtJVWhXUDRiclc1cnAzV3cKHu5v98rcJJd7FhL5odJTaRU4Gpjqqfv4
            pkvYcCUDoMsOOJZzfm9dyP9K0IVsqmtbGx8+9r5B76Nx9zDLJdgC2Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZUJ2VXBubU12WnM1cmx2
            N2cwQzhkVVhSVnhnaG14dm1VU1QwdDRKUGtFCmtRRlVuMGFTVW96VWJlU3VsQVE1
            VjBXQjc2YUk2MGgyZjFSNmZwRmNESU0KLS0tIG9yL2xjMExrdHdLZ01EanFTS0ln
            RTUvTlg3VTZmdnI4QlRra1ZXUldnOUEK9ZckgJG/UE2qXg/L9aUSIJJ1BPsd2GRH
            wnUYEbtEaVlsiGr/29hBL8HtxE19G2TO6KE5ZCm0GadCz6X3coiQjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-03T22:14:01Z"
    mac: ENC[AES256_GCM,data:hhaU5Kb/3YZ46cg+sLuyBNIUha0MRYHUSSAPAkJSntqQ5S/2EDyf/tZcBk1Yd+b9KtLOHDvuUsGTsJHYwIhY9YF19OBbgW81kmV8jRSa6p7gpM4TE+NZEliANquEsuegSHcj3Y4/dSnvDe6cKFbJejMGLTk/mkx5tahqZ/Su6IA=,iv:W8Us8VHbGD4sUabrgicr9PT6icIw9zpqtJ+ZvNn8oUI=,tag:eEBWwodGsYwp/U/noemRWA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
