apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gitops-canary.yaml
  - forgejo
  - harbor
  - woodpecker
  - tangled/argo-app.yaml
  - pds/argo-app.yaml
  - tekton/argo-app.yaml
  - headlamp/argo-app.yaml
  - hubble/argo-app.yaml
  - signoz/argo-app.yaml
