apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: oauth2-proxy
    server: ''
  source:
    path: ''
    repoURL: 'https://oauth2-proxy.github.io/manifests'
    targetRevision: 4.2.0
    chart: oauth2-proxy
    helm:
      values: |
        config:
          clientID: oauth2-proxy
          clientSecret: a44fb5cf-d35a-434d-8927-7bd4f00b6dd5
          cookieSecret: SEVuTitJTGFFRnREcmt4bGxYdk1DZEM0QUNHbm1JSHc=
          cookieName: tiborpilz.dev
          configFile: |-
            provider = "oidc"
            provider_display_name = "Keycloak"
            oidc_issuer_url = "https://keycloak.tiborpilz.dev/auth/realms/master"
            email_domains = [ "*" ]
            scope = "openid profile email"
            whitelist_domains = ".tiborpilz.dev"
            pass_authorization_header = true
            pass_access_token = true
            pass_user_headers = true
            set_authorization_header = true
            set_xauthrequest = true
            cookie_refresh = "1m"
            cookie_expire = "30m"
        ingress:
          enabled: true
          certManager: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-clusterissuer
          hosts:
          - oauth.tiborpilz.dev
          tls:
          - hosts:
            - oauth.tiborpilz.dev
            secretName: oauth.tls
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
