apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - talos-serviceaccount.yaml
  - objectbucketclaim.yaml
  - cronjob.yaml

images:
  # TODO: pin to a released tag from ghcr.io/siderolabs/talos-backup once confirmed.
  - name: ghcr.io/siderolabs/talos-backup
    newTag: "latest"
