---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: rook-ceph-mgr-dashboard
  namespace: rook-ceph
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-clusterissuer
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
    external-dns.alpha.kubernetes.io/hostname: 'ceph.tibor.host.'
spec:
  tls:
    - hosts:
        - ceph.tibor.host
      secretName: ceph-tls
  rules:
    - host: ceph.tibor.host
      http:
        paths:
          - path: /
            backend:
              serviceName: rook-ceph-mgr-dashboard
              servicePort: 7000
