---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-clusterissuer
  namespace: cert-manager
spec:
  acme:
    email: tibor@pilz.berlin
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-clusterissuer
    solvers:
    - http01:
        ingress:
          class: nginx
