apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-from-gateway
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: gateway-system
      ports:
        - protocol: TCP
          port: {{ .Values.container.port }}
