apiVersion: v1
kind: Service
metadata:
  name: {{ include "preview-app.name" . }}
  labels:
    {{- include "preview-app.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "preview-app.name" . }}
  ports:
    - name: http
      port: 80
      targetPort: http
