apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: smtp-secrets
    namespace: smtp
spec:
    secretTemplates:
        - name: smtp-credentials
          annotations:
            reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
            reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: forgejo,authentik,observability,penpot
            reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
            reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: forgejo,authentik,observability,penpot
          stringData:
            password: ENC[AES256_GCM,data:eqsjZA7GakvEJNYhs9tSpNi4d7npmWDZUM3IogBcvoKz3OWNeMd61SHTzXas17bObWERgYE=,iv:RbaA/QpXAByLFnZVYbjDNJ26DIa4DVOjo4pEmmhFjQ8=,tag:nC6ZFLn+uFgJDZKUhrVWYA==,type:str]
sops:
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMUJjNkg3ZWRYcFYrOVFm
            aVpUc3N4ek95SWNzT3pkdmRjeHhsUnJaT0ZVCk9sT2YyVnhDdFA3Zlo3Z0w0Vk1i
            SlhOOVg3L1hwTUNkY2xNVVpSN2k2TlUKLS0tIEFBNkFVV1ZEM2d3bEhaZEdvL3A4
            dFRRekQ1TmJjNnRlQ0RrVEttcThTWGsKBIF2WtsLl1R9t1wJ3aOjVqbcPTWZgQC9
            BH41O0gGawRgjgNnAq09k445DFuJ/DMK1G+AP8UKSCGi/Ege9mlwUg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVCtZK2Vna0pKdzJKbnEr
            NFhwa2lXeHV0R0VVbU5lSEduaXJkbkxoV3d3CnFQWFJBQUVxTEJSSUtwQnl1NWRP
            V3lTOS9OU1hBWmc3c01QOFlVTnVtYVkKLS0tIFdUZStqNnl1ZFpUOStZTUwzOERz
            RFhIN1lBMTZqNXNLM1NsV0xmeHF1NU0KFOgjJmp44aud1j50J9QDlaiFg/+TstbM
            vN4bLdDBt9rYiemQR5vx9cNtpd2B2O3QavGnVkoLRz0qY2bHjll3vw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gzf883y8p0wfy5yjn5l3l2axnqxdgtw2zdcp8jqsrk65m7gf6y6qzgkf63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMmNYcUJIc0N3Wm9XS0xq
            anpjbnFTdHB4QTQrN295WWNyNTJNQ0VHT2h3CmJSK3NNcXdNclNoTW1ZTVdwNkFZ
            T1FvNmFyRnhwa0ZBMWE2bW1pR1oxWm8KLS0tIERtc0tQdW1DcDZ6UGxLcmhVd1lD
            WUdJSDJaMFEvOTBCNzE5OFYwMVlhalkKpFIbRLUMDOR35AsIbzHqFDrXASvyxj5i
            OGg3XQu0qEF++it6EIgIb73ta0nN7JqdXKgDhAtCueTP2z1zUzqmpQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1j460k9yf4l3smlegue9yx4lwm70cr02308ea5wnpsuqagm25tgrsmfmpj2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVYkFVVitncW1LVy90UkYx
            MDNGWUFwQmsrT1FkVDhXN2pGQlZNaWs2UFR3CjluS0JWWXZPN3JWeUJvdFU5aWg4
            eGlMZjVwY1ZuTDBBVkpPVCtuVy9KY3MKLS0tIHhYU25VNjFmRFpLTDZaUU1iaUIz
            UEJXaTJCNmdOT3I3QW9yUHJpSGM3dUUKNobeWGzxXJQaeJ6ooS5mqJUwsZY28lmv
            JAmir99jIR5JspBdA2r9KxKXBMa5JxkOK4Iw0pB+GUGrTBAL4nAbvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-02T14:30:57Z"
    mac: ENC[AES256_GCM,data:QMI3xrgyR6IRkyTDZ38JQ8+McUH7ubT0tAIAAu1acyLmCveuKXFfu2mIoufvv1oVre4mN5GvZlybsfzKojYT3tq5EWVXCoziXMKniY5mqoR4INDLAY7QcRpm1NtuANHWV1rMmXDNH/d8HvVTKKq3txkW0t5UZMjv74xUqbDy190=,iv:7Sb7NdI4qDR4BydL+KAp7TghxIGWTvDZL4TyxETWBCs=,tag:TxQkJ8g1W5SMzGtjhNAdDQ==,type:str]
    pgp:
        - created_at: "2026-08-29T12:33:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0IKwDTH3WibAQ/+MdJdTe8tZA4VCXO2jpzjxq1BDy9XVqqiLb8NOew6KHMP
            ZmY8yWb6qv5HZeFHwkrDyS5rr1zotM/FraU3Iii6EeICRd6Bu5+oLYGvgOlLB3cu
            5UOJy2Am4i0nctBhKXAyC0V1SX+7+ipwUjB/egqQRtSBcHA639UxVHKSNOw6c2p8
            soh/YKDsGvVj66lxAhm6upXkkpBfMN+X1XeY3UJfbBSSa9HPqJyyogrIyfdqdsWG
            4R+PuKCGKghCCSbxAPXZzblEUvLyr1p2LqxQa8pPuNbcPohIJw7SEf2mOQCadbIy
            yCYxRpWS9ZALjj1nCPPxYDD7Jm7hiKJHo9/yMI49AdyyqqGbN3AhY4IXVPcB9fG1
            93FmNaqTj0zdIknHIVa8e6c2BFNupqcoWngaJQTZjKhJ5Mpfv3yZEsG8t9RBTJEH
            asc59mqE3nUEmy/hixX/B0HG56dit+RVIWfjDff4qZ+7lwEo32ToDuRaK1tjJxMb
            ZXN7p6LaZJ+XVsJYLanzMOhI2CFdyBnxLFMrTkLNElMQD6zyg4a2OVfvex+dB/u4
            Zu/4qDJQvUnBZgIP73+AQZStxeYvXRgMIGWNpbKqf96s2E+82extZt/ioqxkAu5m
            03Fxjwb+j1ghLvi56MoSBxshLyhq2Kt0fPEE0lAoyIRe2B+lMvb66ef6B+AYP4XS
            XAE+MDUQ6QSmXo4kmcMhdofDmlzqRB3EvERwHKJQov7er3MCzKIgD0yeXoLEVSd6
            IBAMCDhtV4PSxFaUL5joDI0IQBjhUwDgyWGlz3RnKWhnBIp2SkEvk3YF0mc2
            =5c+K
            -----END PGP MESSAGE-----
          fp: 03746612698994281D322B09923BC5E9B4E9509B
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
