locals {
  argocd_namespace = "argocd"
  hostname         = "${var.subdomain}.${var.domain}"

  # Stitch the chart values together. The base values come from the env layer
  # already templated; we decode, append the additionalObjects (each as a
  # parsed YAML object so the chart's `tpl (toYaml .)` pipeline treats them as
  # k8s objects, not strings), then re-encode.
  base_values = yamldecode(var.authentik_values_yaml)

  additional_objects = [
    yamldecode(var.database_yaml),
    yamldecode(var.valkey_service_yaml),
    yamldecode(var.valkey_statefulset_yaml),
  ]

  helm_values = yamlencode(merge(local.base_values, {
    additionalObjects = local.additional_objects
  }))

  # `var.platform_data_ready` may come from either a Terragrunt dependency or
  # a parent Terraform module. Keep it in the Terraform graph so authentik's
  # CNPG Cluster is not applied before the CNPG operator and StorageClass are
  # actually ready.
}

resource "terraform_data" "platform_data_gate" {
  input = var.platform_data_ready
}

# ---------------------------------------------------------------------------
# Namespace.
# ---------------------------------------------------------------------------

resource "kubernetes_namespace" "authentik" {
  metadata {
    name = "authentik"
    labels = {
      "managed-by" = "terragrunt"
    }
  }
}

# ---------------------------------------------------------------------------
# Bootstrap secrets — TF-generated, lives only in TF state and the cluster.
# Never committed; never SOPS-encrypted (Path B in PLAN.md secrets strategy).
#
# `secret_key`:               authentik's Django SECRET_KEY equivalent.
# `bootstrap_admin_token`:    initial API token for `akadmin`. The next layer
#                              (services) authenticates with this
#                              to manage authentik state declaratively.
# `bootstrap_admin_password`: initial password for `akadmin`. Replaced by the
#                              services layer with a stable
#                              TF-managed password.
# `valkey_password`:          --requirepass for the inlined Valkey, also
#                              consumed by authentik via AUTHENTIK_REDIS__PASSWORD.
# ---------------------------------------------------------------------------

resource "random_password" "secret_key" {
  length  = 64
  special = false
}

resource "random_password" "bootstrap_admin_token" {
  length  = 48
  special = false
}

resource "random_password" "bootstrap_admin_password" {
  length  = 24
  special = true
  # authentik password validators reject some symbols; stick with a safe set.
  override_special = "!@#$%^&*()-_=+"
}

resource "random_password" "valkey_password" {
  length  = 32
  special = false
}

# ---------------------------------------------------------------------------
# Secret consumed by the chart's global.envFrom.
# Keys map to authentik env-var config — see
# https://goauthentik.io/docs/install-config/configuration/.
# ---------------------------------------------------------------------------

resource "kubernetes_secret" "authentik_bootstrap" {
  metadata {
    name      = "authentik-bootstrap"
    namespace = kubernetes_namespace.authentik.metadata[0].name
  }

  # When `authentik.existingSecret.secretName` is set on the chart, the
  # chart's own Secret rendering (which would normally translate
  # `authentik.postgresql.*`, `authentik.redis.*`, etc. into AUTHENTIK_*
  # env vars) is skipped entirely. Anything authentik needs at runtime
  # has to live HERE.
  #
  # The PG password is the exception — it's generated by CNPG, not by us,
  # so it's mounted via `global.env.valueFrom.secretKeyRef` against the
  # CNPG-emitted `authentik-db-app` Secret instead.
  data = {
    AUTHENTIK_SECRET_KEY         = random_password.secret_key.result
    AUTHENTIK_BOOTSTRAP_TOKEN    = random_password.bootstrap_admin_token.result
    AUTHENTIK_BOOTSTRAP_PASSWORD = random_password.bootstrap_admin_password.result
    AUTHENTIK_BOOTSTRAP_EMAIL    = var.admin_email

    AUTHENTIK_POSTGRESQL__HOST = "authentik-db-rw"
    AUTHENTIK_POSTGRESQL__USER = "authentik"
    AUTHENTIK_POSTGRESQL__NAME = "authentik"
    AUTHENTIK_POSTGRESQL__PORT = "5432"

    AUTHENTIK_REDIS__HOST     = "authentik-valkey"
    AUTHENTIK_REDIS__PASSWORD = random_password.valkey_password.result
  }
}

# Separate Secret for the inlined Valkey StatefulSet — only the valkey pod
# needs the raw password. authentik reads it from the bootstrap Secret above.
resource "kubernetes_secret" "authentik_valkey" {
  metadata {
    name      = "authentik-valkey"
    namespace = kubernetes_namespace.authentik.metadata[0].name
  }

  data = {
    password = random_password.valkey_password.result
  }
}

# ---------------------------------------------------------------------------
# Argo CD Application — authentik chart + the per-instance data plane
# (CNPG Cluster + Valkey Service/StatefulSet) injected via additionalObjects.
# ---------------------------------------------------------------------------

resource "kubectl_manifest" "argo_app_authentik" {
  yaml_body = yamlencode({
    apiVersion = "argoproj.io/v1alpha1"
    kind       = "Application"
    metadata = {
      name      = "authentik"
      namespace = local.argocd_namespace
    }
    spec = {
      project = "platform"
      source = {
        repoURL        = "https://charts.goauthentik.io"
        chart          = "authentik"
        targetRevision = var.authentik_chart_version
        helm = {
          values = local.helm_values
        }
      }
      destination = {
        server    = "https://kubernetes.default.svc"
        namespace = kubernetes_namespace.authentik.metadata[0].name
      }
      syncPolicy = {
        automated = {
          prune    = true
          selfHeal = true
        }
        syncOptions = [
          "ServerSideApply=true",
          "CreateNamespace=false",
        ]
      }
    }
  })

  depends_on = [
    kubernetes_secret.authentik_bootstrap,
    kubernetes_secret.authentik_valkey,
    terraform_data.platform_data_gate,
  ]
}

# ---------------------------------------------------------------------------
# Public HTTPRoute. Attaches to the Gateway in gateway-system; the Gateway's
# wildcard cert covers <subdomain>.<domain>. external-dns picks up the
# hostname and creates the Cloudflare A record.
# ---------------------------------------------------------------------------

resource "kubectl_manifest" "httproute_authentik" {
  yaml_body = yamlencode({
    apiVersion = "gateway.networking.k8s.io/v1"
    kind       = "HTTPRoute"
    metadata = {
      name      = "authentik"
      namespace = kubernetes_namespace.authentik.metadata[0].name
    }
    spec = {
      parentRefs = [
        {
          name      = var.gateway_name
          namespace = var.gateway_namespace
        }
      ]
      hostnames = [local.hostname]
      rules = [
        {
          matches = [
            {
              path = {
                type  = "PathPrefix"
                value = "/"
              }
            }
          ]
          backendRefs = [
            {
              name = "authentik-server"
              port = 80
            }
          ]
        }
      ]
    }
  })

  depends_on = [kubectl_manifest.argo_app_authentik]
}

# ---------------------------------------------------------------------------
# Readiness gate. Downstream (services) authenticates against the
# authentik API and needs it ready before talking to it.
# ---------------------------------------------------------------------------

resource "terraform_data" "authentik_ready" {
  triggers_replace = [
    kubectl_manifest.argo_app_authentik.uid,
  ]

  provisioner "local-exec" {
    environment = {
      KUBECONFIG = var.kubeconfig_path
    }
    # Pod readiness implies the chart's HTTP /-/health/ready/ probe passed —
    # no separate curl check needed.
    command = <<-EOT
      set -euo pipefail
      kubectl wait --for=jsonpath='{.status.health.status}=Healthy' \
        application/authentik -n ${local.argocd_namespace} --timeout=15m
      kubectl -n ${kubernetes_namespace.authentik.metadata[0].name} \
        wait --for=condition=Ready pod -l app.kubernetes.io/component=server --timeout=10m
    EOT
  }
}
