apiVersion: v1
kind: ConfigMap
metadata:
  name: outline-config
  namespace: outline
data:
  NODE_ENV: production
  URL: https://outline.tibor.sh
  PORT: "3000"
  PGSSLMODE: disable
  REDIS_URL: redis://outline-valkey:6379
  FILE_STORAGE: local
  FILE_STORAGE_LOCAL_ROOT_DIR: /var/lib/outline/data
  FILE_STORAGE_UPLOAD_MAX_SIZE: "262144000"
  OIDC_CLIENT_ID: outline
  OIDC_AUTH_URI: https://auth.tibor.sh/application/o/authorize/
  OIDC_TOKEN_URI: https://auth.tibor.sh/application/o/token/
  OIDC_USERINFO_URI: https://auth.tibor.sh/application/o/userinfo/
  OIDC_USERNAME_CLAIM: preferred_username
  OIDC_DISPLAY_NAME: authentik
  OIDC_SCOPES: openid profile email
