apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - database.yaml
  - valkey.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml

images:
  - name: outlinewiki/outline
    newTag: "1.9.2"

generators:
  - kustomization-ksops-generator.yaml

patches:
  - patch: |-
      apiVersion: v1
      kind: Secret
      metadata:
        name: outline-oidc
        namespace: outline
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "authentik"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "authentik"
