apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secrets.enc.yaml
  - database.yaml
  - valkey.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml

images:
  - name: outlinewiki/outline
    newTag: "1.9.2"
