apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: outline-data
  namespace: outline
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-filesystem
  resources:
    requests:
      storage: 10Gi
