apiVersion: v1
kind: Secret
metadata:
    name: outline-secrets
    namespace: outline
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:PVjDVt1LLEenLYI0BM1L3B0sMo+HUSM9RjnV18iKDXNUXJ5fcrJsWwmy4AqoisJl/WjCsVbPVKyH96QG05y1rA==,iv:JTg2zVcWobvDrKk9xTjYbiG64+UAG7iflGQOK87GGdU=,tag:e80PZlVkp0rj6sGQYnDBwg==,type:str]
    UTILS_SECRET: ENC[AES256_GCM,data:wF6+5XnsZEyIfIYx2tJc9MPZRgiG1GnEmEzS/q1fAqGyd+LFdgyGFgvfXsCQKL3IP34QxPaSwRDytvwPdowqVA==,iv:L/gEyJZ8npVVYJ49B9sd+oNOiDxAoOZn87+g6uxTyfw=,tag:tPPbRC2eHYfkup3/vkkjKA==,type:str]
sops:
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUEFCMjAxS2RjQkFVaHB4
            UUZVWnhlSkw5UkdVTVdhbmVLcWgrWWIzSWtjCjV4M2YwMUs1b1crcEhoNDViRUtp
            YkpuMzdNdlFKU28yUGFsOEdBd1Z3YzgKLS0tICswVTkzT0RxVWlYRGVrcENRRmNS
            Q296QjBHY1p1NG0vQ2d1ZlVTUjBvYWsKnwjRI/fyKWj1rcRRAWbZkin2OvhQVji3
            ck9dPloDiVjGFZTZjWEF6WjKFGN9R6fWs2fMA/7Ovp0bg4WY5YFgWg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxR2V0UlZ4WVRRNHY4TERk
            dDJDS3U4cUszM05pOFpMNGthTjBMU093M0h3CmY0czQvcW5rTTlkREN5RExHaCtX
            OWVXT01vaVVmdW1rSmJmWmxuYkRtNTAKLS0tIElQTWMwYlZMY1NzcmEyeVgrVys1
            anRVTkdZTmpzSnBIem9jb0dVWDJXdUEKEf0PJBukBRld2P7fRDp/pTPxh6+294mi
            DGaAmtJlYw4kHohNNgCK6JPrqXIE3GU5A9aLpmTEXWds24POAsBUvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-24T11:40:28Z"
    mac: ENC[AES256_GCM,data:IzzLU6XCSGgjYEWkcwX49BeZYf66Ys5MLbyJm2COZcETDKCOiKywQvNSORps0Pt81sIh8annGXtTcwYwJGl/RMPcl1V4UuJHIz4Rgtc1+ueUQbihqcFY4wd0GYgp+bi4UbykGRrOYoxBh0zdnhjKtuAj6hLUc6VEUsQ3/Mx1YaA=,iv:JO+fIhp039fl2dAZ5PbB0REU2umHE1TEYlUmFoaPlrI=,tag:b4NWQBgvbuzJ3HuOC2+9iw==,type:str]
    pgp:
        - created_at: "2026-07-24T11:40:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0IKwDTH3WibAQ/9HlhSMu7UH94yl7CPzAMM0CaKBSS0cA9BK7IxnmxVIveY
            URMtXhitoLOq0Wy0+CX7o8gGKe04FryDafsyUfFyl0qaFMfPD2LALVvGLYTOixpG
            0v2LHJmtIOSW/tm9r98DNgaEMM8ppSS3fbfHvOEZKYl4FsQnPK0C7bWiBuRGErtN
            cLQvkhXj1Tenbh6fhMmMzknxYNtRsGgkpe8/hPHHIk8htOoEK/5IGMBdWJuOR9iO
            DrzR7uVdNnRt+WmbQP/+l4qyze7DzYy5e3oNEvQKPC0A2v34OHJIxtMQIFV1yrcm
            Dn9U4uWkomh/++BhA1+B5wzLbxl2VESUtihypo+0ya2Hd36y9kmzSuED/pf0YoxT
            HRMHTtWucNl+9vz0iQlw8Yofao0rqKWQbTUgTCXNLlNRWIhwf1yKzey0uWES29gN
            3lw9nVuTzmPmNaTtibwsCkQYMYfqbMjEzsUvMZ7P31uDqJLqA/OiLaVk9qlYohdV
            uhz1LE5qOJSSJtQLmAT2qH7grnjf2UqIBtqoi6QYa6U67fjYJsmoP7S4oTylbSrD
            KyopdMjj059PgGfKS2553IvYOMkTe6aqu+0au1Km0hmWLOc5ZB6WJPkTJCOi/l+k
            /f67S6R+wom/t3+SY+h7h1EmAb904M9d6pEKDS4+N5oMXEy92LHTtJOFbhxdTY3S
            XAEUt/3q85kvBP7fTNEYhn6+XjkEEziXOxKXJzuFubgZm81tTqRAikEwJxkjFpWl
            MisXHTUZHesT3pMWA1Dc4zUS4P1A1+fCC9l8bR6uCwb+lIAVsCDFKa5+UyEQ
            =rA1u
            -----END PGP MESSAGE-----
          fp: 03746612698994281D322B09923BC5E9B4E9509B
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: outline-oidc
    namespace: outline
stringData:
    client-secret: ENC[AES256_GCM,data:RkuksVX1lUTd04obGjRWJyFwqfdr7rPyFwly73TEN3shU0MYbPZrblDUMZrCmRCia+xfH/4C+20d1i6lKZoe4g==,iv:Va+3qSe90h4pkWkbnfa76Nd5UglxPdq0yJnAHj4PuZ0=,tag:dpczkUSB8VLy8Ow3/0qR9A==,type:str]
sops:
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUEFCMjAxS2RjQkFVaHB4
            UUZVWnhlSkw5UkdVTVdhbmVLcWgrWWIzSWtjCjV4M2YwMUs1b1crcEhoNDViRUtp
            YkpuMzdNdlFKU28yUGFsOEdBd1Z3YzgKLS0tICswVTkzT0RxVWlYRGVrcENRRmNS
            Q296QjBHY1p1NG0vQ2d1ZlVTUjBvYWsKnwjRI/fyKWj1rcRRAWbZkin2OvhQVji3
            ck9dPloDiVjGFZTZjWEF6WjKFGN9R6fWs2fMA/7Ovp0bg4WY5YFgWg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxR2V0UlZ4WVRRNHY4TERk
            dDJDS3U4cUszM05pOFpMNGthTjBMU093M0h3CmY0czQvcW5rTTlkREN5RExHaCtX
            OWVXT01vaVVmdW1rSmJmWmxuYkRtNTAKLS0tIElQTWMwYlZMY1NzcmEyeVgrVys1
            anRVTkdZTmpzSnBIem9jb0dVWDJXdUEKEf0PJBukBRld2P7fRDp/pTPxh6+294mi
            DGaAmtJlYw4kHohNNgCK6JPrqXIE3GU5A9aLpmTEXWds24POAsBUvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-24T11:40:28Z"
    mac: ENC[AES256_GCM,data:IzzLU6XCSGgjYEWkcwX49BeZYf66Ys5MLbyJm2COZcETDKCOiKywQvNSORps0Pt81sIh8annGXtTcwYwJGl/RMPcl1V4UuJHIz4Rgtc1+ueUQbihqcFY4wd0GYgp+bi4UbykGRrOYoxBh0zdnhjKtuAj6hLUc6VEUsQ3/Mx1YaA=,iv:JO+fIhp039fl2dAZ5PbB0REU2umHE1TEYlUmFoaPlrI=,tag:b4NWQBgvbuzJ3HuOC2+9iw==,type:str]
    pgp:
        - created_at: "2026-07-24T11:40:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0IKwDTH3WibAQ/9HlhSMu7UH94yl7CPzAMM0CaKBSS0cA9BK7IxnmxVIveY
            URMtXhitoLOq0Wy0+CX7o8gGKe04FryDafsyUfFyl0qaFMfPD2LALVvGLYTOixpG
            0v2LHJmtIOSW/tm9r98DNgaEMM8ppSS3fbfHvOEZKYl4FsQnPK0C7bWiBuRGErtN
            cLQvkhXj1Tenbh6fhMmMzknxYNtRsGgkpe8/hPHHIk8htOoEK/5IGMBdWJuOR9iO
            DrzR7uVdNnRt+WmbQP/+l4qyze7DzYy5e3oNEvQKPC0A2v34OHJIxtMQIFV1yrcm
            Dn9U4uWkomh/++BhA1+B5wzLbxl2VESUtihypo+0ya2Hd36y9kmzSuED/pf0YoxT
            HRMHTtWucNl+9vz0iQlw8Yofao0rqKWQbTUgTCXNLlNRWIhwf1yKzey0uWES29gN
            3lw9nVuTzmPmNaTtibwsCkQYMYfqbMjEzsUvMZ7P31uDqJLqA/OiLaVk9qlYohdV
            uhz1LE5qOJSSJtQLmAT2qH7grnjf2UqIBtqoi6QYa6U67fjYJsmoP7S4oTylbSrD
            KyopdMjj059PgGfKS2553IvYOMkTe6aqu+0au1Km0hmWLOc5ZB6WJPkTJCOi/l+k
            /f67S6R+wom/t3+SY+h7h1EmAb904M9d6pEKDS4+N5oMXEy92LHTtJOFbhxdTY3S
            XAEUt/3q85kvBP7fTNEYhn6+XjkEEziXOxKXJzuFubgZm81tTqRAikEwJxkjFpWl
            MisXHTUZHesT3pMWA1Dc4zUS4P1A1+fCC9l8bR6uCwb+lIAVsCDFKa5+UyEQ
            =rA1u
            -----END PGP MESSAGE-----
          fp: 03746612698994281D322B09923BC5E9B4E9509B
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
