apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: outline-secrets
    namespace: outline
spec:
    secretTemplates:
        - name: outline-secrets
          stringData:
            SECRET_KEY: ENC[AES256_GCM,data:voDkE6O4hljaWuYsnhQUHETPlFq4dVeCXFsmOwZy32dwmj/FgH8F9102E1CaglP0x1Z9SyZsdJlo2/7MgUSRiw==,iv:0+ECXt+Bzb60kfpfesYGCxK8PSa1edXRHThx7M+Qk70=,tag:IKPbMi9GXuB7D9X94PBvLg==,type:str]
            UTILS_SECRET: ENC[AES256_GCM,data:sszhDVI6jAvA52wXkAOgS8ofpM2X3Zpbd/R5ttIwZhTeLBBgpujIHSVQgVpufpC2l5VxYfra6S1Pe8QrHczWZA==,iv:GqFvscE7ntlimrjrdphNtIKZN4ngp/SR/RU0JzbtaaM=,tag:zqu6Yggr/WLZgm8ikzb2wg==,type:str]
        - name: outline-oidc
          annotations:
            reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
            reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: authentik
            reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
            reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: authentik
          stringData:
            client-secret: ENC[AES256_GCM,data:kzqXdCih3shTJ23Wru14K4ywGCK2r9tHFO3ZKm3do4SwV69BYt2g+NPQZ3rXtba2w6Q47DTAyRUKcEfwBGHDAw==,iv:wjcjoZScE4hRkf3SKt5I0dQ326uh9HMfMerzcY4RPI0=,tag:uubQAsBPDbOjuRRs7N82Fg==,type:str]
sops:
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQV2hRak9yc3BiSmdiaVAx
            c3NzQ3l0NnMwT1l3NWwyenVqeGFyUHRYdm4wCmlHOFV1eFN3b1NBUmZMSTg3RWgy
            MmhYYnlXWk1wa25nYWVDcGJJRGZLUU0KLS0tIEZjN2R2UXNzSlpwZVErYnJRVGE2
            Qno3bDBlQTEvTTJmM3h0YUtHaHdBM0kKZtyZCSV4OqAMMGwuNEO16xR7wVOcaDUz
            m037z64N4RtLsVgq5RNZEz1J4OsTw24dcWtrya+oBT2IDWjIrlMc0A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbWxrcnp4ZXBEbWxZcjVO
            TkZSZDdjU3lFMUJ2U1hrYVRYTVVHekVLSmpjCmcyUVptYkhFQ0RRelZYSUorNWw0
            YVdKZ2lWNzhUUGk3elp5L0RrNlVpTEEKLS0tIFZrTXdjcUpOelNkT0wxQ0dvN1F2
            UTh5NjkyaHRka1pONnkvbTlMZkt0aDQK3GdFq72W7sy9jgZLOzRWJs2n13kJZlCi
            yun5fMt6WujSOUt3HknPiLHAzv9XXKHBn+1TrOSGakYJwYQZQuZReQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-26T11:14:13Z"
    mac: ENC[AES256_GCM,data:IptkMXtHF2jzUQMFJ11akmGivFoVQXNSqMJHEpLd9s9rK7h0L+orbZ6EUb3kYb0Ehho2AClXZOPy/XesyAB7hAPmglRbUM6tsB8c/ZXYYLo5CDbioZNvhEGKU/xQ4eWumYgv0c0zRXddGARjKzMPK3Mg4B1CqJQAGrk+10v5658=,iv:QgQW9Cfi5Bca2N/WB3XmUKS9hdgnuyesEROrOXRjs/E=,tag:SAsVtHUcX49FghVodwFePQ==,type:str]
    pgp:
        - created_at: "2026-07-28T13:40:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0IKwDTH3WibARAAk/fN3I0gv+XG8PRehq2aonxXB77o609zYvVL+b+B/m4/
            NvsiB4EBk0spjXpQ+fzuQ5MHGSv9hYlypARiJ9IudYg6NH+rtQ94Jnx7AFq7jAMn
            7ZGpE4aUkD+67AiM4HxOjMnBQDCU07kdprif5NQqISXVXFBkGVo7RQh1INmRz4ug
            8BZU0XnS1D9INmK2GWLTJ2YnMqBhq45m4QKhyK1DwBv4ma/ptfUZKrZCmYqJCiGQ
            +QY5GN4NUx/vrVVa6zILQ8Lk4a1d41pMlUsneTz+STkjMZ3IWgdQvNPf7803HxJl
            NWRgUkLfcDi/LQQhyH8fmBSypy5tamC4tRlyrelQ0jwNOx25eGWWeRYRboWMbvVK
            nObjl+nMKjDOMxlGCIPum2GJWlm7aN+bjYj1ErYCgO9epq/b1nQpXIqkiyDko4Jm
            a8HFAJd+H7EyEogJyhFpKDJxh/jpxGlFNEh8zGVE8H7liRxlVqypA+nwGIHZXLBL
            y6bJov4jkfzqqGrb3zCV1zdkw3gjDgIWrDx+rVaKRYUaWsHEfSTEHIv7mHOsrYhP
            GCkFw4+KczOnXqIYFE0aClJBeWtyhObggVR5ZQZtnqU2qNjbMEYTwrsu6SKXAiUd
            QlpFf4VgWhQId+WHaYu54I1iJgmrhQQIW6iuZVNXv6VzKGrxZ2N9ypNzyae18PXS
            XgEBwaMIgSkbQhZlfa4oniqQA+O4sKVfJpPcWDbRF0vaeaRQbk23vp040aMbQJR0
            vaOLBjSN1bX9FOPPqU1yHXevd/1Vt3WTbkbVA4dvzBK9TQwCkKRjKRahq43kOwM=
            =3+fb
            -----END PGP MESSAGE-----
          fp: 03746612698994281D322B09923BC5E9B4E9509B
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
