apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
resources:
  - namespace.yaml
  - https://github.com/kubernetes-sigs/external-dns/kustomize
patchesStrategicMerge:
  - cloudflare-patch.yaml
