apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: headlamp-secrets
    namespace: headlamp
spec:
    secretTemplates:
        - name: headlamp-oauth2-proxy-secrets
          annotations:
            reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
            reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: authentik
            reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
            reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: authentik
          stringData:
            client-id: ENC[AES256_GCM,data:wNvDwLnUhqQ=,iv:prOq0PQIqR0n08fWRvv0SSL/UaPLB8i6Y4/VQ5hhAA4=,tag:h8Lptpor+kaRNJcx5NkW5Q==,type:str]
            client-secret: ENC[AES256_GCM,data:q9KIkkNmerb2OnDe+IK7JXOMsXfT5J5d5SQbKhpVgbxV3VGsyg2SK3R0gh9Q+TypdBRdg5IQAQKqtI/dtkxBQg==,iv:L7mwRY0OAfVYLWLXM2yEKRm5ipyOGLrFLRtrma2ucqU=,tag:2jlZgAgxV0n0jPSYznOwpg==,type:str]
            cookie-secret: ENC[AES256_GCM,data:fIbKWB6yy/08oqJQ8QjZElgzKVm3M3r4XxqvpOrPUs3ZXByqjotBWZaCFw==,iv:e6ts6FeWZsvUG2U2q3uYpbqZTSIgsaEL0gUwm8ApFNg=,tag:awyNiQ6Jz64mut0b6VsKEA==,type:str]
sops:
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxRTUwVG1sRGdjM1JBaFFv
            YmtRdnNRaWlzVjlsVy9BMHNQaVQwbzlJK0dRCnJ3V3FQc3ZSQ0tjMGw0TzFqV1l4
            WEtUVTQwcys2eDA4elZSeXZpY2NJb1EKLS0tIDhHb29OVEQyTTV4S0NkWkxjTlkz
            U3ZQT0h5MEt3QVB1NnRDUDBHVE04MDAKyyARf+eYxdiu9jirOyUFOBK9/6Zowvh5
            2+1vhJF0qe5xsugFC+iKBhHJzZgQC1lXd0xwfSauZi1vJ43NnI9gZg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpN2huNEw1YzNLN1dyN2lX
            b1lMbElWR1MrSkF1czJNbTBSQlBLdW1KNHdJClQrK29nQ1RIc1BCUVVvbFNVUU5M
            Y3JBU0VTS2E4T25qRFArNEpCMFBWUm8KLS0tIHpES2NLcXVyQzFUM05UTEs1aHR6
            N1NFb1doa1kxZ2ZLZ0ZYVG9UZzlROWsKospKFdxiopnszcjXgsPldqbvq9g10EVD
            hKUfz5196GaRxZ7QgrrmIlX6SVNagR/l0jOzL1NZuhjQjFUS4w1jww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-21T16:59:52Z"
    mac: ENC[AES256_GCM,data:9aegRJNdwEykOdHA+HTy90ofVy/56jmdMS0QdtoGwLTn5X7CtQ8MSEfSlqS7DdMb1rl922QLnNSctIC3BO5BrCJ76Oygwlj8OsttlxWw/zQJ9OCtBO+8ZwqgEEd0ySaAMYUqMC7nSrCQUx/E3RE0JBZgZW2A7S2+yXP/E2jn6rM=,iv:MF+ep5sqj6P1AEiFRxsjDUWCXFYpAaRMaGh7mEe80Hc=,tag:TmK0q25/9YsxZvl2ksygZw==,type:str]
    pgp:
        - created_at: "2026-08-21T16:59:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0IKwDTH3WibARAAh4ffxUDeMSKkRjSAWwHYWEH618n1odOEYhkmgcZsG1V8
            C1oh+4ddBs405/Q+UbtmbzN7wSplIQ/8Yy4I8xttQ0AGDWoCUMynrw8QHZLPLxWp
            CP5cpE/QX8lFzTMd5BswIlYxqGrzfvFWc4B9W/T3bNnP621C0CRwS7aS+JYBOR9f
            aopO023FhbqyFv4rHQd2ZVV8hlv0h8vjOhsLMau3Crar63nvAV9hPC2jN+CjUzps
            UvwUhkD/FupIXJgwyS9F+OPQpx3lHcTK1z9jKm4QgaAmbLV/0XTjrxAsbX6MRAUO
            HV8sF/aID1IskvcU/6vcHJPyoJcRwkOj5w2vecBa//cHIKi1Q345hqNvvteH47nW
            0ffR190Ea99chjz7agyUJNQ8633QKIUcS0HWTM+Yz6wTS4c19v+cVT1ZI3nPBbG6
            ZkhZ/uPC3TJyKKoXUYmvq7NDh+uothVqcAjXwwQi/NYqd25vxN9n39gmOfKPpxwO
            rO59wttWS2xv4zX8kx1g4UkrTdeJzQL0EGLVBALD12QQOiNO3u8ymcOZwt8EcgaK
            k7po6pkxztg/2FLP0CCqQ0nzxagV4dk9cZi9Wnu3tYFe1e8/Eg0FL/5bDt/l15XR
            A6eO9db/LmR1STNHETjbzLdyPGG6ghygM5ItfweEnp1FLqhQotByyc+5teoSA+nS
            XAF7p6RBRlNup9d49BZJDAxm+Cb4Bj21K3w9w3A/DRbjrbxWTPnvPYHt56JThLIQ
            LsbTQmRUdzh8ukfQCOLwXBMsmrRwb5bAK3Je//GyWdm/i5TfAd2sSdPhAanm
            =EhNf
            -----END PGP MESSAGE-----
          fp: 03746612698994281D322B09923BC5E9B4E9509B
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
