apiVersion: v1
kind: Secret
metadata:
    name: headlamp-oauth2-proxy-secrets
    namespace: headlamp
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:xpzpwA9Y7as=,iv:OobjuEfh0KoUk46s166fQH2qSxMIv7MijZ/9zAXGJQU=,tag:TWidhssJgaSnWhrtqrdWmQ==,type:str]
    client-secret: ENC[AES256_GCM,data:e/vDzkzXHC6obBlqsoUmcvzowKzstur4kHw2BHbGcgblp7gXCq8LdB/1qaPnicd7UJpv0ufSHGOWMhj6m+ladg==,iv:TVELFitAQXddY1T+VslyB/tk7qUCPZRfeXJD5s75CEU=,tag:hGcXxf8cu9l9G3r3IcjgDw==,type:str]
    cookie-secret: ENC[AES256_GCM,data:F/jT1OCPWRQFlDrPIlwZd39ozZDSjqt66+hsBIPtBItfAvDrDQzt2nqvMQ==,iv://y1BCd2A+rgblDwZhIhBtM4wwWHV7b/vi4OLc6a4Xg=,tag:pMoKkQdkIXDcxGodw8669Q==,type:str]
sops:
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHUEpiUHNyQnhpdDBUL2t3
            UGFIUE9oYUUrYkR0Wit4ajg5SXVlNmhyeEgwCnlqSnBRNXJveEFMcllWTjVUaDYw
            WlFqdzdEVThxcXFkbHpscEFxWnYzWkEKLS0tIE4rNG5UcDhrT1I3dWVwajJiR3dk
            TWVsME84eXN4SnRrTVBEaDZhODVaSVUKUvzjaheGj1/JglzaxqLZaZyMtVv4kjy1
            GOWtsVoeuKaiAEkErNVLuNxD3oYOJ1UEM9xPcZkuqttUnZlNpkTuww==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3QUNIbFF1ODAxYUJNdC9H
            bDJKeUlaVGdnVW1qMkg4eEpwWVNZWHh0L0VJClZMME1qYXlUdDRsbEhVaTJScmtZ
            ZGFBbUJ1ZHlkK2swYTcrMHFubi9vYTQKLS0tIHhRVmxoVFMwNGF6ZmJ3NGlOYUJV
            VXVUeE8vSW9jelpIRE43RDNGOFA2cUUKTxZGoXhIym3n+g6L6SpXFCzT4XtjxdXj
            pQlXdO5IRZXyk0fsnG0WZHitdpydj3V6ssmmJKJVwiZLwgnAkKQpjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-26T14:48:05Z"
    mac: ENC[AES256_GCM,data:4MmUUWED9gkW+2abdthpmFOjY/dLwu6IcvKv2kqAh1TQm7H8M/3B6maIEy++XNecyd4TRsmQcmZxIkYoadP1h+Kv9PIJXL8X8LULsixqw+VxYzFu9iDg90cWFtfaNrw4epGPMmtrJuYsdEEvIOFUKwZvv+3H5yBfgTaspKjYnOk=,iv:gkvx/jBlfEFmNHplrKpBlinZrxhCKwhiPvtYNEPK5w4=,tag:1RuaO4KXR/KqRoR9iRKy7A==,type:str]
    pgp:
        - created_at: "2026-07-12T20:03:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0IKwDTH3WibAQ/9FG5r75AIFhjeHQHZ++zAp4iUOBcBNBnXVHwzDjAiv1BG
            ICQOqPGk+qp7ivayeXcbeU74TRxp8Ao+pZQHNRrtn+AFS5YbX+a+D9Ywjq/dGdNo
            Cv1eSmAfguZVQpZf63XBBe4Ic+9fM7wLilQNiPwX5ST3AjXSsEKKv/mtxC3xRPYP
            iqtveSTO6+8xKo50VhpNnKxfYE7k/BV8aplHDhWIasThq8r55jdcKDmVQ13X9JKC
            STgagw4uHqH3+OAwsIl8+DM1hqHnTavvxZHC2Hi6gdyqNtFplpedwNlSxXjBiNqO
            ljVoN7zCO6+TC7o0EUEPySlOBnR3fmPcWAxDCFZZxHL2NdTkywh188EeIfhXnVxO
            eeIz+dyabezYJqzU2L1sm/3ymsiecN2qT1so8nqHWemmb/diisl+OK3bDyFpGXIJ
            D73ztWBNJXAQOYGeFMbM/qGWQMjeVu5veKWXkp25+0hzpGOj/34JC2cKjhIxDkPF
            3EiDybGLvf//hGe/yC3KW87docdyFS22uAoRpwfRPa94AP5W1F2MfQb5rGKeUIbM
            ffbIR0QAKwQx1X/0zD/xcoQ10peQaMzq5Ze90QDRLNWWbv96UHi0c9TXMlX+6xwZ
            K0uxZc0QVwtCx9nQuQdEvPbHI3Rwy9h/7OIVBGxk8p6D9Ot5/yxmOq6KqFGncwzS
            XgGJUnz7pfCVRdd97/dbykxTzuxL4O0LSee6MmC6pZ6MBLTCiLlZsEsb5mtQqjoS
            uJaxeSdNjMOFh1rIGY872SmgxqEX+HykiroWYNqVyghkfTC2xIGMWR2mGo491GI=
            =5Q8D
            -----END PGP MESSAGE-----
          fp: 03746612698994281D322B09923BC5E9B4E9509B
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
