apiVersion: legacy.k8s.keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: client-secret
  labels:
    app: external-sso
spec:
  realmSelector:
    matchLabels:
      app: external-sso
  roles:
    - name: some-client-role
  client:
    clientId: terraform
    secret: client-secret
    clientAuthenticatorType: client-secret
    protocol: openid-connect
    standardFlowEnabled: false
    directAccessGrantsEnabled: false
    serviceAccountsEnabled: true
