apiVersion: v1
kind: Secret
metadata:
  name: repo-envoyproxy-oci
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: envoyproxy
  url: registry-1.docker.io/envoyproxy
  type: helm
  enableOCI: "true"
