apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - argocd-oci-repo.yaml
  - argo-app.yaml
  - envoyproxy.yaml
  - gateway-class.yaml
  - gateway.yaml
  - https-redirect.yaml
  - reference-grant.yaml
