apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secrets.enc.yaml
  - database.yaml
  - pvcs.yaml
  - valkey.yaml
  - httproute.yaml
  - oidc-config.yaml
  - argo-app.yaml
