apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: harbor-secrets
    namespace: harbor
spec:
    secretTemplates:
        - name: harbor-admin
          stringData:
            HARBOR_ADMIN_PASSWORD: ENC[AES256_GCM,data:b/yy96K3i9+WjqtCPuPjhFYF0C6w+/kSNvXshdAWDBI=,iv:ZxjDSW4M9KI4peTW66vTRJdsUujtF+wdD+ui9o6q5ps=,tag:vPP5Qb3THa4uqbIYiqryhQ==,type:str]
        - name: harbor-core
          stringData:
            secret: ENC[AES256_GCM,data:6HDPcV5dGescDJ4xRGNTTw==,iv:vqDrHolf8F12J/Y2dmi1A2pwvg5knCOqSwwJaXTSg2Q=,tag:/drGMV9wPdp3J1brIlEZIw==,type:str]
            CSRF_KEY: ENC[AES256_GCM,data:jl5ohN+3QU/bIWho9CE4wek7+yx/7b3IxTqc7QCQHWw=,iv:gRayT/DQa1B3HNisI+8umFRnddvhuPMJXgWaMBkREqw=,tag:9O2tizeomwMZj6I96e5wxw==,type:str]
        - name: harbor-jobservice
          stringData:
            JOBSERVICE_SECRET: ENC[AES256_GCM,data:mpmtRHiXJmO+DnRk+Yhohw==,iv:n1qLg4tRR3HoFdKf12HunZWAZVLfd6bo4VbdP6Xbo0Y=,tag:Gdn9YrcHl7P5Ta5xnY+RYg==,type:str]
        - name: harbor-registry
          stringData:
            REGISTRY_HTTP_SECRET: ENC[AES256_GCM,data:/iDNtp/tcr/U06IIxw3axw==,iv:Pvocvye1jQoA3bC/K+HAqfsPROmB/oPp58+mYxc5FQI=,tag:C5C9jmN6QTwWCcOpzey9Kw==,type:str]
            REGISTRY_PASSWD: ENC[AES256_GCM,data:eXpNDgeyx8VMk5tnEujlS0Fl4+Ra7BTN,iv:NpltYanUkNZKGa16jLGWWnoBDhtzK38A83KGSIkKHPQ=,tag:DKvmwGLL0fuczP386/PqnA==,type:str]
            REGISTRY_HTPASSWD: ENC[AES256_GCM,data:jksRxEdjeSXRcMOv9H5yJtgWoPjGCdnEjadLUg2S1YZh+QyJNSIvJrg8FHu9UgoqclMTHLCd1qwen+6KLrY3rfKVL+RD5LjD34Bip1wzFbTH,iv:OoB5y4yhDNsiA5HmuSgSN2jHFRMcQQm3dmbSAReyLCc=,tag:YOxbGR+BdGa/Vg8N/RqunQ==,type:str]
        - name: harbor-encryption
          stringData:
            secretKey: ENC[AES256_GCM,data:Dw1oCud9pTIWvZLFQXZ6Qw==,iv:K1WvouA04LUCnAcorhLHwXod8j4qdN2HsBesfGez1B4=,tag:5n6Bx98dhaoTLf83CCbYfw==,type:str]
        - name: harbor-oidc
          stringData:
            key: ENC[AES256_GCM,data:pomNyKcO,iv:EiPmJ6J9/+fys12605g0WwSCFez/2m6vh9df8T1fnMk=,tag:VFy6+8aCLSzY0AYe9fdRgg==,type:str]
            secret: ENC[AES256_GCM,data:aj0a6TSxJ5U4nXp3PhCWxkxsTeNtBuzXfABhcjRHwLrP+MIwTW6KrZAbKPvnUjKT,iv:rG9xkaDmryiw1TA3Hy5kk4kFjoMXuZOpgHXMMFDHPc4=,tag:N88zaFEMPAQZrgKRfQJozA==,type:str]
sops:
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4cnJyL0g4QlpvcmQwRFUx
            aVZhR3ZPZjRhdjBkRDA2bkdNR3FlVzl5aFFjCjltSklST3FSZmVQVUJyRTc1VGZR
            b29hdFk1Vng0Z2Y3SHdMUXlBTkhyR1UKLS0tIDVIZHZKZm43K0FhS3N6Tkx2Qklr
            cTUzVDVoRFRFMXVkMEk1SWk1MzRJYkkKEWxTEoIPo23AroLIDti61Pe8jtzBXIMb
            Xl9f8yzanpF7NYUSF/Wfqls3Bg8djdoO98irYll0F6m1KfZ1stwbJg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gzf883y8p0wfy5yjn5l3l2axnqxdgtw2zdcp8jqsrk65m7gf6y6qzgkf63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZlUzZkpSamsrWTByWW1Z
            Mm40U1pQdVQyMkR5OVBydzl5eEtOY0oxT1RFClBLZ2JpNlgwbk50dmdsckNtL2Zx
            TjQwK3pGaUpLYmt1UFF6UDc1Y2ZhZTQKLS0tIFlFV0x6TnRNSjZQSTVWenpzN3cv
            MlIxVnJJejVpOG5pTzhFNmsvbjc1S00KQ0+/1hrpgeiXgYbR99GYwgYCiHKz0/8F
            YRR+ZxuOoxKQ/xrukx3FsR+zMeX0GcOa1mOXdBLO7F0Fsxdx5khGyQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQeWVXMzl6eC9ZLzRkUmRR
            NWFJYmRLNlZIcThvbW5PQk0wVTAweEliMlJRCjZpZGlTejlPejI1aUNZdUkrYzRq
            eFRPRktXcmJLQzJrUW1KanZhOWZTaGsKLS0tIERwNk9yTUUwcHV5eTFJL3pNL3V3
            K2lrazJXemwvbzVzTGxKVE43cWJ6RVEKECPiPR2OFOIpmz1UuNxmfdR1ZHMBio4U
            D0QGrpAAQg6a3XTHxowUc1Tm1BJcbvp0z86aORAPxFTkAoVjFlW7NQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-01T22:54:48Z"
    mac: ENC[AES256_GCM,data:Onr5plhkiuody4PHY7mHUgEVKsfSNdwhuARCar9n8PurBWNTuo2Nh5Diu8fF+6uIxB490DnFdKRadOhgioSAODJSz4OKd4i4rJnxSMFa3F/OB9FV/2WDbbv1OURn2kcX1P3qt4Ea7YUzDFXJgWp3bpgoZYDgH85kPbOj9dJtDE4=,iv:LQPiJGvGnQVdupKYQHmD9W+q9ufHZTb3w9HrIBfMYWg=,tag:Qb+0Z4+r9+zJHF3uQ1HRDg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
