apiVersion: v1
kind: Secret
metadata:
    name: renovate-env
    namespace: renovate
type: Opaque
stringData:
    GITHUB_COM_TOKEN: ENC[AES256_GCM,data:Z/b6NYmE6LVl,iv:q6lk30zHFxrmAUIQ0dFfgFhnwJRoXhgS/EDGCzIfnJs=,tag:0K0ue5rX1y6CVbODbK+nYg==,type:str]
sops:
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWEc4cVdiS2VSTnJLdUcw
            ZWpsTU1GdlUxbTRpaW8wTmNWNWxyczVYU2x3CnhsYVpQL3A1b280aEQvcG52SjB2
            c1dCMjNoLzQxSUw5L0RxNlo5OUZWa0EKLS0tIEpma0k0VWpqM2ZqS3M0RW5ETXBC
            RlY1Qys5bzQ5ZGovM3lFZEZDSU9JRGMKchCgbpCkKbd9Qx0ZuxOFmMBWm1TEpglM
            XNHZOlnylYwdhTDXYpr4GhqdoO7s6ng78fYymree3xh8980Cras5jg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gzf883y8p0wfy5yjn5l3l2axnqxdgtw2zdcp8jqsrk65m7gf6y6qzgkf63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRXJBYUdLTHA2Z0YvWVQr
            NFMrdzVVRzFGY3FXZDlaVzh5ME1LM295dFRzCmt4S2xsUXFXNXdCMG4vQjAxY1Jp
            TTBiOG1qd0t0TzRjakk0TEhyS3hsWm8KLS0tIElkbzQ1YmF6aFg3YWdWTVFIQ2li
            UGJnd1BGZW9tUDY5UEFCNGp1VWc1UjAKuPfd7T7jAaaOrE8YLFI4yeCvukNBu7xc
            32WQuztTZWpgo4SNvhtDsvXa11NpVKx2Z2sHD3oIOLvyypfAJQHdAQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoV2NjSUp5TS90V1RXQVNJ
            SkhNckM5TTh0RGVPWTZGLy93aG45Z0xaQWg0ClRERnVzZW5TeS9TdlZYcnpLdzNk
            M0sxSzg4cFBGeDFtL1hqZ3Q1NTNETU0KLS0tIDU3aGtzMkd5NWt3eEFHTTJnUDZa
            Q2FFRTFiS2hFc05qMDVaa2pzdGNLR0UKARFDBwAg+k0/xY50h5xzh5OUPDPmxFqy
            5R4R37K8Ax0WcdRFgUnVSO7jloPu7o3wx7y1LbcVCli/kokjhlfikQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-07T08:36:30Z"
    mac: ENC[AES256_GCM,data:mC3kaLyGcqL7ZhA1P1rfIndZaOYjkgWity7u5BoEsNrRcCPjWJkyvNoe9VM9/7mqZYGO7yjfOzsZXycwW4KgQ0B7n51N+ee3VktRfpPwtfvhbr+2BrXZeyrdcWC8ZFxGiqEQIe6EjRyWljehChYsakQwK1MEWXOHjwleQ/bBFfk=,iv:69TaOh2dlE9wFXXE9dHOtRBXW+aPrylO6E8TJlyrAoo=,tag:rjhIfNxlR99ImmqlXsvOOw==,type:str]
    pgp:
        - created_at: "2026-07-07T08:36:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0IKwDTH3WibAQ//URDlKay9joKGIXOuM5UpJtj4KFRzPOE2rWjBQ3VmE4P3
            FIHx3RxHWqoWtUznPD7tUYHjQ2KcAY1uVZqHUv7OnTGzs/bD5W0hjfAY7O/0Ylg4
            HkfuFszYSjSoGy9KNKpjz57j5kqQDuxofdn2skyr41tVHqT4RMs+dSMSi8JjQ1w0
            8g6Up+ySY+dDsMATqsMrH50YFUk5f0AxUZgaUL9by8ROQZEgVBuXdjnNyGUitHgR
            Aa+R/cBxtH/HMYMuu+YTsBOovvZN91DAOOhWcQsIdVd3W1fqxr51swI6vfagWZxS
            EZaKBH2nmp7nBBLmV+D6nzbSNSgEhguIuP5c2sPuTt9a9PIql2ba87tz+TDsdykx
            XOwZpuUyKe3aXxn3ZbGjgWSCtIAsVIg/HoWkMlrnlKbinDe0miQVAIGa3iWVP5eN
            Mo9pHEh9cCDewudmFz0KElupJPGA3cM6YQurLvnYA8ayCc7hSvmV7mrc+yaJC5Yn
            Yn5+gK1zfB0mWIOj+MqbyQxxo8IoYmnrYvtjzm/MDgBl+C6tnOm3hTGzeU0JRlUm
            21cZ/V7SiyHR1egNozIts7s1gFWDJ5SqII3dFBVbcswEZr6sCX/fVMXYChABe8GY
            wgBYFXsqLCgchvJo/EbOwBUkiVU6nPw9tAB/Qks4VuK566sLwlD5lhsrpUvUbsvS
            XgHFWoY13I7m0/8whpOvx9Wy6EGyK0oB2e/8EcI8QMB1EdnEYkibixP6A5EoSxMB
            iyhjTuTCCD/yuH2uWNYyg2F1Z+Ms3hbtsWKmS2A1iPSomjLaYehIbtXMgoaDI6Q=
            =Hm6a
            -----END PGP MESSAGE-----
          fp: 03746612698994281D322B09923BC5E9B4E9509B
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
