apiVersion: v1
kind: Secret
metadata:
    name: renovate-env
    namespace: renovate
type: Opaque
stringData:
    GITHUB_COM_TOKEN: ENC[AES256_GCM,data:Z/b6NYmE6LVl,iv:q6lk30zHFxrmAUIQ0dFfgFhnwJRoXhgS/EDGCzIfnJs=,tag:0K0ue5rX1y6CVbODbK+nYg==,type:str]
sops:
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSVphNWdDQTJ2V1VGMEdh
            c25VNGFyU2N1N3A3UWlid0hHejM4c2hSR2tJCjhncTEyd25kQjRUV0M2citTc1Zq
            bDFCcUl4akNaTFNjUDFkZ1VpQU1XZk0KLS0tIGZmbnMvMnZMejJhUTdRWVNqUVlC
            RWpacEo5UW0xSUZUK2g2N2VBRElXMFEKdIMaGbdd5s8N11B7nMdUlPiJWl03bYQa
            +f7GHZAHnQBK9ujT21AiZzrtUwDuCJzwGuyZZkvbB/C7kSH5/nM4cw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjNHdsQ2VyTmZKbmF4Njhj
            QjFnSVRlQ2dRbGdSTi8zOWNHR2pxZUxpU2pjCmo2ZUVQeEkybVhlYXIxQVZvN2xY
            dUxtY1JSL0tJaFowWjdOWEl6QzZaRW8KLS0tIHVVMXBBT2MrTnVhWjZBdWkyYmNt
            dit1TjNuckU4T1cveER2NXBYNHhVY0EKS+TWwE4jFkv3eTmFYUJVnTbqhMvQi7IR
            JKJPx26haal2vlbGGQF2fAzQJIuJaOQQaP9SjKDAxLukkT6/C1a10g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-07T08:36:30Z"
    mac: ENC[AES256_GCM,data:mC3kaLyGcqL7ZhA1P1rfIndZaOYjkgWity7u5BoEsNrRcCPjWJkyvNoe9VM9/7mqZYGO7yjfOzsZXycwW4KgQ0B7n51N+ee3VktRfpPwtfvhbr+2BrXZeyrdcWC8ZFxGiqEQIe6EjRyWljehChYsakQwK1MEWXOHjwleQ/bBFfk=,iv:69TaOh2dlE9wFXXE9dHOtRBXW+aPrylO6E8TJlyrAoo=,tag:rjhIfNxlR99ImmqlXsvOOw==,type:str]
    pgp:
        - created_at: "2026-07-12T20:03:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0IKwDTH3WibARAAkdHI9zioTcAP0I/u4iI4GoqF59u6U8mZSae6pooQO8Wg
            SeeHTYmnqRhsMaa1txEVyx3AJEnbPBUb4HHtG/MYawgJrt01SSpkAXWCXHLAaWnK
            kPjTZwRLixUIKTnpwUoP8m+Mn6OWu9X75eu0xz6shVYcV/RtK2x8DJaXPXjCVS8N
            Gwns25fhc/HeATBEuqmykrSQ/OO1B1ju7+VLiT41bHdz2Al9lgR9Efbg7gBmU7TD
            KxIwB2YTkQLvSCx+nFzqqHebK8iVXZeKI/xweTQBuPdaV7eixTybilTGsRgmHq8t
            zyVqPVQfNTcq+ECrsPG9KpkrTQanfYviDUxtxQPD1YGkwSrXSafGP0WdFBDQP4Ku
            +8UVZpTJP9kZkrdqnYBG7+1Kcsm4v+ZCLK2zSKQIY91n17HclHLD512i225sosvj
            +n1N25Ue3XmJNjA0PCuJgdubuBLKFxRpZfnYD+cDjCJpkizPg/h2kO3WX1vigvem
            +ajXYa890Yp1S/1Vz5fE83wXFR4J0beUoj6L/MxvA/6K0t8p3fieRfRun3RL489P
            mr4xci/Kdksi+JHDVonCJS7KfuJmngwbgHrN+8yG5ukIZ8UDCE/byrQPyZcTVsEo
            90CFof+5ekHY5DJfojFuuSvxw1c5eP/QELUTE8os8i42htinlH14B5O5V6ts653S
            XgEDyG+6ERDkbZEWruNdO0prrPdiHz37JGfEsKQw/CmSQlNo9O1f2ncHcb1GwQPv
            A9BqR1CAq4vhNftA/quPUVXusioY6Y8bcPN4Egof9p2DwY4K5PTuUi6YLRJTHig=
            =OA05
            -----END PGP MESSAGE-----
          fp: 03746612698994281D322B09923BC5E9B4E9509B
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
