apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: renovate-secrets
    namespace: renovate
spec:
    secretTemplates:
        - name: renovate-env
          stringData:
            GITHUB_COM_TOKEN: ENC[AES256_GCM,data:r/riWdLrwE94,iv:UQSq1GcsbhJMF8qRL6kPENH0m+CTLegLFjw5jDUB4j4=,tag:HQTnnC5xB1/az83uD43cSA==,type:str]
sops:
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmT2V3aFVSOWcrdzlJQkJm
            RjNWRXFzZlIzK1AvTzBUOEk2dmdlaU5mcFNNCitNRDhnQmc1YTlDc0VRRFlHQXVF
            Q1Y0YnJlWld4ZHVESEtxSFZKRGZ1dGMKLS0tIFZPbHhUUHNQeWVGZ3A3SE95QWQ4
            UlpoYm9mTWxNZkhBT3N5RVZxSkJna3cKorLeW5lJgc7i0Gn2BxoMrW5B6LD2BOjJ
            Sj3jddyAvKubeNCdQ/5AHD9exl5xd2G/w+X2OkSbCQOHeW71dDTlsQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyR2xZQzRxbEhoTE4waGU2
            R2E1ZzFwWGdsYVgrREJvdk05QzUzMkV3QkY4CiswajF3cTNDdlhTdmVlYzN4MXZT
            T3prOHdibDFNejlpczViNkZlWFF0SlEKLS0tIEtuNjB5WVVKWUFIQTRLd3ZQeEZK
            TDRXNjBkQUhwciszajhBaG50VDN6Q1kKo5+juwcZauR3NmDeaoOLJj7hO6j/yIO1
            UDjm50T1welOn/BfKJ8sIFVxiDnNcg+EQpxyuIkRXuJVfvjCqjqttg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-21T16:59:52Z"
    mac: ENC[AES256_GCM,data:1B3tZzfKEoG+sn5e55lXnNeMambVQ3ffneNfCqScbybkAxBfpAy7fiA4j/0Y7LUVvliyEpA45ohjJiLELv1i509GBhMveC+9iNJFv4JNHzCQ7eMgTg4J13yX/4qZ1M4IHMK5tNP4MuQFfy9octTLy5cB4oPfsDa1U/RFyBzayGU=,iv:ZxPa3EOk5YHN1LHJtL+aNmm8X+npuKgb+ASL5sCn3fI=,tag:V2HtsN5fffAjh/0maWh8bg==,type:str]
    pgp:
        - created_at: "2026-08-21T16:59:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0IKwDTH3WibAQ//fHqjLNpRUaTxnhFmN9S+wVbngAiq8Dr0FJlbP4vBmF3L
            2el+ScR3xLsMjaLWNcWekJNPgmGmQmpXEEuTKCgmbRciszr9b8gRn5Q3FmnbJkX5
            7CBmI0EmBXmubwTJSe2JzAKZUEhJymHfnDnhQH49g27YN1R1ztt4aIWR40+GAFNu
            NT4q+J6q5rCRzT9AqBZOAKbWapodYLg4DCq54psRocX1CYd3EQG9yOrVaW+t7x92
            M/OS83H9h4lBdJs/PIAGuY/JxUEx3LkYAjQAWV2RVvkAvBV0xjc4UF23FY92tndP
            GqHsQYekUFUQT/FlkOzzr+P4jaW8J4QRdg/4LOx0nMF/6zShcIHN0/k7WRFuIuaE
            33gzRa6Q2YG49XeqjSccnv4LS+bYLMJ9dRWjyK2yhgxDASP/KGHuKUPPWxkxCS2n
            yZvLBqoqJVkD3V7GgUJuRgPZGjvpz60H/0ONug76dt4UqFEG6993ATE5L48ByO2U
            l7F6keQDd7yqxNu4qnbo6RHbteG1soEYlEJuQ/d79hM37lXm8sUUXlKltYdleuBG
            g/ZdGNJpBfr2ECXupGfksv3sQ8WXuhW42i2RVOYH/8HqAYJl+VqWwItm2FtL0thC
            CtQFrXW4A2Do1I1jUsC/PL+RnOEPLt2/OpGRFbhRxA+/ukjScOULMBmh22FZLjLS
            XAFXZ9ToBDo/OXU1IunBGHFBZnXDiH7rAvqPBSfeBajRpXYHb9zoIcOUPDLabUtP
            KHjXyilGN4AhmwoTQSkBa7qScJr9tf60377whUk26mFvhR6rcTtQeKTiwsLO
            =YmfS
            -----END PGP MESSAGE-----
          fp: 03746612698994281D322B09923BC5E9B4E9509B
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
