apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc.yaml
  - node-config.yaml
  - deployment.yaml
  - service.yaml
  - explorer-config.yaml
  - explorer-caddy.yaml
  - explorer.yaml
  - httproute.yaml

images:
  - name: alpine
    newTag: "3.24"
  - name: fredix/radicle-node
    newTag: "1.6.1"
  - name: fredix/radicle-httpd
    newTag: "0.23.0"
  - name: node
    newTag: "24-bookworm"
  - name: caddy
    newTag: "2-alpine"
