apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radicle-home
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
