apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvcs.yaml
  - deployment.yaml
  - services.yaml
  - httproute-knot.yaml
  - httproute-did.yaml
  - tcproute-ssh.yaml

configMapGenerator:
  - name: tangled-did-web
    namespace: tangled
    files:
      - did.json

generatorOptions:
  disableNameSuffixHash: true
