apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://argocd.tibor.host
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: $github.clientID
          clientSecret: $github.clientSecret
  repositories: |
    - type: git
      url: https://github.com/tiborpilz/infra
