apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tangled-spindle
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: platform
  source:
    path: applications/tangled/spindle
    repoURL: https://github.com/tiborpilz/infrastructure
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: tangled
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=false
