apiVersion: ENC[AES256_GCM,data:i60=,iv:lbeNmyP08Aym0X9kP3+BY+Iad7s0k2ebBk64tNzIWGg=,tag:MbugcokmftTNLk3RPN22nA==,type:str]
kind: ENC[AES256_GCM,data:D5LYmQ7L,iv:03pbPAh4RI0A4aVVB2ekmWp5yt4Ln9hkW+Qqcv/aWFs=,tag:sdakZDFuskXDLr8ZH0+vjQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:bbMO/TOVbFg5RPrfDefLWMLPcVk=,iv:+xiLS1Zr/jnBSYmqCMIi1N7xP4z/oV7HvSrwN5XsUGM=,tag:o62GAoXKeYVhkLV8ZeZvuw==,type:str]
    namespace: ENC[AES256_GCM,data:6XFMI+hOrMgotK4=,iv:wuDtwJyPlHzKczlf6akk915CY6r0CA4M8XpRCcrDdqw=,tag:u+l14GX2uf4kIG9XlJxTBg==,type:str]
type: ENC[AES256_GCM,data:f23lKGKB,iv:qnJBszaQs5stU7b4jDZQgp2e/6rQLquESgyNrVJMqL4=,tag:sZIkcfEBz8iTgtHaVGnXmA==,type:str]
data:
    client-id: ENC[AES256_GCM,data:zbn9CFT2B5Y=,iv:2/7LOCveGs1SlreMi++a0mEpKLcl0NgNM/60UoMx710=,tag:UaHMtoeM62ro4poVzOYHDw==,type:str]
    client-secret: ENC[AES256_GCM,data:3x6H7HnmGGxLsB98bZ/d9GpBDQuem8xkbmrsCiJA5jHg6wDOUFU01HUfl0ERn8jToFQzPBmXXEf12GcpPXZyyNl+bvIerT4ptu4ezYi22/0w+RAY2i2LJg==,iv:XydshwSwOBlUdCsIfIJL/w0COdRccjkCW5cuaerQhQI=,tag:cnj9h2jiWci1IxDCm3vuDA==,type:str]
    cookie-secret: ENC[AES256_GCM,data:jATGhT58VEC4kzkSWUuco6T2n9R5MFqb9aELfq2ab0YPq6EmIsvOR4B5uYGvu0hUQqFxWIUmvcm3lAB2,iv:hVnNi5n7PpX/8NSZUsvUb4oVdu6nnOWH5TCOL1qSaqs=,tag:td5mWu69KlBhggu0htfGqw==,type:str]
sops:
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUForTjJGS0JNOU5Tc0k5
            dDZlNzBLZzk3Q0grY3hKZVJxQ1NmaWc4Q3hnCldyNjFtckxXUDByTzRlc1pHWFI1
            QVNxMkxRUkRndWV1K2NST1YwOXJ6RmMKLS0tIGJuY01IVUl3WTdIcHlTT1dZQlhh
            aHRXUjYvMnE5eXoyWitjMkRPNjJjSHMKKI2o9E9fj6FpTEkCHeEfbO1b9BECEHZs
            f+ot7dBaXDQt5SrOPa2Pev/fcohK7WE/Mju9CvCTe78tHy0qEad+ww==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gzf883y8p0wfy5yjn5l3l2axnqxdgtw2zdcp8jqsrk65m7gf6y6qzgkf63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cTVNbk85eWFuT3JqTHVj
            cFY5dGpUR2tranB2RzNOZHBUWXZ5Lzhjank4Cll6bjBjZkxrVlEwV2J0TjhoczNQ
            NEFCR1Bkdmdrc2ZoYzJxZzFwWEkyZlEKLS0tIHRLclJuYVlTTWlUOWpSSlowdVVZ
            TzI2bjdQb3dwUlFnTEp0R0ExNEpaWjAKS1VaCv5f+Kr2Je3Mq1X5HQSFafqPSORN
            mejgBOtZIj4fKn4GC/C/k9SC8zhtTOrCMQJh7xkaZKXD3wLgCqW0OA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZUhxc2x4ZWsvOWtYbGVv
            NkM5S251V1ozWEhSTFlxNEMxbW5MOUtmcERrClVqdnNvMHpxcmNPODlzamVJWjBX
            RXp4MXcxaGxEeTdVTENDamFZeUdkejQKLS0tIDB3R0pVTnY4cmxlYzBlTllGQ2g1
            U1hiK2RlYm0wMVE3VTBPK3U0eHNYYW8KRQPGhnUu0/19MUDeM2cstUUlQc391EGc
            /wLmVQ9/xFHoT7BcfTaemjPHN6DzWfy077RyJWRP3ptOHvkEUWUONg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-13T12:00:52Z"
    mac: ENC[AES256_GCM,data:vYvPZKq6yPxqDP6LFBTy8sDlAftq6YaBroJw1E/ISHvJGt8Pfbaudifow23PNogvAB5qP4o9U1HY8Uug1gk2LjKGZlQajUboOMoy6uMffFZpnHh0353eAAC3M/1QSj0/XXOEgqE/kRlMOqBFzfgzrHi+cAD/dinYA1ooX1xabdI=,iv:3MIi6qimvdQixbhSPM4I2W9ObVFLlXV83Lpac945Lf8=,tag:LNei8DxdALpc2tpN2ZiIMw==,type:str]
    pgp:
        - created_at: "2026-06-13T12:00:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0IKwDTH3WibAQ//aLzgMeVrnIDNVzcg32xG8vsA0LmTa0HTNTKSC0Ezjk6H
            to3HauQFBdwUGNTdAoHZtcqTS39ATjpGF5I/taaFNB7E3mK5F5j3x29dpOQ5DqaG
            8+edSy+Dx+sEuNTc5eUhTefNeoG/K2OMb9+UDeZ2GyN922ldmHwyPTjyMXJylWRs
            blKWMu3MrHD0oGUoztwqIQLy7HYYn5paKhdLwWt1AR7vHVTjcbibe+zo/9ZBUhDN
            /+kKt38ZYosEA1hcrPKWnwW607l1pLpYGPbZ1O3famp6QdC8Pu2GxzfTmLeeTzyG
            KTzmCXKhJYL8ZK/jBQ9VIexpjt+dJn2oretCxduI2IpEntohH90tehYY4Iwi7xbo
            Kb2dQtb6E4qHHkm77TRC76I07OB2uL8ObwAmEGZI99JPShTA/T9e3+62ybyq08S0
            LFDCI7Rd5nrXHQr5tB/j+pXj6TIzkMJq/bPrHYhh/9TNv0RiD2jS2EjpMTsmgOla
            /IXsF6TKylfTvJ0oMoSqcTr7jXmOAXpaTKRCqv55WcG3i5wBxPnO5qottBLfxJYw
            VrZH/MAR2pFYGnuEMylRnY/UZmF+KzkhGU32wqfQ8fTnPgdd1cYUxr7NhhobTuPm
            MsD37yhIhXUf4ufdqRTzTSjnkOhfgKYfJzWqoyyutzL5epd155qU0972My4RTkDS
            XgFMGwHYFCi9Kvz7eWZwvVxZFTidi+zIkGFGJYIsq0SeZqCImemacR5GeOj/5FT6
            7bPOHlZk+YycZpmiqMerfpKZJbr0SGgmiG6fk0Cw2HplTAS8ZafxM19uBD+MVo4=
            =lsz5
            -----END PGP MESSAGE-----
          fp: 03746612698994281D322B09923BC5E9B4E9509B
    unencrypted_suffix: _unencrypted
    version: 3.12.2
