apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: penpot-assets
  namespace: penpot
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-filesystem
  resources:
    requests:
      storage: 20Gi
