apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: penpot-secrets
    namespace: penpot
spec:
    secretTemplates:
        - name: penpot-secrets
          stringData:
            PENPOT_SECRET_KEY: ENC[AES256_GCM,data:fdh9MRjMX+TRXOOy27J8ZONeY2TRgKCbRQJOzCG2OEXOIh9ezvnKZnRjFMF8HuFJiLprTKpcg1eckT9ZwZwHuep9PTuXGpDA8qR1qKLSygo1M1kp42Y=,iv:V/W3UdaKUksJHLSyY0lbWcEzpWjTuvc8tnuQfz9Bn78=,tag:VVm/OM8N0rcAR8RYX+vUzg==,type:str]
        - name: penpot-oidc
          annotations:
            reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
            reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: authentik
            reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
            reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: authentik
          stringData:
            client-secret: ENC[AES256_GCM,data:3HTDDLsTHwuK2oA84Nbx0AYbDyfALfgFCPMm9JvnyhYjbjDsezYvf3J4Jyc746hJ58qzkJ5YOx0giXKZlabmO+3u4sht8/kR882SmTwKWTA06Ib5ZFVxJiexcKDR0x+DlFLl1iZuhQ1nOGcOSMGj5ka9V2Sym9JLpp6aRrl3fuU=,iv:iHfBZpuBpAAXVrD+fbLFK0o4bIHVsClAvQwwAx00KfM=,tag:yTliy6wKS6Vg+tEw7PJegw==,type:str]
sops:
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6NFZSM2s1bjNZVWpzWmU5
            S0VpV1FBRCtzZTV1aytUV1NheTRBMkhha0JvCkJtNlRaendQblN0bFdUeWtyOHJS
            SGxzSXM4Ym5lQ3k4b0NOeWZvT2g5ZzgKLS0tIHZLZmhVTmtKcmg4S29JRlRZWHVt
            NVNYMWw1TmpIL1Jub1MzNm0ra1doUGcKdft7652/XZx4aBiiozAfJjQ7QPxwWTcU
            AwWGttAlGz43W/Kc+rCZ1iKKBiIsUqmw0sEt0H+fnrZClZLF5NoRRg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWV2JyS0x4NDYvWCtwVzAw
            Vi85ZCs1TlErS1ZxL3NjTkRqNk4vUURaV3dNClNxMmdUazdhTDBlOXEyZ0JnWHFE
            Sm52Ym9kendYZzV0OVcwUVBQZTZkb1kKLS0tIHZNa0xBWUVXWHQxdmJ2OFRrcm9Z
            WkdjZyszUnhnSlI4bnpuQ0dzY1ZtRWMKZHYZ3NE3LP7+A2gvDKGdEhl39hXnksMr
            ymTBBey/m7cRwZZEZ8vXzUcPSJ0nZMMmpHEPyeF6uy107o97E4ht1g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gzf883y8p0wfy5yjn5l3l2axnqxdgtw2zdcp8jqsrk65m7gf6y6qzgkf63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVytYNHR6aHo2UVErOFlP
            ZXRNKzB4Rm1kb2pucVZCai9Pekw2SFVWNkUwCkYyUmtGZGs3RWlIOVQ3aVU1Z1pD
            UVJzYm1XaTJEQ3o4MXYzTFg4dThMNWsKLS0tIC9CVHVPSUZNTG5Pa0JDZFR3bTNW
            WFZHQlIzUVdqYlJtZ3FxbUc2VXhJWUUKnkSq8FQiR1T3VKywiDynk4R6H/PFlr87
            b3ykLwgyOILJsziIFsab1WhMrpT8b1/IELLq1XeMZSzD5Idb4HvqMA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1j460k9yf4l3smlegue9yx4lwm70cr02308ea5wnpsuqagm25tgrsmfmpj2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1L3NIczV4ejlUQU9ON1py
            aUcvLy9nUS9wbE9Sc00wYmZIb05hVGdJbkZzCnRFUjdUNW5qd1ZJeVNrODJUem5M
            dVRYWityMS9sM1lsaEZYYm9Hbk1zdVUKLS0tIDM2OTRheHU3VDlqUEtTN3M5L3RX
            eU9yMytuR0h1Q0swbUswZ1FHMnIydmsKeZN0xWaT9QwRT39IEEUMluHAF0mIwfNK
            zbwtSppSadIjRF9UqW5zyhSaVaxgsnWtNVlkVF0zQo0DL/kzrxeN+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-02T14:30:08Z"
    mac: ENC[AES256_GCM,data:ABJQVKh6KtUTKc2+6DlZW1pGoPMXJXmzNGgrrpwHFiHIKUhnFy4wpATLjIFKkqQs1rpH20W17OMe9jLA4WwIy1XTIftA3XBD5bUeyDD99PY40/YCqEjX0Sccq9BoTAsCAwUS3MV2JHH3n03vzDntjmZLKz70FUeWTKxh3H+YTE0=,iv:ykkJ7RA+nN3+Sp6JGdepQzkzFRLLKnqANj8sS2ZkMaA=,tag:WwVRI/CDLc900mQre3488Q==,type:str]
    pgp:
        - created_at: "2026-09-02T14:30:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0IKwDTH3WibAQ//eTJoY2K507SsFPLv977p59vMnr9L+vX+hkZZD86eXMbS
            00tAKlhYIceg/+Xm/neZvbdpQvk36A61z43rT/NyK6al64ql9ULyebCF5nv6yF7p
            VBir4y7ZWcS5nQAH2lnO/B++fXpddINOrrRewsCeCfnUobjZydw76Qv8MG25k0A0
            geYyRzmoRDAOX6y0k6/oul3JEtr00WFF6a1BwbMGekz27ZjsOghsy6G04FVAKudF
            9KDJDPmyLGtu2ZZCR//Z/+fr1eDFVpvfpviXNaH/SbG3y4C2vmlks/zxUOuffg3c
            yOjKHBXD4gGV/4uyFIdnKhNHX8yEmERn01dLCcK0iPiFWOdqmBYulFAhb4vuEq/D
            bcVEYzCuSuCXRuKzy1aDEI5H+NTs7J+rVGnOz4TwVzs4/VzgWtADnwAa/e4/gFT7
            qkyBIAUzaKetR0eMrPzBkU7myhWLu1UiFVTkNcfmdwsntre525CUUUm5wSEEDxZE
            OPfj0hfMwyXMYcdSOLHVbUyU5U8lgaGcSHcynIsiuvvM66SkKYo5mxq76sm+C2Cb
            Sxdk8oiG+8T9NB6/OZKLhFKWVTevK5xpsg2Z2muAfk9SSOz/+ctD0noFnCnvW0dn
            zdY/kC5Opuz1BW17iIblGjKSxwTlLwdx49028d+2leMLv5sO5pkcs9h8IjMCWPfS
            XgHawp38XNi5wxGUyeAQR+KWFy7iXCoQww1tX7gGLKde9XcizodImBgB+stbtMrs
            NeccNBNO1HyoVqBHA9eJjEjuI0OIrtKcBmyHTlSMOYmsxHpG5sI7WcxAbrSjCVc=
            =1wAq
            -----END PGP MESSAGE-----
          fp: 03746612698994281D322B09923BC5E9B4E9509B
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
