apiVersion: v1
kind: Service
metadata:
  name: penpot
  namespace: penpot
  labels:
    app.kubernetes.io/name: penpot
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: penpot
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: penpot-backend
  namespace: penpot
  labels:
    app.kubernetes.io/name: penpot
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: penpot
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 6060
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: penpot-exporter
  namespace: penpot
  labels:
    app.kubernetes.io/name: penpot
    app.kubernetes.io/component: exporter
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: penpot
    app.kubernetes.io/component: exporter
  ports:
    - name: http
      port: 6061
      targetPort: http
