apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: forgejo-secrets
    namespace: forgejo
spec:
    secretTemplates:
        - name: forgejo-admin
          stringData:
            username: ENC[AES256_GCM,data:Eky7FRJUTkGtHoZLcQ==,iv:yqW6pwLiMSr7D4LOs6rdtHYNXCkvjOtm2eVhC4Pmy9g=,tag:tJLhDNS1OdFrhiukJTi5ZQ==,type:str]
            password: ENC[AES256_GCM,data:nMLd+8A9gh/Zug6imDm3J8ukeYNgNaI/Hmk0jyyzRmmmKP1jr4r/MsEvhJQ=,iv:TYeIqsvZz7yjsy/pczDYWRdGYD8KSQ0gFNJ8PtLMAUU=,tag:d1wn7aEDeuNRywmm6aMsdA==,type:str]
        - name: forgejo-oidc
          stringData:
            key: ENC[AES256_GCM,data:kPOJHxNYRg==,iv:u5B4QqcotIPSved7NdCJWRzYU6mz199gKK0JV4EZad0=,tag:9RtDroK7AYsj3b5savVaEQ==,type:str]
            secret: ENC[AES256_GCM,data:KWTUl0ah2x8kzgCqJZ1lmXrEfcJuDtzrO61I1IFg6Azsb7a8266p5uQCjUQAptYLFb6QK/IcddPY1v+eSJr8Gg==,iv:vsAq9C4muTXZgDR2Y7OKy2tzCgj2eZfM7ZmrVJc7rIs=,tag:E3FoI6OkAlvPdSbDMRkUiw==,type:str]
sops:
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSS1U4clVIdEkrcEs0Nkdl
            alBUckoxQ2ovUUtTeDhwVFFjNGxnSjlKNUJjCmlGRFJaSVl3bWZvVCtoa1JwZVhK
            b0FGNE5vOE5XQURhaFNRVkRNRVVsSGMKLS0tIGhiWFc2K0Jkbkxkb1VGYXVxQ2JC
            QkczdXlkL3lmN1c4WVp5d3NEMndnQjgK8Jr8OA5f0oAdRdHlLp+CHULV3MzccXiJ
            TBftUGypjp5HmkY1gYhkgL7oEDMr/AzxXtf+zY/TtE9Y2uEfHoeLNA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSVdGREphcjg1dEdWU2Jz
            QS9LeHcvWVFVakRqYjR1dTQzbjZ2VVVCdW5vCnYyN2M5dXpuUThtQlpOV29oVldM
            Z3g0RkxibkxJaW5tcjJuSk1aTVJ6VUUKLS0tIGgreFpmb1hDOTh5SVNZWHg4MHpF
            dmsyVzE3TjV1cVZNNXNVYVE5dTRKSUEKIL5KL7IajDbZ3v2MmmIR/qE73kOZqTgz
            gFvzPlhdcBRv2DteKwFI6u6Y+r126Fh1HOpDjc1KO6hSTOMJmxQrqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-13T19:47:04Z"
    mac: ENC[AES256_GCM,data:HViNr+vVFces3YIJ7OVhQaSy2KO7nw9gdJjcU/iRagTC2dInivty89Y6vh4EQrIYjUwCnlQIE4gUrtwUe0vgN2W2JFTMsV5KMRfaWy9V1YjzbslybN7L3RsRoQlFw8dt/X0nphrgOm02X6e/fg4NL1CbaDm72BD/rQJQNlca8PA=,iv:nOwUMXMjstOuPkM+gcqVjRZAIOIOSGR5LsNV9ZrIZiM=,tag:K7q2Q8DcL+3tEWGfGfbdTA==,type:str]
    pgp:
        - created_at: "2026-07-12T20:03:21Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0IKwDTH3WibARAAg2NeChUk2Dcq8q+IOnze8UW/zrQ9Djslv4ZF3CxO5LK3
            bmrwCFG9+ol9LkpUspxgff+glS5FYGGBFg40BJvQVd0LL4E6NHAeQkbatL8S40Gh
            f5js2t3RIxlZL14iyaD64iBHINBkqCWEZewyutbfvKGITSj+mWUAESrfMTthxuD1
            tM+Vspjf+03tHFPtcC0pfGI4yYyQAPUkrZILJRwGXWpLf9gJDXTPXJXWyox0nzrt
            hCYO1cTlf9wTfQsGHvMidJ2KA2yXEnAH7bAxBA6lS+GBGk7AdNTgK7tcpQ33PVbM
            ChMEPGP6zp+1NdDuFMKWtKal1gcpuZxN5rJ68wCphxM1WfOxLk9Jap76cTUatVxx
            gz8mPxKx38xc5AK7kfBMzAxIPTANAQwrllTPGT/gwyGpq4bHcIP5RIo6I8qWJxL3
            cKp1YcwX99PlzkqejqyqjqV3Uagcgy8dCI5yabAmwgc+pfwBM0luRIGitXeMMoYw
            7zrvPWfXg2oIcq3u5gxvJON7b7c29unccTjtlxpf1WQHqtcJ3CH5M8VmsyW0dqBN
            GItFpaQu5tdStu6wPed09pjKKYuj6jGNzEk13beERLrj3vdK/PGuWrZRSa2wmiMM
            TD7s+x0ZZADtOJrsFUqKXiYLBpaaSVRsTcXT38cTUqrqIK8TeqxL+9qX4lpQdXLS
            XAEE64jnj5omv5gK6+rtnHM5OCe7VQAmyvOMHWGO7oIkiDr/eDoAXRSlZbF7Qzct
            weLdkkFfH/+OuuKuKOCwJBiX3UgCcLGNdIQ/jSP6HFtXchmaAc8hUEP911L2
            =o/Kb
            -----END PGP MESSAGE-----
          fp: 03746612698994281D322B09923BC5E9B4E9509B
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
