apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scope
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tiborpilz/infra.git
    targetRevision: HEAD
    path: scope
  destination:
    server: https://kubernetes.default.svc
    namespace: weave

