apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - blueprints-generator.yaml

configMapGenerator:
  - name: authentik-users-blueprint
    files:
      - blueprints/users.yaml

resources:
  - argo-app.yaml
  - users.enc.yaml
  - secrets.enc.yaml
