apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: forgejo-oidc
    namespace: authentik
spec:
    secretTemplates:
        - name: forgejo-oidc
          annotations:
            reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
            reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: forgejo
            reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
            reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: forgejo
          stringData:
            key: ENC[AES256_GCM,data:oO4pgboDGw==,iv:JDkZivBuLTFIEnO5wjcVA0UfK+52lLC830QLwWiRHPU=,tag:PjZ3UCSq9uo0XJxqRo8y6Q==,type:str]
            secret: ENC[AES256_GCM,data:r5sTIbreQR5fo4NsfVUUqW/2+QMrr/rgvNBK3IUy4XsvTzklhPn6jcxq5InZM6lvr4lhuhR6eGwU74GC/AIeNQ==,iv:2Mh1JTjToufyBS8FinYpwEMronOBQYtzueUwV4oojY0=,tag:22HYFOD3DSE7rEE5SPVPyw==,type:str]
sops:
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMDFZWk52cVlUd3BVUUpw
            TG4wdlVCdnY0WmRnclFXYUFhOXVxMFZpQ2tZCmMwVjZlaU5vS3M2eWQ5by9lK1Zm
            cE1WdWczV3VtTm9uSDZvMTJaU2R5UG8KLS0tIFZubmsvQnhpdnQ4eG5QMkhTTjdE
            MGRPUit6WHF0UUVuWk9rR3VEWGtEQzQKECPD8bGG0DIZU5ACV0xDnZxqKShTJ4B8
            KuDXLizuZBOKMWPj19Wu0+zF+2IO3e0eTXy/rwCg1Xp9h892hjw+CQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gzf883y8p0wfy5yjn5l3l2axnqxdgtw2zdcp8jqsrk65m7gf6y6qzgkf63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQ0s5YmR5M1AxcmhiTlo4
            OWlaSk84c3hocnY2ZXZpc0dXUm9JZ3owQndvCndXcVhzRjJzUWttOFJ5NUxWY2p3
            ZmNqZDN3RHJaOVh0eTY3U1VlWklQY0EKLS0tIFVydHdIb05lR0R6ZWVkWW4wVko2
            eitCYVVhWXpKbHRKWUd6YjczOHBiTHMKVnzZwQkJvSn6GwrJYtALckxwzPzFdp8m
            1ILGhtxz3gCIksghQGk1IO171ohxdYKslni7U/XFaKzJE6P1+RWqlA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5d2JLOXVObHhQdUR2cCti
            czhhOW1GKzMrNWtodWVEeWpxWWcxbmxteWswCkVQQ1phSDZzaG1YdXVaUWtYUlky
            QWxpNnNJd0tnL2pTZjJNOTNQbVNiRGcKLS0tIDB1K3VaZkluTlczUmk3bGZ2aTBG
            YlpmeHJMVzBlWENUaG82MThmZlpTcEkKB3EgWmpKonHHSD5MPsgTcjN7Ea+IxhEM
            WLz18+zHNwcKcxfQDl9wT0TNcVd25DU2N4XhIX5qgAD5EZLqpryYHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-13T19:30:27Z"
    mac: ENC[AES256_GCM,data:AbARQhfw8qbbrW1QzPEC13odyy2CWA8y6sDxQ35oRJ+v0mRXIGBhwacy7x1D13GiwapZo0Wg5uWc/CutBrN+U+yRbHGWEuHI0h5mA/n1HbhH/wXdqWwAageaQnIacHWfvc3MXlkB+Gl0T1WFj93oUw0x+2sc+YA2QHmqpUUJSag=,iv:yl7fjQr2blFIvOk/YK6wWQ/WhLPqQpQPRQxezPe8to0=,tag:iQI7EYtSkWsHO5zyBgMhIw==,type:str]
    pgp:
        - created_at: "2026-06-13T19:30:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0IKwDTH3WibARAAk5RbAgHRVI+BPhAqJBeESG3aasiAI5wNtGacIsXCKkkz
            9HR420XCi/aMgEbs3PsWKwkfhp+d+RiqRc21FW5aHGwmEyCF95QHVrfxwwV6mKB2
            yT2c2yI6Xrq6LroaWMKPz/5Md5P1HFeebY3OmmVIIxM8TYHOxmfEl7eeakTdxykj
            ltQ7tLLyrWtqqrsPISQ7Ga8FxjGW97EH4S976hM/oIY2Eu2rtERZdPChexSKW6Jh
            B6oANNfh+W0MjIwbXgYb59idLEx1FqYmnfTOWEFdKMlY1oilIQZuMp1+EeaxTm5h
            L5/JOwJB3YHKMyaVAvP0jlfCC13j5TW1yoEbP1TD/DX7O3/fOzgL3FUa1w544kpQ
            SWvsOJ3hCui4QpQ0FNlnI0l2UqGo9psibtmNcfcY/o3vRKeUo/gbEQUMtmmM/0PA
            rwLN9aDfGpPo/F8Mz8v/SLTVz1xOcU5X+iv89PlzgbsDMF1ptujpEyeRZQrKeSna
            LL38Npc0ZsEmLKl86YY/36WQcYY/uu/yy4z+vgxsFBBx+0LotLMJDG/nSvsoiUAW
            0RyeZ5SwQz4i0C/UhhX4Ch5addkjiPmliOi44WYAk3QR9rwAncqyZHc4faLvPCWX
            lI90TZx8+CxWWpmNQReSuil13vI3c+IybV0HJbfA5DVBDzHwAZjyuqu08ITt66PS
            XgGo9c9r0GZ1HrCAs1uhsOAmvK94XeMTHihxw/rMXTg4tn1jVCExWZkFY8KxLK0b
            sdguuZ0ibVT1+WpNhfmHqw07jD3/iAJf6xqtUa5TT/CAHZBb5vL9xAgf+lZTXLE=
            =YUdx
            -----END PGP MESSAGE-----
          fp: 03746612698994281D322B09923BC5E9B4E9509B
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
