apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: forgejo-oidc
    namespace: authentik
spec:
    secretTemplates:
        - name: forgejo-oidc
          annotations:
            reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
            reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: forgejo
            reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
            reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: forgejo
          stringData:
            key: ENC[AES256_GCM,data:oO4pgboDGw==,iv:JDkZivBuLTFIEnO5wjcVA0UfK+52lLC830QLwWiRHPU=,tag:PjZ3UCSq9uo0XJxqRo8y6Q==,type:str]
            secret: ENC[AES256_GCM,data:r5sTIbreQR5fo4NsfVUUqW/2+QMrr/rgvNBK3IUy4XsvTzklhPn6jcxq5InZM6lvr4lhuhR6eGwU74GC/AIeNQ==,iv:2Mh1JTjToufyBS8FinYpwEMronOBQYtzueUwV4oojY0=,tag:22HYFOD3DSE7rEE5SPVPyw==,type:str]
sops:
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIU0pvV0JYVzdaRjlPKytV
            Tkt0ckxkZVhBb2hCbncyWUtyS0hRL3M3NDBVCkZoK2FZc0RJeGViWjV3YzRCeDlJ
            ZjdyTGFOMytvQWJFNC8zd1RHZTRnVVkKLS0tIGVLcWY5TUJRZnFCL0pZMGhKalFk
            OEJpTkhzTVUxQTQvVXhYc295WEw4OTAK31CrKrkTL6fDT2dqRG/8TWhSs4LOHqj5
            DD7gBrUgN3/dRXCsxcZbIZ8RLRRsgU8+Q4w2YE9d7uVJ/YVbf7C5PQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQ3VhSzlhdFhqVEJJNjAx
            cG5salBtbDF3L1ZVclhKQ2lCLzRweFFUcWl3CkFRay90VW1ValBwYkxxNGorYUNJ
            N2JpcElseXplMDNjanRXczJZdCt5SWMKLS0tIHJuL3pHWW1aK016cUFlOGcyV0do
            d1EyUUJaWnR6KzRnQ29kZGZlU2laR1EKTlW+h52gOB00PljlpeAb3TzDUS0ShptD
            yZBCAnw/NwobRl1bgWLiRGN1pVaYrQdccRTkoi2fqB138arBPEzLag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-13T19:30:27Z"
    mac: ENC[AES256_GCM,data:AbARQhfw8qbbrW1QzPEC13odyy2CWA8y6sDxQ35oRJ+v0mRXIGBhwacy7x1D13GiwapZo0Wg5uWc/CutBrN+U+yRbHGWEuHI0h5mA/n1HbhH/wXdqWwAageaQnIacHWfvc3MXlkB+Gl0T1WFj93oUw0x+2sc+YA2QHmqpUUJSag=,iv:yl7fjQr2blFIvOk/YK6wWQ/WhLPqQpQPRQxezPe8to0=,tag:iQI7EYtSkWsHO5zyBgMhIw==,type:str]
    pgp:
        - created_at: "2026-07-12T20:03:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0IKwDTH3WibAQ//ez8TjZ7+BfTW1qkGTHBqEsfSR59WVhlq5ch5tCoHaSIK
            spvJJ39gjuXWizTkDFMlx6MGq7nLMFzD4OwqsUVFVz4WqtqvRNfzxFOxk1zQmmfg
            IfcjvEuNtLR/zUnx/Hcggjp/cNIG5UtzPfmsVmvvXj3X5NnMEzbr3p8QeXKlw0+l
            UhHU6e5A7/8q+243gyyEOAxxX7kN8fBcMAncUTUmdH5h8SCB1L3GgHwO4lUFOux2
            SRmfQMPEik7sxV7ff1A5mQrijfkHiHyxU5qh8WqrWMlfWyZ7En/hSHJyCHrlu4Yr
            H2RSdKKrJ4TlPOrgnczSM6PxS9+E7Cd7ow8EobgLKbYNZWAMP45lTABb+6jtaBJe
            2ty7Q+Vf/q1GOacwIgXnCEE+1yzaK9itZG2tmSez4TrtcwK8tlGYU0oMVDPdFJJT
            tO9/XFHlHv2gEHzquc+izgAH/XRrO80YunyYcfy0AmKVpNd8d71CK6sTAAmkSCHP
            SULohWQYFBA2QgM5bwdxcAPTRU8ymclwMX45/DdTAr0QltRHdv7z99mSrWMWHEZB
            QDOQmV9sV59pwdcjksE5Qfz5xAbo45ZmKWios+Bzsxa4yA04jyTCsLRUeoKnWLsT
            ayy2C2PzSdlniOAqr0bo9pf797IC6IYoRXWqv8ITWoemXHv/p4z9EKPiFqGllSvS
            XgFexvzRqySwFd5HKLGCVh1Fb68eGGTyO5zoVrCIo1onWnTic4lFOdePyGRo0Uws
            xSIIS1ij9c5TsuuRQ1E0qKTySKWJltvXAXJE6odUFDtATPOf3/P0ap1UvNFs/zo=
            =IAlO
            -----END PGP MESSAGE-----
          fp: 03746612698994281D322B09923BC5E9B4E9509B
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
