apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: authentik-user-passwords
    namespace: authentik
spec:
    secretTemplates:
        - name: tibor-password
          stringData:
            password: ENC[AES256_GCM,data:txm9bMynkwpg9vI=,iv:/CVyrYZNSWYlw71yXG7PL0LUVtjyZ0mbmjjbTUHxQ7Q=,tag:GTAnzCEi8W48FbKGgxS1/w==,type:str]
        - name: tine-password
          stringData:
            password: ENC[AES256_GCM,data:zAPlFxruVODW3A==,iv:ZnUZsDNEjn6q81ThafopAQi6KlTgh+KAwjp7dL9QMss=,tag:BE36QGDfcHpdRbWk66436g==,type:str]
sops:
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjdDhXL1drbTBwZTB3aFds
            SExjN1krL1B5VzVNR081dDN3Z2ZjWEY4bVJRCkdRSThDNUIvUDlBZVRlOGFOSTY5
            VTNsd2RmZUZDemkwSGdhemRoRUI2OWsKLS0tIGlGRVFuNGUxVlkvRklMQ05BMHBr
            ZjdIOWsvWFJBYkZTbjZiQ0VsVXBJOU0KtoEgFzjHPKdCKcyAxc+i9GD3rCaDrhiA
            bRr9oOAEFWMdZWt1Y/g7vE3w6uISgZ5ZwgT2k9wV2R2sGuGP+ntV5g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLYURpN08wamYweDRrYm1E
            RGhhcTFwcElQWFNzejFzTnJ0SUFVS0RvT0h3Ckg2WE9yNUc4aXRtbWVKZXNXV1p4
            RU5UNjlmdEFVZDBSaU5sdWFGY2pRUVEKLS0tIEl4UzlEaUJJbXNMblpGQ3ZFQ1ha
            UytLbVo4Umkzd0c4azJBQmpnZVllRFkKIV45zUWgEs1NjgE8YU1Xzh0HZC0I+F3T
            xSYhGiA0Q0XuiWQsh5j7R7UldTSCJw6m/lMbpwr+iRzJ5LjhIo3Mhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-13T18:06:05Z"
    mac: ENC[AES256_GCM,data:1Jn6/+5Fqr1Hqwj6NitAspyfXNnKu1+tcbzF8GiG2sz2LJMXRbYRXUVBQPxz6VsRVjJHeXHIy9q4WF/Bsqi8GllBTURd5J5j0AFuh9cKCR2Eilx7fsJbF8Wdzcrg7PBC/AlEhWSITVe/09L0TbURuLmuFRgYwWBSVSxE9dqgC8Q=,iv:3rK++wkBvsibVnyvfXsxw4ycwMEd1fxBD+zV+tRT3kU=,tag:oBk2ZcQUiOm3sft0TVANMQ==,type:str]
    pgp:
        - created_at: "2026-07-12T20:03:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0IKwDTH3WibAQ/+Pic6U1gh/N2eIh75Exv6zht08zjHzbh3fiwQUWByDe7c
            Z5q8yDgfxNFHP6rOfxL0NlfffHPFlGDFLFlu94qnqX2WFmU2GkjYdVHuWqn98L2W
            XBmFavOIPho/FF01JGfo7dxlJ3Ch4Hq2LVbG6MTzG7t3DG1GhMoC1Wl8YTUiI/z9
            vBwcQNdYurH5SSRUZwseofCwBsnDGWPI7cbIxG5aYYVYq/9PkwGPq/evBbGlfCC3
            /atp233G95kiwGThVWp9F3N21S3ZX6YX8qiTtFTc6sZF1e6v494l8vSN9HlzQ3MR
            Mr63ZFnUEfvpmQAeJcoJPDg2QTVjYH9rejcyn1zWoe5YutKqjAb0mjdWYQ1YjOCb
            aAAR4WECu/yUGGtwlsVcmJNSgDOIX9s6c0A/TULCDrkpu+i1OnfBJPey4APfm4xA
            2/QA9idKY64XKLF5pzqyjQghX/H0ihI5HHmacX9ptCUC5YvNa/V6tnXDHIP8HvGO
            eKseuHkWyQCtaEmI7+DWt8/2Q4US712jQXcp9bi4EJ2T4LE/KrQdDutNroKfZoQL
            VpEyY+aDyx+yrd4TxtjFigFp180uN2n/yEuKDIdFu7eoLDtsNUx4FojS/vOF0xjz
            qtuz2l77qbdf6nY8eOQA5Jfe36dTobJtZkmF2n9l6CNcheTxOE6rY2Hzzk1ucWLS
            XgGT6HAjPfifc/TEqWTbMieGdTRB310/G/5EK6lXoLRB2QP0LYZW9Vpkys23B7Bk
            31js18ka0ubz3OiCaI6zhSMlhbM0obankowN11QAMm9dOl6O+Jq+JCGs3GosmjU=
            =cuY1
            -----END PGP MESSAGE-----
          fp: 03746612698994281D322B09923BC5E9B4E9509B
    encrypted_regex: stringData
    version: 3.12.2
