apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvcs.yaml
  - deployment.yaml
  - services.yaml
  - httproute-knot.yaml

generators:
  - kustomization-ksops-generator.yaml
