apiVersion: v1
kind: Secret
metadata:
    name: atcr-pull
    namespace: tangled
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:n1zpRvG6lg+oO+/s6nupFDp4kO8wjzeWsdbRkcgaTexAASn7iDVHKx74pP6ZiplXOT2w6HvGlb12wCzfn7VYssdVQzKRqPBXysW1rGaYy/Ag,iv:9ShPDGn6FKFeK8m49FPiym6kQh0TeSRr4Rx3m/ARlqI=,tag:hvG1em1xqmMwV2eP5+5Nmw==,type:str]
sops:
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlWHN3dkNiMXNFNVNLNWRZ
            dWtlWk1uUWczTlBzcUQzKzJBTTU2cUFUZFg0ClVRdEh4VDJOb3NORVZUbEJ1Wk5o
            MWhqR0JZYW5xeHFkVzc1WGpsN3pWVmsKLS0tIFJkRzdFTG1FaDhIWk1MbFIwTDFJ
            MDZrOGdGMTM2WnhkUURMOFhPRzhEY28KsBHB3TQWXpvI3g3GhUz/3rFTRNxpgsrm
            6NuzPFNf241B9hV7+FFDGlA5AsKYyZNMJ2/cBzpYD5QlDP334LccVw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gzf883y8p0wfy5yjn5l3l2axnqxdgtw2zdcp8jqsrk65m7gf6y6qzgkf63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUU1zY3VXb0NIVjlSTTcw
            bjlGQStEM1FpM054UzY0Z3R6S2QwS2lYRlhNCjd1ZzJvUnJtK1IzRnJ2M0NPdms3
            N0JHa1crQzRZUGtzeTNBclpTM0ZlYWsKLS0tIEduWkcyVytjQkJTYVBZR2l2UWhP
            bWRFZVUzdyt5Nmx2UmxQdjV1VjB6ZDAKuaq05q0/rJdv4POu3hBCeLuckm3CWpXt
            yQ3pahUvJYFU6Wx0Fx9ik5kjB5DIg6L81u4GHrMm8cIU5pDWo1TNQw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzQWdBUE9wakpValFBKzJM
            SERvRVhQc1Z3cmF3aWszT2RXQ09QOWZRRjE0CldGKzBpdEEzWE8rbDk5UStRUzlL
            U0JyT3BZWnhpcWhDWG1panhiYXE0UTQKLS0tIHN1N252WUE5Y0FvcVViQ1ZxbDhV
            SkNweldiL0hieGNkSFJIV1MxeHJmVncK2XI4QypU0mYDiR+Ln+yL59KCbAFaJXZl
            Hv5oBuLkGorVB+cRMUwodYlrKMv0eM96hKU37lCMdFvsb3MwQM1UHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-25T18:20:22Z"
    mac: ENC[AES256_GCM,data:THzuHA3m8Yao0LCiU2d3tHFT2c8w/1vLsxBLcr4QnIAP1QXsyVwUZaoX+7AvOJZ9X4w0e4OHf1dlH8WIVPIQ6PuUHDloJss9HKJsSYc38doENn3QMTaXZbWdZxQd6k4jEC8JmmQqMpYn9VedRTxRjdhRjB+bU/g0OPWLySFlGyA=,iv:mabG9EdiWfSuWmH7MQa/tZJ20J/a/D8NGtjCKq8c4GI=,tag:KM3MmtJYWlEyXY2m/hnroQ==,type:str]
    pgp:
        - created_at: "2026-06-25T18:20:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0IKwDTH3WibARAAhpvSRmAqstrJfl0Cj9KinkL5dN8MpWcAbhOxVrtBhXu/
            EfLfzzEkNjziF2Jhxc4JJ3MO/YfSQ+2laSyWlEot4r3rita4g5CRZkarDeuSHr6R
            g8LJvVSmrTn/8gC5cLXy1iIKPnuUQv6598WsisATL9+wVOJTKJ8xJQ6w+lVuDFZ/
            WuNiiE5e6NQAavVYkyBO+IZskUOOd7hL53XZpPHYG1FfcfltbFMaaMWof6X6ZyMH
            0OZiyDOJ/9WZ8a66BZVH7lA4hdeMSaFwxsVrXfzD5N7J8bsLPcRuqUdE8JPQ8TqU
            fvfXyitvpg+5XstJW1mGBWsJZKxDKmeqjlk5YC3vO7/lQXUXBUdDA/dL0lMyFYiF
            9F72FJuv9wxgSHkfZ6hquEy2bNFzPLOW08AyWQX1HglPpGcl1WAJ763o1V+kN18B
            eUl2thhIIhoSvKbVi24INtXHK5fn/wl2pRHdV8SU4ZItwhrl4HwR8wqgxOhk9tR9
            HweXH+P1gmiSK0ycOxCSfzAdOX/mc2jENpVHChfciMgwUYygOuof0EFi2MJ6T+ag
            N5mxTYdqcm4otL+EsEa9SDpwU7OXx5iupY/jS6RdnYhoFUF/5/uWQTmbFXCg2iUw
            wcxXS4izvlYTt8civohEVWySBX2mP6cr3EF2nSRhu1Vz2uXeJV+zjxs9LZHoRh/S
            XgHte8vYedt/2bKdw5ilU0zXTBJVq9ZSKBGlgOKWVBFKGL58LBZX3gZzFlMnY2SC
            BZE3FZ2hfpEBam5l2BVGjZVK2AiBeuZfszck8OJGMWOpR7HRx2BX3gMbL0x4pYQ=
            =IqKC
            -----END PGP MESSAGE-----
          fp: 03746612698994281D322B09923BC5E9B4E9509B
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
