apiVersion: v1
kind: Secret
metadata:
    name: atcr-pull
    namespace: tangled
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:n1zpRvG6lg+oO+/s6nupFDp4kO8wjzeWsdbRkcgaTexAASn7iDVHKx74pP6ZiplXOT2w6HvGlb12wCzfn7VYssdVQzKRqPBXysW1rGaYy/Ag,iv:9ShPDGn6FKFeK8m49FPiym6kQh0TeSRr4Rx3m/ARlqI=,tag:hvG1em1xqmMwV2eP5+5Nmw==,type:str]
sops:
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvbk0xY0pPNEtOZEk5UUpz
            Mnl0bzVlY3lLZ1lETi9nTW9uQ0NaTFh2WUR3ClA1Z0Z6NVQzMm1lMDNPNkx5clFs
            OHZFcUI5dTRPbWZiUnBIYUFucHZxb28KLS0tIFB1NXBqQXJGQUpTdHo2bG53YmNa
            a0MzYnZHd1IwVEYvQm1SYjNqQmdmUmcKs/3bLUIgClg4zb2Ja4xQB2QeD2+ZBlQ1
            A4EEvTUK+4jCxPlytKiPu/QKa4OzpJGl8RppLBl72178g97O9dvynw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZUmpLYnJTUHRZNkk2cDVF
            MlFhQ0xTeC9YUVRGRHg3NTdIUURvMkRmM1drCkxsYWs3Nk5oV1JZaVBvRnFDcklh
            Z2ozbGVPbnFxWG8vVUFNNys0TzdpaXMKLS0tIHBXZTFrZHpwNjJFcG9yM3FHZ0RK
            YU1zZkY5WWpIQW1zbi9DVEFwMHhYcFkK6op1Izmm1ci64hQjNN1eTcOXZTEUu4sW
            +uDhUrsgFUIKsVZ8lbzqAUoam3ODK7SJk6tS3Eow1mn/QsSjl8fDJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-25T18:20:22Z"
    mac: ENC[AES256_GCM,data:THzuHA3m8Yao0LCiU2d3tHFT2c8w/1vLsxBLcr4QnIAP1QXsyVwUZaoX+7AvOJZ9X4w0e4OHf1dlH8WIVPIQ6PuUHDloJss9HKJsSYc38doENn3QMTaXZbWdZxQd6k4jEC8JmmQqMpYn9VedRTxRjdhRjB+bU/g0OPWLySFlGyA=,iv:mabG9EdiWfSuWmH7MQa/tZJ20J/a/D8NGtjCKq8c4GI=,tag:KM3MmtJYWlEyXY2m/hnroQ==,type:str]
    pgp:
        - created_at: "2026-07-12T20:03:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0IKwDTH3WibAQ//Y7CgUAoEfsiJnbcLQjjaE5RgEjcNKmKXBhcseIF9lUiX
            NgyTnmyoJXwdtefRuIQQwxZ4f9nQnX6VZ5l/cf0vaVA9itZO0C12F+q8ge/P8+OG
            efMCSPYeg8xZT67RZHh7VBOI2LkfoHQb0+UWfs2cyf3eKk0kAoZpEjTqdyWAPuio
            OuCed1M4ib1iUXMy+zGCLSesg/WA0ziidriH5ezhkoy1MgDXPWCGeCq76PaWb5pT
            jAi9Yf93kkuDmviSJlxPYuBzOvuefCtFsveK0fBsr02YR6rHMIcI1TbLWZqic3vS
            3OllExfooajXkJ0De3uO/OPuBrFUCa/bVTqk/MlgPEhDTTTExKAS2lOq3joYdS7L
            gf9LWrt9j4Ily+lBZ9iLAM8JKgbv5zGhvjvJCy122XiUZLvGUHQdbALNMTartXnl
            oN3tm2F/rBxHSFIeqUazZPuhOsA/pdopc9htMztQsCjBCXhSEYJ8DaNwhh4dDT3j
            DI39tJDhZVkGouSUf6RTKdOMPBWJ9r8yQ87dWUQ9Q+6KGJ6sXasiVxwoFV+cQxkJ
            xp1jvtMaO2DD0oKPMQP160BuXfSCNAGNNrNqf1Tm8QV+yZs2/seWgr17wzVfr2Qk
            UE4o3aTTUUjzhXrL1WLvqCotfGjreQDhQq5wFl/2X0Kbj9UF+uEn+2khS91RLh3S
            XgFHsfkawaQaIt6ZacN2Y/rBpsNrg9FSAvaSEC6xvPgdhSInDdOZLxfgNcGQKZd7
            JlrsvOU+3Dxyyy1lO4Y6icvyvL3phT8GPAi52Yl6L0QOlMECkpmbtsxeecINl3I=
            =nyQQ
            -----END PGP MESSAGE-----
          fp: 03746612698994281D322B09923BC5E9B4E9509B
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
