apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: knot-secrets
    namespace: tangled
spec:
    secretTemplates:
        - name: atcr-pull
          type: kubernetes.io/dockerconfigjson
          stringData:
            .dockerconfigjson: ENC[AES256_GCM,data:Gmvbzn85vABbXX3RxLxkPJF+cJ2EK8wSoyxsr2ng9eM4dbabadosReD87fT0LR4vMYRLnR56ikkl9b7G5JNtKly+VBQdGsQpY/Cvn+2XhVW8,iv:08zlivgCABIazU1dzdW3vXaPIsa/go5PbDdAA3qJ3NQ=,tag:ScC1yvbpdIK7m+dJg0+Kbg==,type:str]
sops:
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmaDAyUzhsK0I0UkV3bk9Z
            ejh6MklOaWFrVE82a2ZHSjRjOUxwS0lZU1FzCnNKOGpNUWdzNjZyZDUyT25GSXlE
            djBwYjlpUXp4SVB2ajRha3pveFFXcTAKLS0tIGJhRldmQ3FxNTJnOE1kNW00Tk84
            aExqWm96VG1CYTFMeTFZL2h0bUtKTDAKbzQsBZU0m0FOskGFza8QW9djtTaHQEqD
            Zvf/noFx2ZuMCFuovmuZFOeTCHQETezc1Q35ZNrX1NlvjBvEkBZneA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0YXpKTk1MU1pxbkNSamlo
            TllLU2R1RW9wcnBncitzcjZvaFpuRVNNZEJrCjlzTlQwb29LTEdPZHhyMU03Qm16
            RWYycitwblZjTlBwQ21FVUN4a2NiNnMKLS0tIFg1YWphSmlhY2ExSEdURHllZlg3
            WkpubFFZcnVBQjkvZXZBUlRUVEs1eHMKc//b8b+VMYoSjxkHyWClSrbqcgTne/WE
            x+k8NNNv/fNOTMUrIe888vQFny94yDwrL3yG2CuDE3UM/QevGI/T0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-21T16:59:51Z"
    mac: ENC[AES256_GCM,data:TxnqPZG/4aoI8W8fEfBa83d9y37vOUYvDm9uj9ZIX0pgjchtHBcwIg/7zm/L8SxeASwQeeVv1qTZsMkRAl/rErmKm34H/4to61YJN8oE1W3MD+br6I+PL6WqrX4hdnPN0uJP7rwYGBgdD9fxPFHt/TkvVZApk2WVF04DmweMQZw=,iv:/SUZPfmXJL3xz2RXhqQhhAuhRj8+ST2OWSWMlLXka8s=,tag:h87BIrZaBNAHvIaocwReRg==,type:str]
    pgp:
        - created_at: "2026-08-21T16:59:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0IKwDTH3WibARAAjvC+A4bkNXYEaaw+9ZI4LHSq+nvK5U2SaPwfLp0fKHMT
            MBuBAGU35Rsv5PSmZmcEsMuOrXmhWzv3a7SdvyHzxpygJIUb+DuCbAiRWRrXHAhI
            Zto7H2YqwCxbenf0QsfU9LQuAndRBAAZxiJHVJrbRqt+00+k/XJkd+cbro9T2PU3
            2TVeQtSt3FNoAhJosghwAwOipuVvotuq5IIvcKq4hwTJMW3CvQnS4zpR/taevk/t
            ru02cE1KqM8xiePDRR3RU6U+tsjihzHc/wxEKfzBJGH+FuqblPl7tcFyFtJfC1Vy
            NtAmofDsYlwUcqCEV27q6oSdsCjx0LPwSay+qS+XUlTkiHBZ7eEAbGySQ5693WDx
            sxkbr1EbRxsyrIV0vVIbjgBCvthiSzlH9a5TeZVZhsR6da+Une77KZcYel10Ab3K
            u/oWm1PtTcYwOpfTi0oPYD5P9+uSAKZwNag0lNfx5u3blNpmkRCRKnXxJI7d2n7H
            nxLIFLC0FjHDM/z4fXudLHLXLQw62Nw+H4xCZgUENzR6xPHgpfdGDdl0XKxJpzka
            TZQOCm65i3DfbSM5bClIqQwoBAmfebw0WsAWCqYOTNl1LZPU+yU9/Cmv6GAIQhZ2
            FAsVM6PiVaRU1XCrw029Oy0tbrR6en/kthMPVChjQJrY2Uzp2xvcINXx1IHJspLS
            XAEiCs1KIpWWfkDtbZezSatRZ52pln8iIqJlQimrFPy9OrJoGeqEHt0cOO4Gt2Fl
            s8DhWe/ApLYKdWoKNM9Pvc/rBlPK7fX/PDTBlAEJgxLifDMOVB8qqo2+FwIo
            =E7hF
            -----END PGP MESSAGE-----
          fp: 03746612698994281D322B09923BC5E9B4E9509B
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
