apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tekton-auth

resources:
  - argo-app-oauth2-proxy.yaml
  - httproute.yaml

generators:
  - kustomization-ksops-generator.yaml
