apiVersion: ENC[AES256_GCM,data:Ihw=,iv:Y788M6hbcLSaNT077Ee/NSZ+S4JOjhxFXOFia0xs990=,tag:aeE3z8XBb2K6RAUipQMGwQ==,type:str]
kind: ENC[AES256_GCM,data:n75jw574,iv:mfV1c1K8ugs8lyl1naWf12BcMTdtZ7MTaJxLsMWhz/4=,tag:S04wb9aA5qpB4zKMlM/DSw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Jtpu/QsRsSwnvzDD/dgLYjB7XLY=,iv:hkF9IWfsAAx+Jvv5DDaSYrHWZrvkxwLmMHROeNyWcU0=,tag:a9EQBgtEFAt+EjXSRIgMAw==,type:str]
    namespace: ENC[AES256_GCM,data:dxYBKho0BA0TLkg=,iv:vDnQiIOeovkRXZVuRdt6lzEDqVQaDgCr0nGPtMeRjqE=,tag:JAQEP3lcsjIiXbJM8oQMoA==,type:str]
type: ENC[AES256_GCM,data:yp1z3V1c,iv:ZN8TNqxo+GHLik8VJXyrtK0h7BSRMVDKG5rP3qH9oM0=,tag:CIxINfwpSizRxUDtoEBxMg==,type:str]
data:
    client-id: ENC[AES256_GCM,data:o+yDbSs6UfQ=,iv:ATCa8lbPWST0mFg0FheiwUTgTv+V2BPUbEEmGbyNHL4=,tag:fn+gBIoFo2tGiYr4dGYNjg==,type:str]
    client-secret: ENC[AES256_GCM,data:p3ogjCls8X0miBWlo12Ik0P+hDMbrYa6zsEzhyQinHWh9mzMbP64XESWbpYggLd/W+hLfXkGT25PHI1bdsxVgMHhGNFLRYQYh4shIpVn4Rpi3P4WGIqG8g==,iv:rZEbhcKuiW+3+hBodRcqXweGiUMfCQURlJlIowM8jIo=,tag:/YjHEZ/1HFfmqHraEqG2BA==,type:str]
    cookie-secret: ENC[AES256_GCM,data:AxF+yLzmmjOBOcn8LgdiNyD3+1H8u9SldqVP+YWa2tiyMPWR0lp/Z4L5VXjLat1Q9h9Tme/qVPrXOJCG,iv:be/HEpAzXs23YAeDar3tdyexUYTEdDj9ycN2yGid7qY=,tag:9HO3rYeDPNge/fLmWeinHQ==,type:str]
sops:
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUURzeUJHM1dtVlRVQkxJ
            NmtLV0lydmZ3WnNhOHV0OHZVV0hqZ1o5aVdJCmsvNnAxRDI3ZWRYRHFacHI5a09t
            OUxmYW93eXJQYUNTUnlmQlJGdm1uSVkKLS0tIHF1Qk1sS2hjRU11L09OSFJIanBv
            aDN1ZUx3MlFrK3lRVEFiM2QwYXlicEkKMyMet29OPgsmzAqGF+RI5O3XPB89gENn
            DF0U48efanwB6YU7EkIQnOuCwEC3HjfoB/uJGcerb6sjAx56AEUCtQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gzf883y8p0wfy5yjn5l3l2axnqxdgtw2zdcp8jqsrk65m7gf6y6qzgkf63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQ21NTUpvV3JWZ2FMZTZ5
            QUlXOFVSYXVONlNTc1JOOVN3bDdORmZvbGdBCkt0VEJWSmFHNFJIbkhVU0h3WGRJ
            b3h6VTE5RkxlT09TeUxrSy9aVXlBcFkKLS0tIDZyTEVxOEtueitRc0xvTmFtbXVX
            RkFIcjZlTmtpZ3ZoTytZZzZzbzk1Y00Kqh/doYwBs1UEtH6KXz3BwF7PvzdFzY7D
            L6DuKC72/BzbhWafe3cdhpZ5PrzY62SCNxrI09rU8uG86W9Zw3zokg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ZHZGZldESUpOaERKWVBp
            dzVWdVBRd2ZOTG11SEZTV2xvRHNjb21nY0hRCjFyVHNVTVoveno4V3pobHF6Wi9x
            TDdFS243a1paOFlkSFFjVFYwYS9rQ0kKLS0tIG9aRUIySCtkOVpMUTI2bCtsT1VF
            bDh1dmZXQXdVa0RaNlhJUjc0UXhPMTQKGvXrn/pzs3yJFWFMhJU4edfJzHWo9D+0
            6ifFQSnQ/2ypO/tiHoLtnjUDNMGkEWxflDjfWIyEFktdMAakGcE1Ww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-13T12:01:38Z"
    mac: ENC[AES256_GCM,data:bzWn01745cwWNERDTD4LG/8/h/FsvITHztryYCN9idW6lIklHIy/dLrxT7CqBQzGkLOaS90wiPbEKaTsghuUHWFbqDxnQm++EFUoarhjNbyCeIbiue7gLGdkWDuQi5bWbbTPzD4biDgBEfvk8vycX4ZB9Y1E9FzidGFG5PJf2Zg=,iv:KcN9mzWn7DvWJqRAngUsytqQFBFyAIF8Wx7OqfCsXbo=,tag:25OQFkgU0u1We5tdW5t6Pg==,type:str]
    pgp:
        - created_at: "2026-06-13T12:01:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0IKwDTH3WibAQ//aDOJf3QjD8pYZFTNwteFcKcoIXnukG2R+dQLm3Sw6jwW
            N6rPvra7ZEsJURz03RxMQ/lP2AgYkq1hDFxq6bg0l+usiTjgqBSs5H88Cyr7uCQ1
            259XCexkxe4k5IyqUIgR0lWlx6SZAoEaz3yFL9P4OI9YmiGouO4To7CI4sz3Rv60
            +93DFrErIbHrzab4ucj1kRN3RzASGfKyEDIvCiP/7tISkDdjnLB0oJXqM+IFAmn+
            xcbwXsuazpzGoZ3RvTO31/DgtZJ/biVZBBkPWkfIqx2HfSelsW8GCe4THzZEtx0L
            od0iFWVKMNYSbgrzCZZ2h5aDzsfcx86ztTBUaRhNeOxDMtBSJCYliakMqZHDgO+8
            m+qPXZj3ffFebHDMybyNPb4FxTFqrca0dySoImIRGJQ5GsZcq5SDKAP8uxYyyReh
            AGp7kCNUNd6piZOCPCGDV25W+WhEXiR5F+jrMx1m+aHE8FJh3KOLqPQYR2oCkNoR
            8T3XL11JVwiVUkokF4VqmulzPrIs1qKp+gALYdEvFYkISIfDMuRdFYjYL9yFr3mG
            euUqGzeepFSfDazWcvXFEbYSCKMq/7FZ1vSdp7nRRo1H2chae88RhZW53qYPYNc5
            PfIFUZvgIR6YDXNUaYg5Uqqn+4qWmECWx6tFVQr4Z48fBG78U0LTz2qpZ2FSQn/S
            XgFZDti8C4ACNlvRelUcBAaaZfnagNd2G/JlMRHyRDKfbn9n2tyheP2vZ5hIUfC9
            fYYQjWR7lTWpvg64yU5zPAS5rloNWPt/SooG7vZDm1E1fIJLcmcpSQoHLNu9I90=
            =7SYT
            -----END PGP MESSAGE-----
          fp: 03746612698994281D322B09923BC5E9B4E9509B
    unencrypted_suffix: _unencrypted
    version: 3.12.2
