apiVersion: ENC[AES256_GCM,data:Ihw=,iv:Y788M6hbcLSaNT077Ee/NSZ+S4JOjhxFXOFia0xs990=,tag:aeE3z8XBb2K6RAUipQMGwQ==,type:str]
kind: ENC[AES256_GCM,data:n75jw574,iv:mfV1c1K8ugs8lyl1naWf12BcMTdtZ7MTaJxLsMWhz/4=,tag:S04wb9aA5qpB4zKMlM/DSw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Jtpu/QsRsSwnvzDD/dgLYjB7XLY=,iv:hkF9IWfsAAx+Jvv5DDaSYrHWZrvkxwLmMHROeNyWcU0=,tag:a9EQBgtEFAt+EjXSRIgMAw==,type:str]
    namespace: ENC[AES256_GCM,data:dxYBKho0BA0TLkg=,iv:vDnQiIOeovkRXZVuRdt6lzEDqVQaDgCr0nGPtMeRjqE=,tag:JAQEP3lcsjIiXbJM8oQMoA==,type:str]
type: ENC[AES256_GCM,data:yp1z3V1c,iv:ZN8TNqxo+GHLik8VJXyrtK0h7BSRMVDKG5rP3qH9oM0=,tag:CIxINfwpSizRxUDtoEBxMg==,type:str]
data:
    client-id: ENC[AES256_GCM,data:o+yDbSs6UfQ=,iv:ATCa8lbPWST0mFg0FheiwUTgTv+V2BPUbEEmGbyNHL4=,tag:fn+gBIoFo2tGiYr4dGYNjg==,type:str]
    client-secret: ENC[AES256_GCM,data:p3ogjCls8X0miBWlo12Ik0P+hDMbrYa6zsEzhyQinHWh9mzMbP64XESWbpYggLd/W+hLfXkGT25PHI1bdsxVgMHhGNFLRYQYh4shIpVn4Rpi3P4WGIqG8g==,iv:rZEbhcKuiW+3+hBodRcqXweGiUMfCQURlJlIowM8jIo=,tag:/YjHEZ/1HFfmqHraEqG2BA==,type:str]
    cookie-secret: ENC[AES256_GCM,data:AxF+yLzmmjOBOcn8LgdiNyD3+1H8u9SldqVP+YWa2tiyMPWR0lp/Z4L5VXjLat1Q9h9Tme/qVPrXOJCG,iv:be/HEpAzXs23YAeDar3tdyexUYTEdDj9ycN2yGid7qY=,tag:9HO3rYeDPNge/fLmWeinHQ==,type:str]
sops:
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvUjRJMkg5VkNvSk9YRkhm
            ckVTbzBMUzdxQWFyVExmRlJMOXRLL0tZazBNCmRCOVhBMDlJcVpDNm5LNXYyMVY3
            emFhcGVOaVpaeUZVdFpJditSM1l2MmsKLS0tIGhhNnFTZVNUcENMbjBqM2F5VW96
            Mys3MVpENGVJeDVRa3lXVmt1Z2gwYnMKjQKqXwBNEoALNldjZKNKiUYchbxm+bJw
            KSrNlIdv8owlCeMWZJ5DLNquze/HYJC9c5Wb2Qu9bEjrxidsA8K0SA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmY3hkN0dhY011V2xid3hM
            Q3pQKy9ONjNCcW5kZ1hjUkFHSzdJY2R4cUJFCmF5VmRqTWJ2K2thbmtvZ0hqQ3JE
            YXI2Z25hcnppdHM1dWdZK085K2pvR0kKLS0tIGVmQTI0dlF2U3gwZlkzT0RCSUFz
            V2hybDErZXR1akRia3ArN2w1cEJpZlEK8/hri2Z+Lq0A8s0oxBLUXqTiH/7L9Ksy
            JKEipYkC1hvHtKTzODqMMjSQJGpqoBfCLBrEkvewaXAqcYLcV9CyZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-13T12:01:38Z"
    mac: ENC[AES256_GCM,data:bzWn01745cwWNERDTD4LG/8/h/FsvITHztryYCN9idW6lIklHIy/dLrxT7CqBQzGkLOaS90wiPbEKaTsghuUHWFbqDxnQm++EFUoarhjNbyCeIbiue7gLGdkWDuQi5bWbbTPzD4biDgBEfvk8vycX4ZB9Y1E9FzidGFG5PJf2Zg=,iv:KcN9mzWn7DvWJqRAngUsytqQFBFyAIF8Wx7OqfCsXbo=,tag:25OQFkgU0u1We5tdW5t6Pg==,type:str]
    pgp:
        - created_at: "2026-07-12T20:03:20Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0IKwDTH3WibAQ/9GposePyPD64FP5VclRErxTiBbttURKoB90PTqAbhRBb8
            5fNzxPgpbT712w9Vzp5/GO5O/lB9CptqMxMvtxr8rXVZm5gxw8U1Fkgt1NFUUlr8
            s6oTvSYpXzzkRCZUdkYMvX2qz9kky3G/nsx76JKj6l0ZuFNA7OpCb1U9fad0IgWX
            aLu+FSSuTxKVsZS68CTgyi/DztVTG4l3H4LIVQ8xpYqAMEqM1K9kC8Fov5Ru7lmA
            lFnYXFUzOEphiPGW+aZsWWs9PTF4KJIsvEK+FZ8r4Os4DgbozaE4K9gF9rt4xuH/
            RA3vzaufIc5iG5GHzp5v3cHT/ST1bbGOf1jjngyh2mDXf/N5ylwrF7bS0cO1bvOL
            kQmu7oRqq5LAvpHP/UDgwDL+dboCKw0qciSUneH97zgsPiW1Ag4/Ajim98QAgQJ5
            Hvze/zi7C2LJMVzPAlntb6maQVjnWdnQznBTW9WlPvMJBa8VPHujbVcICyC/ic05
            yKkbb4s92AOoyAx5pISXYF0J/2vokwRfFLGtwSOMgzKMiHstGaZd/Ug6kuvQre62
            ZgHrYApqTCYw1lxPSMGHkYjxpiXBrLOXnJ1921GizDLC5mNPwwzET7ey/kHpWVCT
            1xSaWWHXvZCZFba7QbhbYD5G5OYvzuAgJlV6cgxsJSuhcUdXNqWBX0u7YMUQ+vLS
            XgG3OgSHm/PrB2v2zpJoyc7thAFFXyftMPXHAWLJsePYjYwbpZd3Bn7lOCjxy05+
            9Iw9yhGHER2ZxVDZMfQg2sEijj51qO1Elit8/VgdOxhuLDlDjJEtRfCuZIFa0Pw=
            =YbOt
            -----END PGP MESSAGE-----
          fp: 03746612698994281D322B09923BC5E9B4E9509B
    unencrypted_suffix: _unencrypted
    version: 3.12.2
