apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: tekton-secrets
    namespace: tekton-auth
spec:
    secretTemplates:
        - name: oauth2-proxy-secrets
          data:
            client-id: ENC[AES256_GCM,data:5RJa4HTUJsI=,iv:2j9ZQWci15IDziuyb26j3N6XjSotRcpnhNgbR+K/Kps=,tag:lvru1AHu8XHPATSJckgVnw==,type:str]
            client-secret: ENC[AES256_GCM,data:gGahANIGdeZjI1YhxTLP9aRKdMUmQNIcceSBEMIrupGxW+HSkSU72I2jH73OSR9G2XbAit/VofzYwOVfW6iF1GnQ+IlyItT2OvrQn54j5SF0IG4wtJYumw==,iv:+79sePjbFRXaJwEY/chGan9i37/b7nL68MYqBpk+3oE=,tag:jws01PnQbtfYWc3sYxNvGw==,type:str]
            cookie-secret: ENC[AES256_GCM,data:GUlZBbRkoaoSXzi8ZrM3SahQyjU36o9skwdTCcHm3dpRe9PS8UX+I6924bTpNBxNaI/zAlc+EMQ9rxzn,iv:MFBr/Ze/abCYpRkzmRRbVW9zPOZpOGifvhvNh+8T2pE=,tag:35q+mnxicCCOsSwm/gqBtQ==,type:str]
sops:
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNEJXSHJwS0hET1RCRU5o
            TEl1Nkx6T1BZVGZPQ1RXTW5aRVBEeGViTXhjCjk1VmZKcTR5STdzeWtvc2pZMGZ5
            RHRsMTRDR25wMDMzM2szMXRpSEl2QzQKLS0tIENYSHlPbW13YlZOUEZscVVPQUZM
            dXJFcjA0aW93cnlYWjJEcGIrcGpuc2MKp2sAUxCrBOodToAuizWaRkLpde1DEm+S
            eoNZCAb43AyJ56W6APN/TKMln+Rb0UrPsuFfVwuzEZJvnRIXvPpYpQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZGZkRk5JSmo2YkVwb1dC
            NDIyUzZUdjUyT1o5b2NzZzB1ckVMY28yeDB3Cm8yV2NweEIzNXJJa0t6alZ6dG1n
            WEJUSVNWcGtqcDhmTEdha3pvMVgwZ0EKLS0tIGJ0czhMY1NJdWw1UDJUTUQ3cW80
            d3JmVDllVnFOWW9tcFZmTGkyS3N6MFEKSTDGjGu1+okBYv+6aK7UPgOm+yONRyb4
            exL3sBRAyNVIuU/LQZyZSAYvp/SrsAEqf+Z1c9+X8ltb13Zh2Z1SDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-21T16:59:52Z"
    mac: ENC[AES256_GCM,data:XzlG3UIHPsyOONGSRYE3aQ8pulrE1mM5H0i7J2wWm/283dneAaW7Q1eyYsE/WpfnRSxV+GqOPsXXezSUR5dcA6sSpoWyFPPaIsVLMs3Z3Ozc1UJ3wHW4cF4DX225ckxXmJKHLZw6CaC6DJUuued1grt8oyLyRCAD5Cw2Iqv8Hnc=,iv:RAXj0FjdjTVVN72nUBGfTLWCFp2d/Hb2B8jJAHxVYOo=,tag:HqXoKCGXdfyrUU7Xz80LTw==,type:str]
    pgp:
        - created_at: "2026-08-21T16:59:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0IKwDTH3WibAQ/7BmERzsmCygb4XqvtG2NimTyE4UslC0KnwZU/lC507WnE
            4t9k0UxUjN3g4IoeRFy6iJm5tr5+o4WnRos3p8Mda15qVQa2+VA2WVLYttq8/PYZ
            sZK8jyhuGn+NdFV5XExtloOFb01h7wpyPiYQzOvhKfrnqCwj/gvcXQRjxniE5BJL
            A3OtuG6WB5ooCoJHCDX4YTg3JE4LpFNcuFFdpZgL0ZrWszqvDEJJ5GNcfmjb61Po
            lfVK/MS2f0aZ1eItxvJxokTfls6HMXvKQTcoF1c9KM2JzdbM1wDFc3yOv4eQR3+H
            3BjM2oo3IST8Is8olMpVIoYIL9Q6VcFBlq6sNSguAtctDScHxer/rujrL0xncSeJ
            1ioXiMM1fAz50rixt43Eg1osv4WU2boKZyXSuoISXffhgv0Z2Xv1x/wU8cwDB04X
            ggAd2Qu95b9Gy2wT8CPxw+egt/04rO/j+NLupQMdJIACAdLW/O9zWsCsUu+H0yxU
            88sosaGoXV8KP/vZwuMV4l2LwMR9HxG1bGxjslQjEX6g6hbh88t/53d1AEq9O29B
            rh+DmYVSPXSK8B3mh98360w4HgzLA+965JHOOpYLgv4TodDGl6HaW9rGTxF9EcAG
            +HeUkQJMwMUdcSwF+1Cexm+Rtnh7Af6J9Pnnovph1Ri1nUs/LXRypjcrPIYn68TS
            XgHdX69lszrLY/7K52UnB0FcWJ1RoT/fZHAOf3xfLC7+yiMNIbbDk0HX5xHDEZd+
            RK1UPMXk3htJigfGlYfOFHW+mJLcm35N2eyV+j7sE0FcssMlXkRfTMYlqlgYVO4=
            =CRKg
            -----END PGP MESSAGE-----
          fp: 03746612698994281D322B09923BC5E9B4E9509B
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
