apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scope
  namespace: argocd
spec:
  destination:
    namespace: scope
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: applications/scope
