apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-clusterissuer
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    acme.cert-manager.io/http01-edit-in-place: "true"
    nginx.ingress.kubernetes.io/auth-url: "https://oauth.tbr.gg/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://oauth.tbr.gg/oauth2/start?rd=$scheme://$best_http_host$request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user,x-auth-request-email, x-auth-request-access-token, Authorization"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Authorization $http_authorization;
  name: scope
  namespace: weave
spec:
  rules:
    - host: scope.tbr.gg
      http:
        paths:
          - backend:
              service:
                name: weave-scope-app
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - scope.tbr.gg
      secretName: scope-tls
