apiVersion: apps/v1
kind: Deployment
metadata:
  name: spindle
  namespace: tangled
  labels:
    app.kubernetes.io/name: tangled-spindle
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: tangled-spindle
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tangled-spindle
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: spindle
          image: docker.io/heywoodlh/spindle:c38881b4
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          ports:
            - name: http
              containerPort: 6555
          env:
            - name: SPINDLE_SERVER_HOSTNAME
              value: spindle.tibor.sh
            - name: SPINDLE_SERVER_OWNER
              value: did:plc:uxci5w626xlqmmbkzis5ksww
            - name: SPINDLE_SERVER_DEV
              value: "false"
            - name: SPINDLE_SERVER_DOCKER_SOCKET
              value: /run/user/1000/docker.sock
          volumeMounts:
            - name: data
              mountPath: /data
            - name: logs
              mountPath: /var/log/spindle
          startupProbe:
            tcpSocket:
              port: 6555
            periodSeconds: 10
            failureThreshold: 30
          readinessProbe:
            tcpSocket:
              port: 6555
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 6555
            periodSeconds: 30
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: spindle-data
        - name: logs
          emptyDir: {}
