apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml

images:
  - name: docker.io/heywoodlh/spindle
    newTag: "c38881b4"
