apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml

images:
  - name: docker.io/heywoodlh/spindle
    newTag: latest
    digest: sha256:7f2dd3200885a799abbf2c8480ec546d24d48cf75c102d8b929e3b0f8c75b9f7
