apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spindle-data
  namespace: tangled
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hcloud-volumes
  resources:
    requests:
      storage: 20Gi
