# This is a basic workflow to help you get started with Actions

name: infrastructure

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  render-jsonnet:
    name: jsonnet-render
    runs-on: ubuntu-latest
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    # Checkout the repository to the GitHub Actions runner
    steps:
    - uses: actions/checkout@v2
    - name: Add credentials
      run: |
        echo "${{ secrets.CREDENTIALS }}" > secrets/credentials.libsonnet
    - name: jsonnet-render
      uses: alexdglover/jsonnet-render@v1
      with:
        file: main.jsonnet
        output_dir: ./
    - name: Upload cluster.yml
      uses: actions/upload-artifact@v1
      with:
        name: cluster.yml
        path: ./cluster.yml
    - name: Upload main.tf.json
      uses: actions/upload-artifact@v1
      with:
        name: main.tf.json
        path: ./main.tf.json

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1.0.1
      with:
        cli_config_credentials_hostname: app.terraform.io # optional, default is app.terraform.io
        cli_config_credentials_token: ${{ secrets.TERRAFORM_TOKEN }} # optional
    - name: Terraform Init
      run: terraform init
    - name: Terraform Plan
      run: terraform plan
