apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: coder-secrets
    namespace: coder
spec:
    secretTemplates:
        - name: coder-oidc
          annotations:
            reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
            reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: authentik
            reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
            reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: authentik
          stringData:
            client-secret: ENC[AES256_GCM,data:5P3Op+X6+ZkwpoTY7O+3a5+dXw9diG0VJA39gEUyzDT6y/SlctAuKCcPRYaVpAaHxatnL8IT38lr/+WnIJuI8w==,iv:SFkGQ1mOPM9c/sGRvo3HdfY6/GQfkWv+u6IA9MDftdY=,tag:NFUCJhPf2nIM4/BXxgBzkg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nhsx40cf26syk9jt8hkd0grdrc9qc45sk52cl5vy0d78fxl2f4hs4h7laa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGV2k5bkREbG1HZFZqUkQy
            WXJHQlo5M24zd2dMMFljT2xjNWIrWnNHbm1VCkhCMWE1VmxqZ3NuYjBNeFlBZHox
            U1hmZlI3OXFUVms2b2NiNXZiTHpudWMKLS0tIDhRSFJYYXZJeWs3UDNqRXpVMVRy
            UVc0OWt6K25Gd0xSbGdKUTY2RDIzTlUKIEpabzyKkapblrW1cB7Krir9HiCCJkW0
            B5GuH3WYWL8UCpi8E3MtCrYzrPFcS+GlgTuybepKHL2nHoesDvaZ5Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gzf883y8p0wfy5yjn5l3l2axnqxdgtw2zdcp8jqsrk65m7gf6y6qzgkf63
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dENpOTRaZUR4V3pDdkRm
            aEhXOURzNGRVRVBKUFpvWU10em9Uc0tYQ213CnV6WHJBWW0yRitXellmdE1Gc2Yr
            eXB4YlFCOGo1emg1U0dhaGcwNVFZTlkKLS0tIHJ5V29yUEFQd3ZwcnJuS1NKZ3Nn
            cFhkKysvOHRKb3ZMTVdkUktGRjM0YlUKHqkQo1Uk5F3PnpBnPl0ZLhB+Uy2xjeKe
            ACDYa5tDYk0S4yuBsv1TnXeLLJ3QfnhoHFbJi16cNeumlZoVcqRDmw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1eagn023gem8ekv6q8gx7rc37x2rsxfscpyt2znd4j5l8ryehksdqzjek59
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqaXpYc1p0UldNVDgxMW9F
            bzZTekxlOW1NT3lnQ0hlWDg2eEs0aklFUGxVClhqV0xQbFhrNXFjZ0pLbDdkS2Fm
            VG14L09yeVJHZldNMkV6TzFadlE2d0kKLS0tIGE0QVBTeU1WbFRidzVWOXA1d1VQ
            NlhBUVZSN1A5QUdYZzgxc1lvZzZoWFEK6q9n3/RqnHo07H1CqpmRpjUSjZAfgJ7j
            E3kY+90igeTGnxWcZhNi4PhZBRFNN8q+Htq8daalrKkQ6Ix4SKA2jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-05T01:35:16Z"
    mac: ENC[AES256_GCM,data:xXguDApyguazIVXtA7IfRDv+9J39q/FpKkv3JCCn5ES4i0BWu4UIxHcMux5mrYMkTxR0TO69m8XC4W0813kkqLq9hF7qihaBKr+v3eQ2n3KWvZJpDgkL80NmMSmn5y9N4ELB/eFw5NKPKBaxjC2KSariaiopboCvC/2nLsiHk+k=,iv:UYiDiwKb6ZguKC9hoQV6mch8wfmx7flF29y8qRdTpvY=,tag:UjZifUoOVIDeFVheligqgA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
